In [ ]:
#!git clone https://github.com/whyhardt/SPICE.git

In [ ]:
# !pip install -e SPICE

In [1]:
import sys

import torch

from spice import SpiceEstimator

sys.path.append("../../..")
from weinhardt2026.utils.benchmarking_gru import GRUModel, training
from weinhardt2026.studies.castro2025.benchmarking_castro2025 import Castro2025Model, get_dataset, generate_behavior
import spice_castro2025, spice_castro2025_2

## Load dataset

In [2]:
path_data = 'data/eckstein2024.csv'
test_sessions = (2,)  # pick sessions that exist for all participants; adjust if needed
dataset_train, dataset_test, info_dataset = get_dataset(path_data=path_data, test_sessions=test_sessions, verbose=True)

Shape of dataset: torch.Size([4158, 150, 1, 13])
Number of participants: 862
Number of actions in dataset: 4

In [3]:
from spice import SpiceDataset

# keep only 100 timesteps
dataset_train = SpiceDataset(dataset_train.xs[:, :100], dataset_train.ys[:, :100])

# keep only 100 participants for rapid prototyping
keep_participants = torch.arange(0, 50)

def keep_subset(dataset, subset):
    participant_ids = dataset.xs[:, 0, 0, -1]
    mask = torch.isin(participant_ids, subset)
    return SpiceDataset(dataset.xs[mask], dataset.ys[mask])

dataset_train = keep_subset(dataset_train, keep_participants)
dataset_test = keep_subset(dataset_test, keep_participants)

## SPICE Setup

## SPICE Training

Let's setup now the `SpiceEstimator` object and fit it to the data! 

We are going to do this in two steps:

1. Without fitting the SINDy coefficients to get the pure RNN performance given the selected architecture. 
2. With fitting SINDy coefficients to get the final performance of the interpretable model

That way we can disentangle the gap between GRU and SPICE w.r.t. architecture and SINDy library

In [ ]:
# fitting without SINDy coefficients
path_spice = 'params/spice_castro2025_2.pkl'

estimator = SpiceEstimator(
        # model paramaeters
        spice_class=spice_castro2025_2.SpiceModel,
        spice_config=spice_castro2025_2.CONFIG,
        n_actions=dataset_train.n_actions,
        n_participants=dataset_train.n_participants,
        
        epochs=1,
        
        sindy_weight=0,
        sindy_library_polynomial_degree=2,
        sindy_pruning_frequency=100,
        sindy_ensemble_pruning=0.05,
        sindy_threshold_pruning=0.01,
        sindy_alpha=0.0001,
        
        save_path_spice=path_spice,
        verbose=True,
    )
estimator.fit(dataset_train.xs, dataset_train.ys, dataset_test.xs, dataset_test.ys)

In [18]:
path_spice = 'params/spice_castro2025_2.pkl'

estimator = SpiceEstimator(
        # model paramaeters
        spice_class=spice_castro2025_2.SpiceModel,
        spice_config=spice_castro2025_2.CONFIG,
        n_actions=dataset_train.n_actions,
        n_participants=dataset_train.n_participants,
        
        epochs=1000,
        warmup_steps=200,
        learning_rate=0.01,
        ensemble_size=10,
        
        sindy_weight=0.1,
        sindy_alpha=0.0001,
        sindy_pruning_frequency=100,
        sindy_threshold_pruning=0.01,
        sindy_ensemble_pruning=0.05,
        sindy_library_polynomial_degree=2,

        verbose=True,
        # device = torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
        save_path_spice=path_spice,
    )

In [ ]:
estimator.fit(dataset_train.xs, dataset_train.ys, dataset_test.xs, dataset_test.ys)

================================================================================================================================================================
 24%|████████▉                            | 243/1000 [19:54<1:02:01,  4.92s/it, L(Train)=0.4903638, L(Val,RNN)=0.5158772, L(Val,SINDy)=0.8586412, Conv=1.40e-03]
----------------------------------------------------------------------------------------------------------------------------------------------------------------
SPICE Model (Coefficients: 37):
value_reward_env[t+1]        = -0.04 1 + 0.961 value_reward_env[t] + 0.001 reward[t] + -0.005 value_reward_env^2 + -0.013 value_reward_env*reward[t] + 0.005 reward[t]^2
value_reward_chosen[t+1]     = -0.377 1 + 1.005 value_reward_chosen[t] + 0.064 reward_env + 0.223 reward[t] + -0.005 value_reward_chosen^2 + 0.02 value_reward_chosen*reward_env + -0.149 value_reward_chosen*reward[t] + -0.005 reward_env^2 + -0.122 reward_env*reward[t] + 0.453 reward[t]^2
value_reward_not_chosen[t+1] = -0.008 1 + 0.985 value_reward_not_chosen[t] + 0.014 reward_env + -0.003 value_reward_not_chosen^2 + 0.002 value_reward_not_chosen*reward_env + 0.001 reward_env^2
value_choice_chosen[t+1]     = 0.208 1 + 0.834 value_choice_chosen[t] + 0.012 value_choice_chosen^2
value_choice_not_chosen[t+1] = -0.068 1 + 0.39 value_choice_not_chosen[t] + -0.2 value_choice_not_chosen^2
volatility_chosen[t+1]       = 0.206 1 + 0.849 volatility_chosen[t] + 2.039 dvalue + -0.025 volatility_chosen^2 + 0.227 volatility_chosen*dvalue + -0.428 dvalue^2
volatility_not_chosen[t+1]   = -0.051 1 + 0.66 volatility_not_chosen[t] + -0.052 volatility_not_chosen^2
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Pruning patience:
value_reward_env:        1, 0, 1, 1, 1, 1
value_reward_chosen:     0, 1, 1, 0, 1, 1, 1, 1, 1, 0
value_reward_not_chosen: 1, 1, 1, 1, 1, 1
value_choice_chosen:     0, 0, 1
value_choice_not_chosen: 1, 0, 0
volatility_chosen:       1, 0, 0, 1, 0, 1
volatility_not_chosen:   1, 0, 1
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Term presence across SPICE models (number of models=50):
value_reward_env:        50, 50, 50, 50, 50, 50
value_reward_chosen:     50, 50, 50, 50, 50, 50, 50, 50, 50, 50
value_reward_not_chosen: 50, 50, 50, 50, 50, 50
value_choice_chosen:     50, 50, 50
value_choice_not_chosen: 50, 50, 50
volatility_chosen:       50, 50, 50, 50, 50, 50
volatility_not_chosen:   50, 50, 50
================================================================================================================================================================

Training interrupted. Continuing with further operations...

================================================================================
Stage 2: SINDy refit
================================================================================

  6%|▌         | 55/1000 [00:18<06:09,  2.56it/s, loss=0.0244261, n_params=37.00+/-0.00]

In [19]:
estimator.load_spice(path_spice)
# estimator.aggregate_coefficients()

In [20]:
# Print example SPICE model for first participant
print("\nExample SPICE model (participant 0):")
estimator.print_spice_model(participant_id=0)

Example SPICE model (participant 0):
value_reward_env[t+1]        = 0.221 1 + 0.945 value_reward_env[t] + 0.024 reward[t] + -0.011 value_reward_env^2 + -0.039 value_reward_env*reward[t] + 0.018 reward[t]^2
value_reward_chosen[t+1]     = -0.189 1 + 0.945 value_reward_chosen[t] + -0.072 reward_env + 0.26 reward[t] + 0.021 value_reward_mean + -0.003 value_reward_chosen^2 + -0.012 value_reward_chosen*reward_env + -0.124 value_reward_chosen*reward[t] + 0.02 value_reward_chosen*value_reward_mean + -0.016 reward_env^2 + 0.145 reward_env*reward[t] + 0.011 reward_env*value_reward_mean + 0.521 reward[t]^2 + -0.107 reward[t]*value_reward_mean + -0.018 value_reward_mean^2
value_reward_not_chosen[t+1] = -0.274 1 + 0.796 value_reward_not_chosen[t] + -0.174 reward_env + 0.148 value_reward_mean + -0.008 value_reward_not_chosen^2 + -0.131 value_reward_not_chosen*reward_env + 0.091 value_reward_not_chosen*value_reward_mean + -0.079 reward_env^2 + 0.052 reward_env*value_reward_mean + -0.026 value_reward_mean^2
value_choice_chosen[t+1]     = -1.067 1 + -0.134 value_choice_chosen[t] + 0.21 value_choice_mean + -0.031 value_choice_chosen^2 + -0.018 value_choice_chosen*value_choice_mean + 0.007 value_choice_mean^2
value_choice_not_chosen[t+1] = 0.156 1 + 0.964 value_choice_not_chosen[t] + 0.016 value_choice_mean + -0.026 value_choice_not_chosen^2 + 0.006 value_choice_not_chosen*value_choice_mean + 0.0 value_choice_mean^2
volatility_chosen[t+1]       = 0.05 1 + 0.851 volatility_chosen[t] + 1.456 dvalue + -0.074 volatility_chosen^2 + -0.239 volatility_chosen*dvalue + -0.102 dvalue^2
volatility_not_chosen[t+1]   = -0.041 1 + 0.974 volatility_not_chosen[t] + 0.133 dvalue + 0.003 volatility_not_chosen^2 + -0.034 volatility_not_chosen*dvalue + 0.065 dvalue^2

## Benchmarking

### Castro2025 benchmark model

In [23]:
path_spice = 'params/spice_castro2025.pkl'

# Benchmark model: Castro et al. 2025
cfs = Castro2025Model(
    n_participants=dataset_train.n_participants,
    n_actions=dataset_train.n_actions,
    batch_first=True,
    )

path_cfs = path_spice.replace('spice_', 'cfs_')

In [ ]:
optimizer_cfs = torch.optim.Adam(params=cfs.parameters(), lr=0.01)
epochs = 1000

cfs = training(
    model=cfs,
    optimizer=optimizer_cfs,
    dataset_train=dataset_train,
    dataset_test=dataset_test,
    epochs=epochs,
)

torch.save(cfs.state_dict(), path_cfs)

In [12]:
cfs.load_state_dict(torch.load(path_cfs, map_location='cpu'))

### GRU Model

In [13]:
gru = GRUModel(
    n_actions=dataset_train.n_actions, 
    additional_inputs=2, 
    dropout=0.1,
    hidden_size=32,
    )
path_gru = path_spice.replace('spice_', 'gru_')

In [9]:
epochs = 1000
optimizer_gru = torch.optim.Adam(gru.parameters(), lr=0.01)

gru = training(
    model=gru,
    optimizer=optimizer_gru,
    dataset_train=dataset_train,
    dataset_test=dataset_test,
    epochs=epochs,
    ).to(torch.device('cpu'))

torch.save(gru.state_dict(), path_gru)

Epoch 1/1000: L(Train): 1.4684736728668213; L(Test): 1.5077646970748901
Epoch 2/1000: L(Train): 1.4892171621322632; L(Test): 1.4341553449630737
Epoch 3/1000: L(Train): 1.4499824047088623; L(Test): 1.3870218992233276
Epoch 4/1000: L(Train): 1.399340033531189; L(Test): 1.3862683773040771
Epoch 5/1000: L(Train): 1.3948732614517212; L(Test): 1.389448642730713
Epoch 6/1000: L(Train): 1.3978655338287354; L(Test): 1.3850520849227905
Epoch 7/1000: L(Train): 1.3922415971755981; L(Test): 1.3773967027664185
Epoch 8/1000: L(Train): 1.3848704099655151; L(Test): 1.3699711561203003
Epoch 9/1000: L(Train): 1.377264142036438; L(Test): 1.3622416257858276
Epoch 10/1000: L(Train): 1.3698391914367676; L(Test): 1.3585764169692993
Epoch 11/1000: L(Train): 1.365770936012268; L(Test): 1.3521857261657715
Epoch 12/1000: L(Train): 1.3602874279022217; L(Test): 1.3406612873077393
Epoch 13/1000: L(Train): 1.350714087486267; L(Test): 1.331235408782959
Epoch 14/1000: L(Train): 1.3407236337661743; L(Test): 1.319174885749817
Epoch 15/1000: L(Train): 1.3287737369537354; L(Test): 1.3013224601745605
Epoch 16/1000: L(Train): 1.3117144107818604; L(Test): 1.2879385948181152
Epoch 17/1000: L(Train): 1.2998100519180298; L(Test): 1.2717082500457764
Epoch 18/1000: L(Train): 1.2831131219863892; L(Test): 1.2561259269714355
Epoch 19/1000: L(Train): 1.2672456502914429; L(Test): 1.2351486682891846
Epoch 20/1000: L(Train): 1.25248384475708; L(Test): 1.2144217491149902
Epoch 21/1000: L(Train): 1.2325206995010376; L(Test): 1.1846141815185547
Epoch 22/1000: L(Train): 1.2107973098754883; L(Test): 1.1438723802566528
Epoch 23/1000: L(Train): 1.1858625411987305; L(Test): 1.1118199825286865
Epoch 24/1000: L(Train): 1.157930850982666; L(Test): 1.1473305225372314
Epoch 25/1000: L(Train): 1.1646621227264404; L(Test): 1.2565758228302002
Epoch 26/1000: L(Train): 1.1902092695236206; L(Test): 1.0118597745895386
Epoch 27/1000: L(Train): 1.0905143022537231; L(Test): 1.1833765506744385
Epoch 28/1000: L(Train): 1.1499460935592651; L(Test): 0.9360814690589905
Epoch 29/1000: L(Train): 1.0512940883636475; L(Test): 1.1102162599563599
Epoch 30/1000: L(Train): 1.0938042402267456; L(Test): 0.9484727382659912
Epoch 31/1000: L(Train): 1.0265676975250244; L(Test): 0.9523177146911621
Epoch 32/1000: L(Train): 1.0250482559204102; L(Test): 0.9273300170898438
Epoch 33/1000: L(Train): 0.9967082738876343; L(Test): 0.8812156915664673
Epoch 34/1000: L(Train): 0.9553048610687256; L(Test): 0.9133585095405579
Epoch 35/1000: L(Train): 0.9686617255210876; L(Test): 0.8640523552894592
Epoch 36/1000: L(Train): 0.9185753464698792; L(Test): 0.8823984861373901
Epoch 37/1000: L(Train): 0.9342762231826782; L(Test): 0.9080715775489807
Epoch 38/1000: L(Train): 0.948798418045044; L(Test): 0.7861372232437134
Epoch 39/1000: L(Train): 0.8722008466720581; L(Test): 0.8640056848526001
Epoch 40/1000: L(Train): 0.9147031307220459; L(Test): 0.7654851078987122
Epoch 41/1000: L(Train): 0.8403370976448059; L(Test): 0.8095918893814087
Epoch 42/1000: L(Train): 0.8752102255821228; L(Test): 0.7498708963394165
Epoch 43/1000: L(Train): 0.8156993985176086; L(Test): 0.7836789488792419
Epoch 44/1000: L(Train): 0.831256091594696; L(Test): 0.7855382561683655
Epoch 45/1000: L(Train): 0.8150510191917419; L(Test): 0.7446317076683044
Epoch 46/1000: L(Train): 0.7833544611930847; L(Test): 0.7524465322494507
Epoch 47/1000: L(Train): 0.8024110794067383; L(Test): 0.7358331084251404
Epoch 48/1000: L(Train): 0.7667370438575745; L(Test): 0.7549875378608704
Epoch 49/1000: L(Train): 0.7781561017036438; L(Test): 0.742935061454773
Epoch 50/1000: L(Train): 0.7636109590530396; L(Test): 0.7323110103607178
Epoch 51/1000: L(Train): 0.7531353831291199; L(Test): 0.7317670583724976
Epoch 52/1000: L(Train): 0.7523564696311951; L(Test): 0.725986897945404
Epoch 53/1000: L(Train): 0.7419144511222839; L(Test): 0.71957927942276
Epoch 54/1000: L(Train): 0.7319188117980957; L(Test): 0.7192167043685913
Epoch 55/1000: L(Train): 0.73332679271698; L(Test): 0.7096256613731384
Epoch 56/1000: L(Train): 0.724600076675415; L(Test): 0.7016950845718384
Epoch 57/1000: L(Train): 0.7167050242424011; L(Test): 0.7007721066474915
Epoch 58/1000: L(Train): 0.7169550061225891; L(Test): 0.6940385699272156
Epoch 59/1000: L(Train): 0.7097574472427368; L(Test): 0.6894093155860901
Epoch 60/1000: L(Train): 0.7033863663673401; L(Test): 0.6887825727462769
Epoch 61/1000: L(Train): 0.7032773494720459; L(Test): 0.6856852769851685
Epoch 62/1000: L(Train): 0.6994143724441528; L(Test): 0.6824626326560974
Epoch 63/1000: L(Train): 0.6946263313293457; L(Test): 0.6812681555747986
Epoch 64/1000: L(Train): 0.6928178668022156; L(Test): 0.6801024675369263
Epoch 65/1000: L(Train): 0.6913801431655884; L(Test): 0.6781710982322693
Epoch 66/1000: L(Train): 0.6878170371055603; L(Test): 0.6758970618247986
Epoch 67/1000: L(Train): 0.6850429773330688; L(Test): 0.6746288537979126
Epoch 68/1000: L(Train): 0.6826063990592957; L(Test): 0.6740142107009888
Epoch 69/1000: L(Train): 0.6809000372886658; L(Test): 0.6723067760467529
Epoch 70/1000: L(Train): 0.6789354085922241; L(Test): 0.6702913641929626
Epoch 71/1000: L(Train): 0.6758691668510437; L(Test): 0.6690274477005005
Epoch 72/1000: L(Train): 0.674964189529419; L(Test): 0.6678270697593689
Epoch 73/1000: L(Train): 0.6739268898963928; L(Test): 0.6664599776268005
Epoch 74/1000: L(Train): 0.6721567511558533; L(Test): 0.6652548313140869
Epoch 75/1000: L(Train): 0.6705640554428101; L(Test): 0.6643105745315552
Epoch 76/1000: L(Train): 0.6693325042724609; L(Test): 0.6635462045669556
Epoch 77/1000: L(Train): 0.6680160760879517; L(Test): 0.6624536514282227
Epoch 78/1000: L(Train): 0.6671967506408691; L(Test): 0.6611198782920837
Epoch 79/1000: L(Train): 0.6651331186294556; L(Test): 0.6601608395576477
Epoch 80/1000: L(Train): 0.6638878583908081; L(Test): 0.6593815088272095
Epoch 81/1000: L(Train): 0.663460373878479; L(Test): 0.6584692597389221
Epoch 82/1000: L(Train): 0.6624159812927246; L(Test): 0.6575599312782288
Epoch 83/1000: L(Train): 0.6610501408576965; L(Test): 0.6569353938102722
Epoch 84/1000: L(Train): 0.6602375507354736; L(Test): 0.6565526723861694
Epoch 85/1000: L(Train): 0.6594117283821106; L(Test): 0.6561111807823181
Epoch 86/1000: L(Train): 0.6587808728218079; L(Test): 0.6553861498832703
Epoch 87/1000: L(Train): 0.6577522158622742; L(Test): 0.6544708609580994
Epoch 88/1000: L(Train): 0.6570175290107727; L(Test): 0.6536208391189575
Epoch 89/1000: L(Train): 0.6562375426292419; L(Test): 0.6529701352119446
Epoch 90/1000: L(Train): 0.6549754738807678; L(Test): 0.6524728536605835
Epoch 91/1000: L(Train): 0.6542291045188904; L(Test): 0.6520629525184631
Epoch 92/1000: L(Train): 0.6538819670677185; L(Test): 0.6516817212104797
Epoch 93/1000: L(Train): 0.6534838080406189; L(Test): 0.6511980891227722
Epoch 94/1000: L(Train): 0.6523374319076538; L(Test): 0.6505633592605591
Epoch 95/1000: L(Train): 0.6517016291618347; L(Test): 0.6498855948448181
Epoch 96/1000: L(Train): 0.6512358784675598; L(Test): 0.6492483019828796
Epoch 97/1000: L(Train): 0.6506882309913635; L(Test): 0.6487349271774292
Epoch 98/1000: L(Train): 0.6498827934265137; L(Test): 0.6483030915260315
Epoch 99/1000: L(Train): 0.6491851806640625; L(Test): 0.6478478312492371
Epoch 100/1000: L(Train): 0.6485310792922974; L(Test): 0.6473864912986755
Epoch 101/1000: L(Train): 0.6480324268341064; L(Test): 0.6469376087188721
Epoch 102/1000: L(Train): 0.6480640172958374; L(Test): 0.6464729309082031
Epoch 103/1000: L(Train): 0.6473791599273682; L(Test): 0.6460357904434204
Epoch 104/1000: L(Train): 0.6464198231697083; L(Test): 0.6456165909767151
Epoch 105/1000: L(Train): 0.6462669968605042; L(Test): 0.6451954245567322
Epoch 106/1000: L(Train): 0.6457626819610596; L(Test): 0.6447490453720093
Epoch 107/1000: L(Train): 0.6450145244598389; L(Test): 0.644296407699585
Epoch 108/1000: L(Train): 0.6446690559387207; L(Test): 0.6438947319984436
Epoch 109/1000: L(Train): 0.644711971282959; L(Test): 0.6435614228248596
Epoch 110/1000: L(Train): 0.6437072157859802; L(Test): 0.6432048678398132
Epoch 111/1000: L(Train): 0.6431324481964111; L(Test): 0.6427547931671143
Epoch 112/1000: L(Train): 0.6430684924125671; L(Test): 0.6422761678695679
Epoch 113/1000: L(Train): 0.642255425453186; L(Test): 0.6417478322982788
Epoch 114/1000: L(Train): 0.6417738795280457; L(Test): 0.6412902474403381
Epoch 115/1000: L(Train): 0.6411697268486023; L(Test): 0.6408833265304565
Epoch 116/1000: L(Train): 0.6411183476448059; L(Test): 0.6405176520347595
Epoch 117/1000: L(Train): 0.6406217217445374; L(Test): 0.6401477456092834
Epoch 118/1000: L(Train): 0.6402378082275391; L(Test): 0.6397198438644409
Epoch 119/1000: L(Train): 0.6393766403198242; L(Test): 0.6392034888267517
Epoch 120/1000: L(Train): 0.6390331983566284; L(Test): 0.6386975646018982
Epoch 121/1000: L(Train): 0.6382140517234802; L(Test): 0.6382503509521484
Epoch 122/1000: L(Train): 0.6381402611732483; L(Test): 0.6378481388092041
Epoch 123/1000: L(Train): 0.6378954648971558; L(Test): 0.6374505758285522
Epoch 124/1000: L(Train): 0.6372645497322083; L(Test): 0.6370037198066711
Epoch 125/1000: L(Train): 0.6368379592895508; L(Test): 0.6365278363227844
Epoch 126/1000: L(Train): 0.6360554099082947; L(Test): 0.6360469460487366
Epoch 127/1000: L(Train): 0.6359606981277466; L(Test): 0.6356285810470581
Epoch 128/1000: L(Train): 0.6350072026252747; L(Test): 0.6352275013923645
Epoch 129/1000: L(Train): 0.6352096199989319; L(Test): 0.6348403096199036
Epoch 130/1000: L(Train): 0.6349276900291443; L(Test): 0.6344205141067505
Epoch 131/1000: L(Train): 0.634397566318512; L(Test): 0.6339800357818604
Epoch 132/1000: L(Train): 0.6337054371833801; L(Test): 0.6335537433624268
Epoch 133/1000: L(Train): 0.6337165832519531; L(Test): 0.6331656575202942
Epoch 134/1000: L(Train): 0.6329602599143982; L(Test): 0.6327596306800842
Epoch 135/1000: L(Train): 0.632804274559021; L(Test): 0.6323726177215576
Epoch 136/1000: L(Train): 0.632217526435852; L(Test): 0.6319617033004761
Epoch 137/1000: L(Train): 0.6322041749954224; L(Test): 0.6315068602561951
Epoch 138/1000: L(Train): 0.6313311457633972; L(Test): 0.6310548782348633
Epoch 139/1000: L(Train): 0.6305552124977112; L(Test): 0.6306304931640625
Epoch 140/1000: L(Train): 0.6303980946540833; L(Test): 0.6302264332771301
Epoch 141/1000: L(Train): 0.6299488544464111; L(Test): 0.6297942399978638
Epoch 142/1000: L(Train): 0.6293505430221558; L(Test): 0.6293898820877075
Epoch 143/1000: L(Train): 0.6289660334587097; L(Test): 0.6290046572685242
Epoch 144/1000: L(Train): 0.6288617253303528; L(Test): 0.6285931468009949
Epoch 145/1000: L(Train): 0.6283361911773682; L(Test): 0.6282038688659668
Epoch 146/1000: L(Train): 0.6278021335601807; L(Test): 0.6278429627418518
Epoch 147/1000: L(Train): 0.6276330351829529; L(Test): 0.6274019479751587
Epoch 148/1000: L(Train): 0.6274345517158508; L(Test): 0.6270168423652649
Epoch 149/1000: L(Train): 0.6266852617263794; L(Test): 0.6266367435455322
Epoch 150/1000: L(Train): 0.6264111399650574; L(Test): 0.6262423992156982
Epoch 151/1000: L(Train): 0.6256878972053528; L(Test): 0.6258516311645508
Epoch 152/1000: L(Train): 0.6254750490188599; L(Test): 0.6254615187644958
Epoch 153/1000: L(Train): 0.6253498196601868; L(Test): 0.6250418424606323
Epoch 154/1000: L(Train): 0.6244163513183594; L(Test): 0.6246206760406494
Epoch 155/1000: L(Train): 0.6247498989105225; L(Test): 0.6242232918739319
Epoch 156/1000: L(Train): 0.6241641044616699; L(Test): 0.6238498687744141
Epoch 157/1000: L(Train): 0.6239733099937439; L(Test): 0.623376190662384
Epoch 158/1000: L(Train): 0.6230877041816711; L(Test): 0.6230360865592957
Epoch 159/1000: L(Train): 0.6228637099266052; L(Test): 0.6225447058677673
Epoch 160/1000: L(Train): 0.622747004032135; L(Test): 0.6221444606781006
Epoch 161/1000: L(Train): 0.6219443082809448; L(Test): 0.6218169331550598
Epoch 162/1000: L(Train): 0.6218815445899963; L(Test): 0.6213635206222534
Epoch 163/1000: L(Train): 0.6213470101356506; L(Test): 0.6209232807159424
Epoch 164/1000: L(Train): 0.6211292147636414; L(Test): 0.6207024455070496
Epoch 165/1000: L(Train): 0.6207504272460938; L(Test): 0.6201207041740417
Epoch 166/1000: L(Train): 0.62038654088974; L(Test): 0.6196781992912292
Epoch 167/1000: L(Train): 0.6195610761642456; L(Test): 0.6193569898605347
Epoch 168/1000: L(Train): 0.6193415522575378; L(Test): 0.6187722682952881
Epoch 169/1000: L(Train): 0.6189150810241699; L(Test): 0.6183739304542542
Epoch 170/1000: L(Train): 0.6189799904823303; L(Test): 0.6180633306503296
Epoch 171/1000: L(Train): 0.618054211139679; L(Test): 0.6175099611282349
Epoch 172/1000: L(Train): 0.6179494857788086; L(Test): 0.6171231865882874
Epoch 173/1000: L(Train): 0.6177942156791687; L(Test): 0.6165835857391357
Epoch 174/1000: L(Train): 0.6168001890182495; L(Test): 0.6161904335021973
Epoch 175/1000: L(Train): 0.6166749000549316; L(Test): 0.6158128380775452
Epoch 176/1000: L(Train): 0.6164729595184326; L(Test): 0.6153044700622559
Epoch 177/1000: L(Train): 0.6162570118904114; L(Test): 0.6151236295700073
Epoch 178/1000: L(Train): 0.6155217885971069; L(Test): 0.614565908908844
Epoch 179/1000: L(Train): 0.6157753467559814; L(Test): 0.6143144965171814
Epoch 180/1000: L(Train): 0.6155451536178589; L(Test): 0.6136752963066101
Epoch 181/1000: L(Train): 0.6147663593292236; L(Test): 0.6133652925491333
Epoch 182/1000: L(Train): 0.6141691207885742; L(Test): 0.6127467155456543
Epoch 183/1000: L(Train): 0.6134523749351501; L(Test): 0.6124153137207031
Epoch 184/1000: L(Train): 0.6132102608680725; L(Test): 0.6118849515914917
Epoch 185/1000: L(Train): 0.6129676699638367; L(Test): 0.6115649342536926
Epoch 186/1000: L(Train): 0.6125584840774536; L(Test): 0.6110045313835144
Epoch 187/1000: L(Train): 0.6117148995399475; L(Test): 0.610593855381012
Epoch 188/1000: L(Train): 0.6117417812347412; L(Test): 0.610057532787323
Epoch 189/1000: L(Train): 0.6114829778671265; L(Test): 0.6101717352867126
Epoch 190/1000: L(Train): 0.6110093593597412; L(Test): 0.610274076461792
Epoch 191/1000: L(Train): 0.6117463111877441; L(Test): 0.6114289164543152
Epoch 192/1000: L(Train): 0.6121679544448853; L(Test): 0.6113821268081665
Epoch 193/1000: L(Train): 0.612686812877655; L(Test): 0.6090523600578308
Epoch 194/1000: L(Train): 0.6101522445678711; L(Test): 0.608708381652832
Epoch 195/1000: L(Train): 0.6098455786705017; L(Test): 0.6100141406059265
Epoch 196/1000: L(Train): 0.6112287044525146; L(Test): 0.6077558994293213
Epoch 197/1000: L(Train): 0.6090726256370544; L(Test): 0.6067386865615845
Epoch 198/1000: L(Train): 0.6080304384231567; L(Test): 0.6081873178482056
Epoch 199/1000: L(Train): 0.6095576286315918; L(Test): 0.6062467694282532
Epoch 200/1000: L(Train): 0.6076536178588867; L(Test): 0.6059174537658691
Epoch 201/1000: L(Train): 0.6075935959815979; L(Test): 0.6063185930252075
Epoch 202/1000: L(Train): 0.6076242327690125; L(Test): 0.6043195128440857
Epoch 203/1000: L(Train): 0.6056668758392334; L(Test): 0.604770302772522
Epoch 204/1000: L(Train): 0.6068384051322937; L(Test): 0.6046170592308044
Epoch 205/1000: L(Train): 0.606237530708313; L(Test): 0.6031162738800049
Epoch 206/1000: L(Train): 0.604739248752594; L(Test): 0.6035341620445251
Epoch 207/1000: L(Train): 0.6051927208900452; L(Test): 0.6030300259590149
Epoch 208/1000: L(Train): 0.604841411113739; L(Test): 0.6019148230552673
Epoch 209/1000: L(Train): 0.6040686368942261; L(Test): 0.6019071936607361
Epoch 210/1000: L(Train): 0.6031876802444458; L(Test): 0.6017062067985535
Epoch 211/1000: L(Train): 0.6032965183258057; L(Test): 0.6005117893218994
Epoch 212/1000: L(Train): 0.6026574969291687; L(Test): 0.6002798676490784
Epoch 213/1000: L(Train): 0.601969301700592; L(Test): 0.6002950072288513
Epoch 214/1000: L(Train): 0.6022975444793701; L(Test): 0.599180281162262
Epoch 215/1000: L(Train): 0.6008896827697754; L(Test): 0.5986086130142212
Epoch 216/1000: L(Train): 0.6005104780197144; L(Test): 0.5985714793205261
Epoch 217/1000: L(Train): 0.6008304357528687; L(Test): 0.5980091691017151
Epoch 218/1000: L(Train): 0.6002447605133057; L(Test): 0.5972479581832886
Epoch 219/1000: L(Train): 0.5992446541786194; L(Test): 0.5966916680335999
Epoch 220/1000: L(Train): 0.5986753106117249; L(Test): 0.5964006185531616
Epoch 221/1000: L(Train): 0.5983536243438721; L(Test): 0.5958797931671143
Epoch 222/1000: L(Train): 0.5978812575340271; L(Test): 0.5952215790748596
Epoch 223/1000: L(Train): 0.5978158712387085; L(Test): 0.5948565602302551
Epoch 224/1000: L(Train): 0.5970500707626343; L(Test): 0.5946029424667358
Epoch 225/1000: L(Train): 0.59698486328125; L(Test): 0.5936113595962524
Epoch 226/1000: L(Train): 0.5962232947349548; L(Test): 0.5930285453796387
Epoch 227/1000: L(Train): 0.5957566499710083; L(Test): 0.5928487777709961
Epoch 228/1000: L(Train): 0.5956022143363953; L(Test): 0.5923228859901428
Epoch 229/1000: L(Train): 0.5950186252593994; L(Test): 0.591897189617157
Epoch 230/1000: L(Train): 0.5946455001831055; L(Test): 0.591254472732544
Epoch 231/1000: L(Train): 0.5947243571281433; L(Test): 0.5907052755355835
Epoch 232/1000: L(Train): 0.5938001871109009; L(Test): 0.5904847383499146
Epoch 233/1000: L(Train): 0.5938065052032471; L(Test): 0.5912781953811646
Epoch 234/1000: L(Train): 0.5942597985267639; L(Test): 0.5968995094299316
Epoch 235/1000: L(Train): 0.599861741065979; L(Test): 0.60439532995224
Epoch 236/1000: L(Train): 0.6066733598709106; L(Test): 0.6118789911270142
Epoch 237/1000: L(Train): 0.6132901310920715; L(Test): 0.5943547487258911
Epoch 238/1000: L(Train): 0.5966957807540894; L(Test): 0.6095346212387085
Epoch 239/1000: L(Train): 0.6127782464027405; L(Test): 0.5935487151145935
Epoch 240/1000: L(Train): 0.5958725810050964; L(Test): 0.6068072319030762
Epoch 241/1000: L(Train): 0.6086606979370117; L(Test): 0.5909538865089417
Epoch 242/1000: L(Train): 0.5936360359191895; L(Test): 0.5996831059455872
Epoch 243/1000: L(Train): 0.6034247279167175; L(Test): 0.5902720093727112
Epoch 244/1000: L(Train): 0.5938513875007629; L(Test): 0.5947669148445129
Epoch 245/1000: L(Train): 0.5976806282997131; L(Test): 0.5937982201576233
Epoch 246/1000: L(Train): 0.5961582064628601; L(Test): 0.5889227390289307
Epoch 247/1000: L(Train): 0.5916375517845154; L(Test): 0.5932625532150269
Epoch 248/1000: L(Train): 0.5972322821617126; L(Test): 0.5891368389129639
Epoch 249/1000: L(Train): 0.5922665596008301; L(Test): 0.5882017016410828
Epoch 250/1000: L(Train): 0.5913676619529724; L(Test): 0.5901737213134766
Epoch 251/1000: L(Train): 0.593636155128479; L(Test): 0.5863786935806274
Epoch 252/1000: L(Train): 0.5899972915649414; L(Test): 0.5871807336807251
Epoch 253/1000: L(Train): 0.5906993746757507; L(Test): 0.5872925519943237
Epoch 254/1000: L(Train): 0.5905246138572693; L(Test): 0.5856105089187622
Epoch 255/1000: L(Train): 0.5892060399055481; L(Test): 0.5857451558113098
Epoch 256/1000: L(Train): 0.5898464322090149; L(Test): 0.5843369364738464
Epoch 257/1000: L(Train): 0.5885696411132812; L(Test): 0.5838598012924194
Epoch 258/1000: L(Train): 0.5880533456802368; L(Test): 0.5833973288536072
Epoch 259/1000: L(Train): 0.5877389907836914; L(Test): 0.5835202932357788
Epoch 260/1000: L(Train): 0.5867322683334351; L(Test): 0.5830941796302795
Epoch 261/1000: L(Train): 0.5867010354995728; L(Test): 0.5813060998916626
Epoch 262/1000: L(Train): 0.5858789682388306; L(Test): 0.5812183618545532
Epoch 263/1000: L(Train): 0.5859971046447754; L(Test): 0.5804789066314697
Epoch 264/1000: L(Train): 0.5848596096038818; L(Test): 0.5810175538063049
Epoch 265/1000: L(Train): 0.5851941704750061; L(Test): 0.5802176594734192
Epoch 266/1000: L(Train): 0.5838536024093628; L(Test): 0.5785492658615112
Epoch 267/1000: L(Train): 0.5834060311317444; L(Test): 0.5782858729362488
Epoch 268/1000: L(Train): 0.5838916301727295; L(Test): 0.577863335609436
Epoch 269/1000: L(Train): 0.5825394988059998; L(Test): 0.5781236886978149
Epoch 270/1000: L(Train): 0.5827711224555969; L(Test): 0.5771287083625793
Epoch 271/1000: L(Train): 0.5817914009094238; L(Test): 0.5761590003967285
Epoch 272/1000: L(Train): 0.5815452337265015; L(Test): 0.5757061839103699

In [14]:
gru.load_state_dict(torch.load(path_gru, map_location='cpu'))

# ANALYSIS

In [15]:
from weinhardt2026.analysis.analysis_model_evaluation import analysis_model_evaluation
from weinhardt2026.analysis.analysis_coefficients_distributions import analysis_coefficients_distributions
from weinhardt2026.analysis.analysis_coefficients_individuals import analysis_coefficients_individuals
from analysis_generative import analysis_generative_behavior

## General Analysis

In [15]:
# Dataset-specific behavioral analysis placeholder.
# Replace with Eckstein2024-specific columns if needed.

In [16]:
print("Fitted Castro2025 parameters:")
print("\nBeta_r")
print(cfs.beta_r)
print("\nLapse")
print(cfs.lapse)
print("\nPrior")
print(cfs.prior)
print("\nAlpha exploration rate")
print(cfs.alpha_exploration_rate)
print("\nDecay rate")
print(cfs.decay_rate)
print("\nGamma")
print(cfs.gamma)
print("\nTemperature")
print(cfs.temperature)

Fitted Castro2025 parameters:

Beta_r
tensor([2.6588, 2.5872, 2.4406, 2.6166, 1.5054, 2.2513, 2.1100, 2.1039, 1.3746,
        2.0745, 2.6667, 2.1328, 2.3358, 2.6025, 2.1986, 2.1311, 2.8331, 2.4313,
        2.6382, 3.0562, 2.2559, 2.3994, 1.6902, 2.9913, 1.8730, 1.9825, 1.6819,
        2.4229, 2.0172, 2.3439, 1.9366, 2.0212, 2.0829, 2.6930, 2.3627, 2.4913,
        2.2294, 2.5848, 2.2695, 1.6097, 2.0131, 1.8442, 2.4099, 1.7877, 2.4884,
        2.5506, 2.2508, 1.9150, 2.4284, 2.4954, 2.2797, 1.9747, 2.2009, 1.3223,
        1.7321, 1.8294, 1.8130, 2.4777, 2.4677, 2.4375, 1.7650, 2.0791, 2.4099,
        1.9940, 2.5261, 1.7374, 2.3255, 2.0326, 1.4980, 1.6791, 1.8890, 1.9227,
        3.0623, 3.0400, 1.6810, 2.5141, 2.1057, 1.5235, 2.4788, 3.1193, 2.7911,
        2.1080, 2.4988, 1.9093, 1.6636, 2.5500, 1.7713, 2.7464, 1.7287, 2.7249,
        1.5610, 2.2452, 2.2940, 3.5569, 1.9799, 1.0523, 2.3127, 1.8893, 2.3050,
        2.3087, 2.0803, 1.8150, 2.6862, 2.3649, 2.2447, 2.5190, 1.9997, 2.4064,
        2.4447, 2.3609, 1.7170, 2.1955, 2.1770, 2.3069, 2.2260, 2.5431, 0.8847,
        2.3862, 1.9628, 3.4391, 2.2637, 1.6960, 1.1667, 1.7355, 1.7706, 2.1902,
        1.8448, 1.6047, 2.4165, 1.7141, 2.3863, 1.9856, 2.0471, 1.3968, 2.4601,
        2.6521, 1.9654, 2.2241, 2.1597, 2.0548, 3.0676, 2.8083, 1.9479, 2.1918,
        1.6474, 2.3734, 2.2527, 1.8660, 2.5989, 2.3309, 2.3536, 2.4350, 2.3552,
        2.5573, 2.3077, 2.1825, 0.0881, 1.9911, 1.8933, 2.2148, 2.5415, 2.6711,
        2.5021, 1.9923, 2.5377, 2.4992, 2.1587, 1.7106, 1.7535, 2.3871, 2.4583,
        1.9923, 2.1467, 1.9436, 2.0722, 1.6535, 2.4197, 2.1072, 1.9010, 1.9500,
        1.6570, 1.7741, 2.1880, 3.2165, 2.1879, 2.5240, 1.9978, 2.0552, 2.3262,
        2.4441, 1.9256, 3.4779, 2.0870, 1.5188, 2.1706, 1.7093, 2.1554, 3.1323,
        1.3909, 1.4578, 1.8029, 3.6459, 1.9580, 1.9831, 2.1037, 1.5477, 2.4592,
        2.4691, 2.3704, 1.9554, 2.0966, 2.7401, 2.1049, 1.6305, 2.4371, 2.0144,
        2.1371, 1.8398, 2.5891, 2.3590, 2.3281, 2.5752, 2.3602, 1.3897, 1.6603,
        2.2121, 1.8205, 1.9809, 1.8037, 2.4123, 1.9906, 1.7313, 2.5057, 2.3228,
        1.6892, 1.9877, 2.5587, 2.5272, 2.1416, 2.1004, 2.2937, 2.4864, 1.6206,
        2.0160, 2.1433, 1.5590, 2.5892, 2.0270, 2.2582, 2.3297, 1.5219, 2.0718,
        2.0496, 2.2770, 2.3115, 1.7163, 2.5276, 2.5323, 2.2470, 2.1114, 2.1226,
        2.7544, 2.9890, 2.3348, 2.3150, 2.7736, 2.0075, 2.1683, 2.2466, 2.1808,
        2.6216, 2.1047, 1.9318, 1.8605, 2.2074, 2.3420, 2.2530, 2.1159, 1.7806,
        1.0698, 2.8166, 2.3934, 1.9646, 2.5035, 1.7418, 1.6262, 2.2457, 1.8205,
        1.8621, 2.5019, 2.3738, 1.6984, 1.8832, 1.9875, 2.2328, 2.3724, 2.3255,
        3.2937, 2.1647, 2.1386, 1.7565, 2.4120, 2.0245, 2.3069, 2.2281, 3.5578,
        2.4474, 2.3014, 1.8458, 1.7615, 1.7432, 1.5648, 1.7937, 1.7935, 1.8748,
        2.1267, 2.3558, 2.4289, 1.9002, 2.3756, 1.8948, 1.8504, 1.4885, 2.4793,
        1.6593, 2.7902, 2.4367, 1.8445, 1.7390, 1.7623, 1.4249, 1.9569, 2.9371,
        1.2259, 2.6181, 2.3358, 2.0169, 1.8616, 2.1907, 2.7160, 1.7242, 2.4046,
        2.3069, 2.7866, 2.7747, 2.2673, 2.0803, 1.9608, 2.2360, 1.9145, 1.8519,
        2.1858, 2.3495, 1.9953, 3.1567, 2.4007, 1.9998, 1.8499, 2.4094, 1.8400,
        2.5996, 2.0758, 2.5672, 1.6103, 2.0721, 2.2555, 2.3728, 2.4145, 1.5679,
        2.3892, 2.5441, 2.4800, 2.4485, 1.5602, 1.7441, 1.5929, 2.2861, 2.6188,
        2.2154, 1.1790, 1.6573, 1.6782, 2.0371, 1.2747, 1.4378, 2.2679, 1.7175,
        1.7306, 1.9460, 1.9276, 2.1636, 1.3463, 1.6984, 1.4062, 2.6498, 1.7715,
        1.7855, 2.4945, 2.6051, 1.5367, 1.9620, 2.4500, 2.6208, 2.1988, 2.6265,
        1.7609, 2.5442, 1.9348, 2.4627, 1.4628, 2.2467, 1.7298, 5.0067, 1.6047,
        2.1703, 2.2288, 1.6470, 2.1894, 2.5316, 1.7099, 2.0844, 2.1637, 1.7692,
        1.8659, 2.3686, 2.8485, 1.9203, 2.5900, 2.4176, 2.2393, 2.6550, 2.5427,
        1.9037, 2.2104, 2.0986, 1.8077, 2.0100, 2.3647, 2.1117, 1.5113, 1.7359,
        2.6525, 2.1746, 2.2930, 2.0341, 2.0031, 2.5390, 2.0438, 2.2176, 2.0225,
        2.0984, 1.4101, 1.6870, 2.1084, 1.7389, 2.5558, 2.2793, 1.8683, 1.6360,
        1.8380, 2.3185, 1.8006, 1.9293, 1.9000, 2.2150, 2.4304, 2.1794, 1.9279,
        2.3954, 2.1822, 2.3102, 2.7831, 1.5173, 0.3053, 2.1765, 2.3646, 2.8203,
        2.3844, 2.6348, 1.7595, 1.8992, 2.1762, 1.7908, 1.5967, 1.3388, 2.2623,
        2.1235, 2.1284, 1.9103, 2.1673, 1.8181, 1.9151, 1.9011, 2.0810, 2.2154,
        2.4490, 1.9447, 2.2631, 2.3629, 2.4152, 1.7561, 1.7205, 1.7713, 2.8646,
        2.1961, 2.3438, 2.2551, 2.4183, 1.1372, 2.6529, 1.9756, 1.9101, 1.8642,
        2.2100, 2.1578, 2.1360, 2.7176, 2.3542, 2.0001, 1.6657, 2.1288, 2.7056,
        1.9494, 1.6583, 1.9488, 2.1507, 2.1399, 1.9920, 2.9571, 1.9217, 2.2741,
        2.0421, 1.1919, 2.6252, 2.4081, 2.1990, 1.8684, 2.0865, 2.3702, 1.5205,
        2.3507, 1.7779, 1.9801, 2.4461, 1.7947, 2.6250, 2.0373, 1.9600, 1.4073,
        1.8697, 2.0737, 1.6756, 2.2631, 3.0655, 1.8551, 1.6714, 1.7827, 1.9655,
        2.2286, 3.4162, 2.1485, 2.1285, 1.9251, 1.8916, 1.8871, 1.6004, 2.0758,
        2.2822, 1.4352, 2.4490, 2.4498, 2.1887, 1.6829, 2.3262, 2.0447, 2.2999,
        2.4500, 1.7711, 1.8031, 2.2857, 1.7446, 1.7810, 2.1273, 2.1080, 2.2337,
        2.0722, 1.7901, 1.8211, 1.8803, 1.7087, 2.3391, 1.6328, 2.4412, 1.4329,
        2.4950, 1.9271, 2.2496, 2.2197, 2.5989, 1.6766, 2.2131, 1.7674, 2.3381,
        1.8727, 2.3872, 2.5753, 2.9033, 1.6982, 2.4487, 1.9902, 2.0182, 2.1144,
        2.0822, 2.2097, 2.0737, 2.6886, 2.8918, 1.0896, 2.0276, 2.5870, 1.8660,
        2.3791, 2.2490, 2.0431, 2.0215, 2.1728, 1.9623, 2.1118, 1.8853, 1.7444,
        2.1612, 2.0220, 2.1647, 1.8318, 1.6068, 2.4495, 2.5230, 1.5210, 2.3832,
        0.9588, 2.3721, 1.9904, 1.7851, 1.5657, 1.7252, 2.2143, 2.2868, 1.4212,
        2.0948, 2.0789, 1.6782, 1.6281, 1.8681, 2.2648, 1.9708, 2.5159, 2.3228,
        1.3589, 1.7798, 1.8473, 2.0423, 2.1617, 1.9092, 1.6632, 2.5961, 1.9027,
        2.3193, 2.0729, 2.5103, 1.9607, 5.0067, 2.0006, 2.1188, 1.5754, 2.4501,
        1.9965, 2.1041, 2.4876, 2.0114, 2.1369, 1.9424, 2.3280, 1.2980, 2.3428,
        2.3687, 1.8665, 2.1436, 2.1819, 2.4245, 2.5543, 2.3043, 2.6090, 2.4771,
        2.0539, 2.6184, 2.9914, 2.9362, 2.1056, 2.1496, 2.0426, 2.4286, 2.0348,
        1.9737, 2.3636, 2.3240, 1.3411, 2.0859, 2.4060, 1.9178, 1.2508, 3.6076,
        1.5244, 1.8174, 1.7048, 1.6633, 2.0903, 1.8046, 2.0625, 1.9832, 2.0276,
        1.8874, 2.2512, 1.8581, 2.3575, 1.9989, 2.5144, 2.7500, 2.0103, 2.8149,
        1.4090, 1.3034, 2.1390, 2.2225, 2.5992, 2.5428, 1.4357, 2.4962, 2.1333,
        2.1370, 2.4160, 1.8750, 1.8740, 1.8560, 2.6069, 1.4121, 2.7918, 1.9512,
        2.2985, 2.4219, 2.1614, 1.7207, 1.3362, 1.6513, 1.7744, 2.3038, 2.5774,
        1.5598, 2.5333, 1.9755, 2.3296, 2.1978, 1.8436, 1.9043, 1.8393, 1.3844,
        1.6193, 2.4639, 1.9555, 1.8234, 2.5374, 2.6008, 2.4900, 1.4960, 2.3202,
        1.7913, 2.0687, 2.1762, 1.7344, 2.3379, 2.1727, 1.7607, 2.6481, 1.8109,
        2.2753, 1.4614, 2.3795, 1.1661, 1.9560, 1.3814, 1.4276, 2.1198, 2.0955,
        2.2975, 1.9047, 1.7347, 1.7796, 2.3494, 2.0389, 2.6393, 2.6250, 2.4275,
        2.5500, 1.6795, 2.1202, 1.9345, 1.8559, 3.3251, 2.6684, 1.7610, 1.7171,
        2.1899, 1.9979, 1.9443, 2.7789, 2.3453, 1.8262, 1.5297, 2.7911, 2.0401,
        2.4562, 1.9180, 1.9485, 1.7491, 1.9698, 2.3837, 2.0869, 2.0880, 2.2289,
        2.0488, 2.0756, 2.0057, 2.3526, 1.8614, 2.9194, 1.6321, 3.2868, 2.1537,
        2.5307, 1.8265, 2.1985, 2.5992, 2.4153, 1.4442, 2.4227, 1.7905, 2.1149,
        2.4199, 1.7251, 2.6437, 2.3663, 2.3555, 2.6763, 1.7415, 1.9252, 2.3379,
        2.2138, 2.3154, 2.4413, 2.0743, 1.8707, 2.5794, 2.0066],
       grad_fn=<ClampBackward1>)

Lapse
tensor([0.0721, 0.0161, 0.1466, 0.2079, 0.1645, 0.0888, 0.0100, 0.0960, 0.0995,
        0.0440, 0.1953, 0.1470, 0.0329, 0.6257, 0.0105, 0.1810, 0.0203, 0.0755,
        0.0100, 0.2886, 0.0204, 0.0150, 0.1477, 0.0100, 0.0573, 0.0104, 0.0124,
        0.1550, 0.0252, 0.1317, 0.5003, 0.0539, 0.0462, 0.0128, 0.1008, 0.0342,
        0.0159, 0.0240, 0.0966, 0.0139, 0.0506, 0.0134, 0.0571, 0.0370, 0.0100,
        0.0437, 0.0321, 0.0418, 0.2229, 0.0245, 0.0100, 0.0169, 0.0416, 0.0247,
        0.0171, 0.0100, 0.0175, 0.0913, 0.0106, 0.0884, 0.0162, 0.0100, 0.0100,
        0.0965, 0.1031, 0.0892, 0.0344, 0.1384, 0.1950, 0.1789, 0.0667, 0.0269,
        0.0242, 0.3789, 0.0195, 0.0415, 0.0169, 0.0252, 0.1378, 0.2254, 0.0152,
        0.0351, 0.4103, 0.0299, 0.1929, 0.0100, 0.0563, 0.1123, 0.0125, 0.2076,
        0.0824, 0.0545, 0.1047, 0.5218, 0.0455, 0.0263, 0.1975, 0.2365, 0.0109,
        0.0100, 0.4878, 0.1543, 0.0224, 0.0130, 0.1415, 0.1374, 0.0176, 0.2017,
        0.0100, 0.0390, 0.5812, 0.0191, 0.0248, 0.0752, 0.0324, 0.2439, 0.1738,
        0.1527, 0.1992, 0.1518, 0.0206, 0.0147, 0.0294, 0.0212, 0.0133, 0.0862,
        0.0307, 0.0528, 0.1479, 0.1156, 0.0945, 0.0100, 0.0396, 0.1351, 0.0595,
        0.0484, 0.0653, 0.0818, 0.1228, 0.1043, 0.0174, 0.2014, 0.0516, 0.0401,
        0.0293, 0.1052, 0.1485, 0.0347, 0.0650, 0.0121, 0.0100, 0.0977, 0.0432,
        0.1871, 0.0100, 0.0173, 0.0457, 0.1251, 0.0224, 0.2805, 0.0132, 0.1359,
        0.3148, 0.1448, 0.2256, 0.0532, 0.0535, 0.0382, 0.0782, 0.1146, 0.1542,
        0.0325, 0.0986, 0.0318, 0.0163, 0.0100, 0.0534, 0.0872, 0.0258, 0.0129,
        0.0544, 0.0613, 0.0167, 0.4432, 0.0860, 0.0611, 0.0100, 0.0579, 0.0309,
        0.3584, 0.1076, 0.7077, 0.0390, 0.0180, 0.0100, 0.0321, 0.1048, 0.1490,
        0.0992, 0.1019, 0.0100, 0.0100, 0.1299, 0.0186, 0.0328, 0.0327, 0.0245,
        0.0253, 0.0231, 0.0517, 0.0247, 0.1850, 0.0244, 0.0356, 0.3432, 0.0187,
        0.0366, 0.0150, 0.1868, 0.0764, 0.1798, 0.0204, 0.0434, 0.1006, 0.0379,
        0.0505, 0.1729, 0.0100, 0.0676, 0.0122, 0.1040, 0.0340, 0.0105, 0.2831,
        0.0293, 0.1325, 0.0451, 0.0197, 0.0733, 0.0121, 0.1015, 0.1419, 0.0456,
        0.0148, 0.0381, 0.2695, 0.2387, 0.0104, 0.1779, 0.2510, 0.0100, 0.1180,
        0.0550, 0.0162, 0.0147, 0.0100, 0.1319, 0.1528, 0.0198, 0.1574, 0.0554,
        0.0600, 0.2604, 0.1588, 0.0626, 0.0297, 0.0189, 0.0601, 0.0152, 0.0268,
        0.1342, 0.0459, 0.0601, 0.1463, 0.0232, 0.1660, 0.0146, 0.0100, 0.0776,
        0.0182, 0.0100, 0.0100, 0.0218, 0.1178, 0.0939, 0.0719, 0.2216, 0.0100,
        0.0410, 0.1123, 0.0393, 0.1551, 0.1783, 0.0469, 0.1956, 0.0794, 0.0266,
        0.1779, 0.0194, 0.0158, 0.0279, 0.0103, 0.1057, 0.0100, 0.2333, 0.0100,
        0.0139, 0.1176, 0.0466, 0.5326, 0.0130, 0.0131, 0.1517, 0.0100, 0.3011,
        0.0423, 0.0720, 0.0178, 0.0222, 0.0954, 0.0144, 0.0440, 0.2075, 0.0125,
        0.0264, 0.1030, 0.0455, 0.0187, 0.0100, 0.0169, 0.1141, 0.5468, 0.0751,
        0.3134, 0.0797, 0.0448, 0.3027, 0.0108, 0.0122, 0.2969, 0.0372, 0.0836,
        0.0240, 0.0461, 0.0100, 0.0107, 0.1468, 0.2101, 0.2705, 0.0475, 0.0114,
        0.0260, 0.0468, 0.0145, 0.5532, 0.0607, 0.0141, 0.2499, 0.0706, 0.0456,
        0.1295, 0.0152, 0.1434, 0.2127, 0.0332, 0.0385, 0.0506, 0.0100, 0.0262,
        0.0715, 0.0163, 0.0233, 0.0394, 0.0218, 0.0843, 0.0182, 0.0100, 0.0164,
        0.0135, 0.0250, 0.0592, 0.0706, 0.0636, 0.2153, 0.0562, 0.0100, 0.0160,
        0.0878, 0.1150, 0.0463, 0.0100, 0.3334, 0.3598, 0.1129, 0.0980, 0.0609,
        0.0610, 0.2432, 0.0279, 0.0163, 0.0463, 0.0705, 0.0397, 0.0845, 0.1761,
        0.1365, 0.0841, 0.0100, 0.0501, 0.0582, 0.0233, 0.2946, 0.0981, 0.0520,
        0.0871, 0.0907, 0.0391, 0.2522, 0.1287, 0.0146, 0.0423, 0.0526, 0.0347,
        0.1183, 0.2266, 0.0868, 0.0146, 0.0460, 0.0988, 0.0111, 0.0569, 0.0100,
        0.0100, 0.1335, 0.0154, 0.1208, 0.0103, 0.0400, 0.0103, 0.0164, 0.0188,
        0.1474, 0.0118, 0.0143, 0.1024, 0.0124, 0.0266, 0.3805, 0.0635, 0.0654,
        0.0925, 0.0520, 0.0513, 0.0100, 0.0100, 0.8096, 0.0100, 0.0218, 0.0856,
        0.0200, 0.0160, 0.0240, 0.1307, 0.3806, 0.0518, 0.0162, 0.0392, 0.1111,
        0.1399, 0.0138, 0.0429, 0.0520, 0.0255, 0.9588, 0.0100, 0.1188, 0.0163,
        0.0124, 0.0407, 0.1091, 0.0863, 0.2109, 0.0166, 0.0251, 0.2180, 0.0648,
        0.0429, 0.1261, 0.0329, 0.1316, 0.0360, 0.0204, 0.0584, 0.0100, 0.0137,
        0.0257, 0.0191, 0.0429, 0.1735, 0.0984, 0.1610, 0.1694, 0.0374, 0.1543,
        0.0321, 0.2020, 0.0128, 0.0355, 0.1232, 0.2481, 0.0734, 0.0161, 0.2083,
        0.0100, 0.0131, 0.0351, 0.0827, 0.3104, 0.0848, 0.0911, 0.1162, 0.0308,
        0.0574, 0.0204, 0.0276, 0.0612, 0.0244, 0.0311, 0.2266, 0.0948, 0.0108,
        0.0764, 0.0258, 0.0799, 0.0253, 0.1102, 0.0816, 0.0324, 0.0100, 0.0460,
        0.0657, 0.0136, 0.0297, 0.0119, 0.2002, 0.0366, 0.1238, 0.1941, 0.1380,
        0.0738, 0.0426, 0.0191, 0.0184, 0.1870, 0.0349, 0.2678, 0.0794, 0.0674,
        0.0172, 0.0105, 0.1976, 0.0100, 0.0219, 0.0132, 0.0249, 0.0760, 0.0169,
        0.0227, 0.0518, 0.0572, 0.1255, 0.1318, 0.4113, 0.0220, 0.0539, 0.1335,
        0.1225, 0.0100, 0.0634, 0.0743, 0.0100, 0.0122, 0.1412, 0.0412, 0.0696,
        0.1269, 0.0100, 0.0344, 0.0456, 0.0240, 0.0100, 0.1355, 0.1061, 0.4162,
        0.0665, 0.2021, 0.0164, 0.1146, 0.1621, 0.1705, 0.0453, 0.0181, 0.0613,
        0.0377, 0.0812, 0.0100, 0.0111, 0.0158, 0.0509, 0.0176, 0.0315, 0.0833,
        0.0143, 0.2948, 0.0507, 0.4423, 0.0209, 0.0426, 0.0672, 0.0580, 0.0584,
        0.0100, 0.1818, 0.0203, 0.0135, 0.0102, 0.0778, 0.0315, 0.0322, 0.1751,
        0.2885, 0.0410, 0.0346, 0.0625, 0.0170, 0.0135, 0.2408, 0.0258, 0.0901,
        0.0262, 0.0898, 0.0281, 0.0155, 0.0146, 0.0247, 0.0100, 0.0270, 0.0164,
        0.0307, 0.0185, 0.1770, 0.0111, 0.4074, 0.0284, 0.0209, 0.0653, 0.1725,
        0.1649, 0.0902, 0.0154, 0.0176, 0.1515, 0.0172, 0.0100, 0.3749, 0.1568,
        0.0597, 0.0776, 0.0415, 0.1820, 0.4753, 0.1147, 0.0967, 0.0396, 0.1446,
        0.0891, 0.0100, 0.0227, 0.0572, 0.0313, 0.0256, 0.0271, 0.0820, 0.0986,
        0.0407, 0.0330, 0.0105, 0.0548, 0.0400, 0.0132, 0.1391, 0.0759, 0.1555,
        0.1430, 0.1035, 0.1222, 0.0345, 0.0466, 0.0180, 0.0343, 0.1104, 0.0233,
        0.1653, 0.1201, 0.0166, 0.0626, 0.2796, 0.0658, 0.1307, 0.0366, 0.0274,
        0.0731, 0.0281, 0.0313, 0.0162, 0.0158, 0.0935, 0.0307, 0.0138, 0.1316,
        0.0471, 0.1652, 0.1419, 0.1021, 0.0139, 0.2497, 0.0150, 0.0431, 0.0427,
        0.1533, 0.0299, 0.1133, 0.0791, 0.1256, 0.1038, 0.0125, 0.1336, 0.0886,
        0.0916, 0.1192, 0.0100, 0.0549, 0.0173, 0.0324, 0.0736, 0.5298, 0.0101,
        0.0843, 0.0178, 0.0443, 0.0104, 0.1587, 0.0391, 0.1042, 0.0127, 0.1289,
        0.3548, 0.1177, 0.0380, 0.3034, 0.0818, 0.0527, 0.0245, 0.0197, 0.0734,
        0.0216, 0.0506, 0.1905, 0.0248, 0.1432, 0.1080, 0.1532, 0.0417, 0.2448,
        0.0458, 0.1649, 0.1444, 0.0753, 0.4144, 0.0292, 0.0132, 0.1661, 0.0100,
        0.3556, 0.0545, 0.1321, 0.0988, 0.0100, 0.1094, 0.0335, 0.2180, 0.1239,
        0.1871, 0.0136, 0.1322, 0.0432, 0.0903, 0.1761, 0.0265, 0.0626, 0.0105,
        0.0205, 0.1345, 0.0213, 0.0361, 0.0100, 0.3595, 0.1289, 0.0298, 0.5343,
        0.0111, 0.2179, 0.0100, 0.7815, 0.0651, 0.0175, 0.1822, 0.6872, 0.1101,
        0.0888, 0.0100, 0.0773, 0.1825, 0.0309, 0.1249, 0.1330, 0.0585, 0.0858,
        0.0228, 0.2424, 0.0676, 0.0172, 0.0723, 0.5615, 0.0245, 0.5415, 0.1001,
        0.0489, 0.0560, 0.1883, 0.1039, 0.0488, 0.0180, 0.0171, 0.0721, 0.1176,
        0.0396, 0.0213, 0.0514, 0.1406, 0.1049, 0.0331, 0.3557, 0.1117, 0.0623,
        0.1480, 0.0221, 0.0109, 0.0168, 0.0901, 0.3132, 0.0263],
       grad_fn=<ClampBackward1>)

Prior
tensor([0.9900, 0.9900, 0.9900, 0.9900, 0.4500, 0.6202, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.5354, 0.9900, 0.0449, 0.1347, 0.9900, 0.9900,
        0.3216, 0.9900, 0.9900, 0.9900, 0.9900, 0.1397, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.2730, 0.9900, 0.9900, 0.1064, 0.9900,
        0.9900, 0.9900, 0.0672, 0.9900, 0.9900, 0.9900, 0.2624, 0.9900, 0.7255,
        0.9900, 0.5883, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.1937, 0.9900, 0.9900, 0.3982,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0340, 0.0254, 0.9900,
        0.7093, 0.9900, 0.9900, 0.1919, 0.3916, 0.9900, 0.4162, 0.9900, 0.9900,
        0.9900, 0.9013, 0.9900, 0.1181, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0380, 0.9900, 0.5880, 0.6868, 0.6779, 0.2973,
        0.9900, 0.9900, 0.0133, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0100,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0871, 0.9900,
        0.9900, 0.0100, 0.9900, 0.3766, 0.9900, 0.9900, 0.9900, 0.9900, 0.3151,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.1145, 0.9900, 0.9900,
        0.9900, 0.9900, 0.0216, 0.9900, 0.4187, 0.5771, 0.9900, 0.7035, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.0169, 0.0986, 0.9900, 0.0537, 0.0586,
        0.9900, 0.0653, 0.9900, 0.2551, 0.9900, 0.9900, 0.0899, 0.9900, 0.9900,
        0.0203, 0.9900, 0.9900, 0.6860, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.1724, 0.5043, 0.0791, 0.9900, 0.9900, 0.9900, 0.9900, 0.3149, 0.9900,
        0.0368, 0.4994, 0.9900, 0.2571, 0.9900, 0.9900, 0.9900, 0.0100, 0.9900,
        0.9900, 0.9900, 0.7878, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.3841,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.6178, 0.0100, 0.9900, 0.5940, 0.9900, 0.0228, 0.9900, 0.4048, 0.8869,
        0.9900, 0.9900, 0.3579, 0.9900, 0.9900, 0.5093, 0.2237, 0.8333, 0.9900,
        0.0894, 0.9900, 0.9900, 0.9900, 0.2388, 0.9900, 0.9900, 0.9900, 0.0721,
        0.9900, 0.1799, 0.9900, 0.9900, 0.9900, 0.3822, 0.2113, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.0100, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.0346, 0.9900, 0.5538, 0.9900, 0.3795, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0168, 0.9900, 0.6176, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0164, 0.9590, 0.0100, 0.9900, 0.9900, 0.9900,
        0.2242, 0.9900, 0.9900, 0.9900, 0.9900, 0.0714, 0.9900, 0.9900, 0.4735,
        0.5038, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.0242, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.5518, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.8445, 0.9900,
        0.9900, 0.4405, 0.9900, 0.4907, 0.9900, 0.9900, 0.9900, 0.0171, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0138, 0.9900, 0.9900, 0.0100, 0.9900, 0.0117,
        0.9900, 0.5208, 0.7135, 0.9900, 0.9900, 0.7100, 0.9900, 0.0163, 0.5073,
        0.9900, 0.3346, 0.0125, 0.0100, 0.9900, 0.4375, 0.0126, 0.9900, 0.9900,
        0.9900, 0.9900, 0.5078, 0.9900, 0.2666, 0.9900, 0.3341, 0.9900, 0.4558,
        0.6080, 0.1483, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.4817,
        0.2539, 0.0435, 0.2969, 0.9900, 0.9900, 0.1643, 0.9900, 0.9900, 0.0538,
        0.4560, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0625,
        0.9900, 0.9900, 0.4781, 0.9900, 0.9900, 0.9900, 0.4627, 0.3230, 0.9900,
        0.9900, 0.9900, 0.9900, 0.4586, 0.9900, 0.9900, 0.9900, 0.1896, 0.9900,
        0.2041, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.4204, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0870, 0.0100, 0.9900, 0.9900,
        0.9900, 0.5526, 0.9900, 0.9900, 0.9900, 0.2328, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0742, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.4007, 0.5753, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.3210, 0.9900, 0.9900, 0.9900,
        0.9900, 0.4737, 0.2095, 0.4315, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.3205, 0.9900, 0.0100, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.6675, 0.9900, 0.9900, 0.9900, 0.0100, 0.9900, 0.9900,

## Analysis Model Evaluation

In [21]:
analysis_model_evaluation(
    dataset=dataset_train,
    spice_model=estimator,
    benchmark_model=cfs.to(torch.device('cpu')),
    gru_model=gru.eval().to(torch.device('cpu')),
    )

Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...
Computing choice probabilities with SPICE model...

,Trial Lik.,(std),n_parameters,(std),NLL,AIC,BIC
Benchmark,0.656590,0.159280,13.000000,0.000000,7890.157227,15806.314453,15908.224609
GRU,0.658189,0.152148,6852.000000,0.000000,7844.539062,29393.078125,83107.382812
SPICE-RNN,0.615619,0.158915,10614.000000,0.000000,9098.567383,39425.132812,122630.562500
SPICE,0.614896,0.158621,54.720001,0.448509,9120.589844,18350.626953,18779.615234

In [22]:
analysis_model_evaluation(
    dataset=dataset_test,
    spice_model=estimator,
    benchmark_model=cfs.to(torch.device('cpu')),
    gru_model=gru.eval().to(torch.device('cpu')),
    )

Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...
Computing choice probabilities with SPICE model...

,Trial Lik.,(std),n_parameters,(std),NLL,AIC,BIC
Benchmark,0.638818,0.176031,13.000000,0.000000,3323.375977,6672.751953,6762.600098
GRU,0.653981,0.164939,6852.000000,0.000000,3149.399658,20002.798828,67359.679688
SPICE-RNN,0.607736,0.175655,10614.000000,0.000000,3693.276367,28614.552734,101972.101562
SPICE,0.606805,0.175069,54.720001,0.453557,3704.651611,7518.743164,7896.934570

## Analysis coefficient distributions

In [ ]:
analysis_coefficients_distributions(
    spice_model=estimator,
    output_dir='results',
)

## Analysis Individual Differences

In [ ]:
# analysis_coefficients_individuals(
#     criterion="SomeCriterionColumnInYourDataset",
#     analysis="disc",  # also: "cont"
#     reference="ReferenceGroupFromCriterionColumn",  # only necessary if analysis="disc"
    
#     path_data=path_file,
    
#     spice_model=estimator,
    
#     dir_output='results',
# )

## Generative Behavior Analysis

In [ ]:
estimator.eval()
generate_behavior(
    model=estimator,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_spice.csv'
)

estimator.use_sindy(False)
generate_behavior(
    model=estimator,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_spice_rnn.csv'
)

gru.eval()
generate_behavior(
    model=gru,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_gru.csv'
)

generate_behavior(
    model=cfs,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_cfs.csv'
)

In [ ]:
analysis_generative_behavior(
    path_data_real=path_data,
    path_data_gru='data/eckstein2024_gru.csv',
    path_data_benchmark='data/eckstein2024_cfs.csv',
    path_data_spice='data/eckstein2024_spice.csv',
    path_data_spice_rnn='data/eckstein2024_spice_rnn.csv',
    output_dir='results',
)