In [ ]:
#!git clone https://github.com/whyhardt/SPICE.git

In [ ]:
# !pip install -e SPICE

In [1]:
import sys

import torch

from spice import SpiceEstimator

sys.path.append("../../..")
from weinhardt2026.utils.benchmarking_gru import GRUModel, training
from weinhardt2026.studies.castro2025.benchmarking_castro2025 import Castro2025Model, get_dataset, generate_behavior
import spice_castro2025, weinhardt2026.studies.castro2025.spice_castro2025 as spice_castro2025

# NOTEBOOK CONFIG

In [21]:
train_spice = False
train_cfs = True
train_gru = False

## Load dataset

In [3]:
path_data = 'data/eckstein2024.csv'
test_sessions = (2,)  # pick sessions that exist for all participants; adjust if needed
dataset_train, dataset_test, info_dataset = get_dataset(path_data=path_data, test_sessions=test_sessions, verbose=True)

Shape of dataset: torch.Size([4158, 150, 1, 13])
Number of participants: 862
Number of actions in dataset: 4

In [4]:
# from spice import SpiceDataset

# # keep only 100 timesteps
# dataset_train = SpiceDataset(dataset_train.xs[:, :100], dataset_train.ys[:, :100])

# # keep only 100 participants for rapid prototyping
# keep_participants = torch.arange(0, 50)

# def keep_subset(dataset, subset):
#     participant_ids = dataset.xs[:, 0, 0, -1]
#     mask = torch.isin(participant_ids, subset)
#     return SpiceDataset(dataset.xs[mask], dataset.ys[mask])

# dataset_train = keep_subset(dataset_train, keep_participants)
# dataset_test = keep_subset(dataset_test, keep_participants)

## SPICE Setup

## SPICE Training

Let's setup now the `SpiceEstimator` object and fit it to the data! 

We are going to do this in two steps:

1. Without fitting the SINDy coefficients to get the pure RNN performance given the selected architecture. 
2. With fitting SINDy coefficients to get the final performance of the interpretable model

That way we can disentangle the gap between GRU and SPICE w.r.t. architecture and SINDy library

In [5]:
path_spice = 'params/spice_castro2025_62_stage1.pkl'

estimator = SpiceEstimator(
        # model paramaeters
        spice_class=spice_castro2025.SpiceModel,
        spice_config=spice_castro2025.CONFIG,
        n_actions=dataset_train.n_actions,
        n_participants=dataset_train.n_participants,
        
        epochs=1000,
        warmup_steps=250,

        verbose=True,
        # device = torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
        save_path_spice=path_spice,
    )

In [6]:
if train_spice:
    estimator.fit(dataset_train.xs, dataset_train.ys, dataset_test.xs, dataset_test.ys)

In [7]:
estimator.load_spice(path_spice)
# estimator.aggregate_coefficients()

In [8]:
# Print example SPICE model for first participant
print("\nExample SPICE model (participant 0):")
estimator.print_spice_model(participant_id=0)

Example SPICE model (participant 0):
value_reward_env[t+1]             = -0.009 1 + 0.964 value_reward_env[t] + 0.023 reward[t]
value_reward_chosen[t+1]          = -0.432 1 + 0.922 value_reward_chosen[t] + -0.052 reward_env + 0.621 reward[t] + -0.095 value_reward_chosen*reward[t] + 0.012 reward_env^2 + 0.029 reward_env*reward[t] + 0.879 reward[t]^2
value_reward_not_chosen[t+1]      = -0.044 1 + 0.808 value_reward_not_chosen[t] + 0.034 reward_env + 0.009 value_reward_mean
value_choice_chosen[t+1]          = -0.356 1 + 0.432 value_choice_chosen[t] + 0.244 action[t-1] + 0.022 value_choice_chosen^2 + 0.054 value_choice_chosen*action[t-1] + 0.244 action[t-1]^2
value_choice_not_chosen[t+1]      = 0.053 1 + 0.825 value_choice_not_chosen[t] + -0.585 action[t-1] + -0.067 value_choice_not_chosen^2 + -0.745 value_choice_not_chosen*action[t-1] + -0.586 action[t-1]^2
value_exploration_chosen[t+1]     = -0.786 1 + 0.448 value_exploration_chosen[t] + 2.363 dvalue_pos + -2.634 dvalue_neg + -0.114 value_exploration_chosen*dvalue_pos + 0.284 value_exploration_chosen*dvalue_neg + 0.459 dvalue_pos^2
value_exploration_not_chosen[t+1] = 0.048 1 + 0.904 value_exploration_not_chosen[t] + 0.063 dvalue_neg

## Benchmarking

### Castro2025 benchmark model

In [22]:
path_spice = 'params/spice_castro2025.pkl'

# Benchmark model: Castro et al. 2025
cfs = Castro2025Model(
    n_participants=dataset_train.n_participants,
    n_actions=dataset_train.n_actions,
    batch_first=True,
    )

path_cfs = path_spice.replace('spice_', 'cfs_')

In [23]:
if train_cfs:
    optimizer_cfs = torch.optim.Adam(params=cfs.parameters(), lr=0.01)
    epochs = 1000

    cfs = training(
        model=cfs,
        optimizer=optimizer_cfs,
        dataset_train=dataset_train,
        dataset_test=dataset_test,
        epochs=epochs,
        loss_kwargs={'label_smoothing': 0.0},
    )

    torch.save(cfs.state_dict(), path_cfs)

Epoch 1/1000: L(Train): 0.6391032338142395; L(Test): 0.6491584181785583
Epoch 2/1000: L(Train): 0.6380892992019653; L(Test): 0.648391842842102
Epoch 3/1000: L(Train): 0.6371073722839355; L(Test): 0.6476544141769409
Epoch 4/1000: L(Train): 0.6361557841300964; L(Test): 0.6469435095787048
Epoch 5/1000: L(Train): 0.6352332830429077; L(Test): 0.6462575793266296
Epoch 6/1000: L(Train): 0.6343384981155396; L(Test): 0.645593523979187
Epoch 7/1000: L(Train): 0.6334707736968994; L(Test): 0.6449497938156128
Epoch 8/1000: L(Train): 0.6326279640197754; L(Test): 0.6443249583244324
Epoch 9/1000: L(Train): 0.6318095922470093; L(Test): 0.6437169313430786
Epoch 10/1000: L(Train): 0.6310133934020996; L(Test): 0.6431248188018799
Epoch 11/1000: L(Train): 0.6302382349967957; L(Test): 0.6425477862358093
Epoch 12/1000: L(Train): 0.6294822096824646; L(Test): 0.6419848799705505
Epoch 13/1000: L(Train): 0.6287450194358826; L(Test): 0.6414342522621155
Epoch 14/1000: L(Train): 0.6280249953269958; L(Test): 0.6408954858779907
Epoch 15/1000: L(Train): 0.6273211240768433; L(Test): 0.640367329120636
Epoch 16/1000: L(Train): 0.6266325116157532; L(Test): 0.6398482322692871
Epoch 17/1000: L(Train): 0.6259574890136719; L(Test): 0.639337420463562
Epoch 18/1000: L(Train): 0.6252956986427307; L(Test): 0.6388339996337891
Epoch 19/1000: L(Train): 0.624645471572876; L(Test): 0.6383368372917175
Epoch 20/1000: L(Train): 0.6240073442459106; L(Test): 0.6378454566001892
Epoch 21/1000: L(Train): 0.623379647731781; L(Test): 0.6373599767684937
Epoch 22/1000: L(Train): 0.6227608323097229; L(Test): 0.6368788480758667
Epoch 23/1000: L(Train): 0.6221513152122498; L(Test): 0.6364028453826904
Epoch 24/1000: L(Train): 0.6215496063232422; L(Test): 0.6359306573867798
Epoch 25/1000: L(Train): 0.6209554672241211; L(Test): 0.6354624629020691
Epoch 26/1000: L(Train): 0.6203673481941223; L(Test): 0.6349973678588867
Epoch 27/1000: L(Train): 0.6197853088378906; L(Test): 0.6345348358154297
Epoch 28/1000: L(Train): 0.6192083358764648; L(Test): 0.634074330329895
Epoch 29/1000: L(Train): 0.6186361908912659; L(Test): 0.6336156129837036
Epoch 30/1000: L(Train): 0.6180676817893982; L(Test): 0.6331577897071838
Epoch 31/1000: L(Train): 0.6175031065940857; L(Test): 0.6326996684074402
Epoch 32/1000: L(Train): 0.6169406175613403; L(Test): 0.6322420239448547
Epoch 33/1000: L(Train): 0.6163803935050964; L(Test): 0.631783664226532
Epoch 34/1000: L(Train): 0.615821361541748; L(Test): 0.631324291229248
Epoch 35/1000: L(Train): 0.615263819694519; L(Test): 0.6308631896972656
Epoch 36/1000: L(Train): 0.6147065162658691; L(Test): 0.6303998231887817
Epoch 37/1000: L(Train): 0.6141484975814819; L(Test): 0.6299337148666382
Epoch 38/1000: L(Train): 0.6135894060134888; L(Test): 0.6294643878936768
Epoch 39/1000: L(Train): 0.6130295395851135; L(Test): 0.6289911866188049
Epoch 40/1000: L(Train): 0.6124674081802368; L(Test): 0.6285134553909302
Epoch 41/1000: L(Train): 0.6119029521942139; L(Test): 0.6280309557914734
Epoch 42/1000: L(Train): 0.6113353967666626; L(Test): 0.627543032169342
Epoch 43/1000: L(Train): 0.6107630729675293; L(Test): 0.6270490884780884
Epoch 44/1000: L(Train): 0.610187828540802; L(Test): 0.626549243927002
Epoch 45/1000: L(Train): 0.609607458114624; L(Test): 0.6260427832603455
Epoch 46/1000: L(Train): 0.6090212464332581; L(Test): 0.6255285143852234
Epoch 47/1000: L(Train): 0.6084288358688354; L(Test): 0.6250070929527283
Epoch 48/1000: L(Train): 0.6078305244445801; L(Test): 0.6244803667068481
Epoch 49/1000: L(Train): 0.60722815990448; L(Test): 0.6239466667175293
Epoch 50/1000: L(Train): 0.6066203117370605; L(Test): 0.6234045028686523
Epoch 51/1000: L(Train): 0.6060054898262024; L(Test): 0.62285315990448
Epoch 52/1000: L(Train): 0.6053819060325623; L(Test): 0.6222922205924988
Epoch 53/1000: L(Train): 0.6047486066818237; L(Test): 0.6217208504676819
Epoch 54/1000: L(Train): 0.604106605052948; L(Test): 0.6211385726928711
Epoch 55/1000: L(Train): 0.6034542918205261; L(Test): 0.6205447912216187
Epoch 56/1000: L(Train): 0.6027909517288208; L(Test): 0.6199391484260559
Epoch 57/1000: L(Train): 0.6021161675453186; L(Test): 0.6193204522132874
Epoch 58/1000: L(Train): 0.601429283618927; L(Test): 0.6186891198158264
Epoch 59/1000: L(Train): 0.6007305383682251; L(Test): 0.6180440783500671
Epoch 60/1000: L(Train): 0.6000186204910278; L(Test): 0.6173845529556274
Epoch 61/1000: L(Train): 0.5992931127548218; L(Test): 0.6167103052139282
Epoch 62/1000: L(Train): 0.5985528230667114; L(Test): 0.6160210371017456
Epoch 63/1000: L(Train): 0.5977981090545654; L(Test): 0.6153157949447632
Epoch 64/1000: L(Train): 0.5970281958580017; L(Test): 0.6145942807197571
Epoch 65/1000: L(Train): 0.5962424874305725; L(Test): 0.6138564944267273
Epoch 66/1000: L(Train): 0.5954399704933167; L(Test): 0.6131014227867126
Epoch 67/1000: L(Train): 0.5946210622787476; L(Test): 0.6123286485671997
Epoch 68/1000: L(Train): 0.5937852263450623; L(Test): 0.6115383505821228
Epoch 69/1000: L(Train): 0.5929315686225891; L(Test): 0.6107292771339417
Epoch 70/1000: L(Train): 0.5920588970184326; L(Test): 0.6099013686180115
Epoch 71/1000: L(Train): 0.5911687612533569; L(Test): 0.6090546250343323
Epoch 72/1000: L(Train): 0.5902590155601501; L(Test): 0.6081885099411011
Epoch 73/1000: L(Train): 0.5893300771713257; L(Test): 0.6073022484779358
Epoch 74/1000: L(Train): 0.5883809924125671; L(Test): 0.6063963174819946
Epoch 75/1000: L(Train): 0.5874122977256775; L(Test): 0.605470597743988
Epoch 76/1000: L(Train): 0.5864239931106567; L(Test): 0.6045242547988892
Epoch 77/1000: L(Train): 0.5854150652885437; L(Test): 0.6035580635070801
Epoch 78/1000: L(Train): 0.5843852162361145; L(Test): 0.6025711894035339
Epoch 79/1000: L(Train): 0.583334743976593; L(Test): 0.6015644669532776
Epoch 80/1000: L(Train): 0.5822634100914001; L(Test): 0.6005375385284424
Epoch 81/1000: L(Train): 0.5811711549758911; L(Test): 0.5994908213615417
Epoch 82/1000: L(Train): 0.5800591111183167; L(Test): 0.5984243154525757
Epoch 83/1000: L(Train): 0.5789263248443604; L(Test): 0.5973385572433472
Epoch 84/1000: L(Train): 0.5777729749679565; L(Test): 0.5962333083152771
Epoch 85/1000: L(Train): 0.5766002535820007; L(Test): 0.5951098799705505
Epoch 86/1000: L(Train): 0.5754074454307556; L(Test): 0.593968391418457
Epoch 87/1000: L(Train): 0.5741957426071167; L(Test): 0.5928098559379578
Epoch 88/1000: L(Train): 0.5729652643203735; L(Test): 0.5916343331336975
Epoch 89/1000: L(Train): 0.5717166066169739; L(Test): 0.5904431343078613
Epoch 90/1000: L(Train): 0.5704506039619446; L(Test): 0.5892370939254761
Epoch 91/1000: L(Train): 0.5691675543785095; L(Test): 0.5880177021026611
Epoch 92/1000: L(Train): 0.5678693056106567; L(Test): 0.586784839630127
Epoch 93/1000: L(Train): 0.5665553212165833; L(Test): 0.5855407118797302
Epoch 94/1000: L(Train): 0.565228283405304; L(Test): 0.5842865109443665
Epoch 95/1000: L(Train): 0.5638877153396606; L(Test): 0.5830227136611938
Epoch 96/1000: L(Train): 0.5625360012054443; L(Test): 0.581751823425293
Epoch 97/1000: L(Train): 0.5611732602119446; L(Test): 0.5804747939109802
Epoch 98/1000: L(Train): 0.5598016381263733; L(Test): 0.5791931748390198
Epoch 99/1000: L(Train): 0.5584223866462708; L(Test): 0.5779086947441101
Epoch 100/1000: L(Train): 0.5570363402366638; L(Test): 0.5766229033470154
Epoch 101/1000: L(Train): 0.5556451678276062; L(Test): 0.5753376483917236
Epoch 102/1000: L(Train): 0.5542512536048889; L(Test): 0.5740545392036438
Epoch 103/1000: L(Train): 0.5528547763824463; L(Test): 0.5727751851081848
Epoch 104/1000: L(Train): 0.5514577031135559; L(Test): 0.5715015530586243
Epoch 105/1000: L(Train): 0.5500621795654297; L(Test): 0.5702353715896606
Epoch 106/1000: L(Train): 0.5486695170402527; L(Test): 0.5689780712127686
Epoch 107/1000: L(Train): 0.5472809076309204; L(Test): 0.567731499671936
Epoch 108/1000: L(Train): 0.5458984971046448; L(Test): 0.5664972066879272
Epoch 109/1000: L(Train): 0.5445232391357422; L(Test): 0.5652772188186646
Epoch 110/1000: L(Train): 0.5431572198867798; L(Test): 0.5640723705291748
Epoch 111/1000: L(Train): 0.5418016314506531; L(Test): 0.5628842711448669
Epoch 112/1000: L(Train): 0.5404579639434814; L(Test): 0.561714768409729
Epoch 113/1000: L(Train): 0.5391271710395813; L(Test): 0.5605644583702087
Epoch 114/1000: L(Train): 0.5378113389015198; L(Test): 0.559434711933136
Epoch 115/1000: L(Train): 0.5365113019943237; L(Test): 0.5583263635635376
Epoch 116/1000: L(Train): 0.5352277159690857; L(Test): 0.5572406649589539
Epoch 117/1000: L(Train): 0.5339623093605042; L(Test): 0.5561780333518982
Epoch 118/1000: L(Train): 0.5327154397964478; L(Test): 0.5551388263702393
Epoch 119/1000: L(Train): 0.5314885973930359; L(Test): 0.5541239976882935
Epoch 120/1000: L(Train): 0.5302824974060059; L(Test): 0.5531333684921265
Epoch 121/1000: L(Train): 0.5290968418121338; L(Test): 0.5521677732467651
Epoch 122/1000: L(Train): 0.527933657169342; L(Test): 0.551226794719696
Epoch 123/1000: L(Train): 0.5267922282218933; L(Test): 0.5503102540969849
Epoch 124/1000: L(Train): 0.5256733894348145; L(Test): 0.5494184494018555
Epoch 125/1000: L(Train): 0.5245779156684875; L(Test): 0.5485504865646362
Epoch 126/1000: L(Train): 0.5235048532485962; L(Test): 0.5477064847946167
Epoch 127/1000: L(Train): 0.5224555730819702; L(Test): 0.5468856692314148
Epoch 128/1000: L(Train): 0.5214290022850037; L(Test): 0.5460876822471619
Epoch 129/1000: L(Train): 0.5204259753227234; L(Test): 0.5453115701675415
Epoch 130/1000: L(Train): 0.5194458961486816; L(Test): 0.5445572733879089
Epoch 131/1000: L(Train): 0.5184889435768127; L(Test): 0.5438235402107239
Epoch 132/1000: L(Train): 0.5175545811653137; L(Test): 0.543110191822052
Epoch 133/1000: L(Train): 0.5166428685188293; L(Test): 0.5424159169197083
Epoch 134/1000: L(Train): 0.5157535076141357; L(Test): 0.5417404770851135
Epoch 135/1000: L(Train): 0.5148858428001404; L(Test): 0.5410832762718201
Epoch 136/1000: L(Train): 0.5140398740768433; L(Test): 0.5404432415962219
Epoch 137/1000: L(Train): 0.5132147073745728; L(Test): 0.5398200154304504
Epoch 138/1000: L(Train): 0.5124109387397766; L(Test): 0.5392128825187683
Epoch 139/1000: L(Train): 0.5116270780563354; L(Test): 0.5386212468147278
Epoch 140/1000: L(Train): 0.5108637809753418; L(Test): 0.5380446314811707
Epoch 141/1000: L(Train): 0.5101198554039001; L(Test): 0.5374822616577148
Epoch 142/1000: L(Train): 0.5093950629234314; L(Test): 0.5369338989257812
Epoch 143/1000: L(Train): 0.5086888074874878; L(Test): 0.5363988280296326
Epoch 144/1000: L(Train): 0.5080012679100037; L(Test): 0.5358771085739136
Epoch 145/1000: L(Train): 0.507331371307373; L(Test): 0.535367488861084
Epoch 146/1000: L(Train): 0.5066790580749512; L(Test): 0.5348703861236572
Epoch 147/1000: L(Train): 0.5060432553291321; L(Test): 0.5343851447105408
Epoch 148/1000: L(Train): 0.5054248571395874; L(Test): 0.5339110493659973
Epoch 149/1000: L(Train): 0.5048220753669739; L(Test): 0.5334482789039612
Epoch 150/1000: L(Train): 0.5042352080345154; L(Test): 0.5329959988594055
Epoch 151/1000: L(Train): 0.503664493560791; L(Test): 0.5325545072555542
Epoch 152/1000: L(Train): 0.503108024597168; L(Test): 0.5321235060691833
Epoch 153/1000: L(Train): 0.502566933631897; L(Test): 0.5317020416259766
Epoch 154/1000: L(Train): 0.5020393133163452; L(Test): 0.5312906503677368
Epoch 155/1000: L(Train): 0.5015256404876709; L(Test): 0.5308889746665955
Epoch 156/1000: L(Train): 0.5010259747505188; L(Test): 0.5304965376853943
Epoch 157/1000: L(Train): 0.5005397200584412; L(Test): 0.5301135778427124
Epoch 158/1000: L(Train): 0.5000659227371216; L(Test): 0.5297397375106812
Epoch 159/1000: L(Train): 0.4996042251586914; L(Test): 0.5293739438056946
Epoch 160/1000: L(Train): 0.4991556406021118; L(Test): 0.529017448425293
Epoch 161/1000: L(Train): 0.4987180233001709; L(Test): 0.5286692976951599
Epoch 162/1000: L(Train): 0.49829235672950745; L(Test): 0.5283294916152954
Epoch 163/1000: L(Train): 0.49787822365760803; L(Test): 0.5279977321624756
Epoch 164/1000: L(Train): 0.4974745213985443; L(Test): 0.5276735424995422
Epoch 165/1000: L(Train): 0.4970816671848297; L(Test): 0.5273574590682983
Epoch 166/1000: L(Train): 0.4966989755630493; L(Test): 0.5270485877990723
Epoch 167/1000: L(Train): 0.49632593989372253; L(Test): 0.5267469882965088
Epoch 168/1000: L(Train): 0.49596333503723145; L(Test): 0.5264526009559631
Epoch 169/1000: L(Train): 0.4956095218658447; L(Test): 0.5261649489402771
Epoch 170/1000: L(Train): 0.49526524543762207; L(Test): 0.5258839726448059
Epoch 171/1000: L(Train): 0.49493029713630676; L(Test): 0.5256096720695496
Epoch 172/1000: L(Train): 0.49460357427597046; L(Test): 0.5253418684005737
Epoch 173/1000: L(Train): 0.4942849576473236; L(Test): 0.5250798463821411
Epoch 174/1000: L(Train): 0.493974506855011; L(Test): 0.5248240828514099
Epoch 175/1000: L(Train): 0.49367278814315796; L(Test): 0.5245740413665771
Epoch 176/1000: L(Train): 0.49337807297706604; L(Test): 0.5243300795555115
Epoch 177/1000: L(Train): 0.49309080839157104; L(Test): 0.5240916609764099
Epoch 178/1000: L(Train): 0.4928111732006073; L(Test): 0.5238586068153381
Epoch 179/1000: L(Train): 0.49253806471824646; L(Test): 0.5236307382583618
Epoch 180/1000: L(Train): 0.49227219820022583; L(Test): 0.5234083533287048
Epoch 181/1000: L(Train): 0.4920129179954529; L(Test): 0.5231910943984985
Epoch 182/1000: L(Train): 0.4917601943016052; L(Test): 0.5229787826538086
Epoch 183/1000: L(Train): 0.4915134310722351; L(Test): 0.5227712988853455
Epoch 184/1000: L(Train): 0.49127286672592163; L(Test): 0.5225687623023987
Epoch 185/1000: L(Train): 0.49103841185569763; L(Test): 0.5223709344863892
Epoch 186/1000: L(Train): 0.4908093810081482; L(Test): 0.5221776366233826
Epoch 187/1000: L(Train): 0.4905860424041748; L(Test): 0.5219889879226685
Epoch 188/1000: L(Train): 0.4903682470321655; L(Test): 0.5218048691749573
Epoch 189/1000: L(Train): 0.49015575647354126; L(Test): 0.5216251611709595
Epoch 190/1000: L(Train): 0.48994821310043335; L(Test): 0.521449863910675
Epoch 191/1000: L(Train): 0.4897458553314209; L(Test): 0.5212785601615906
Epoch 192/1000: L(Train): 0.4895479381084442; L(Test): 0.521111786365509
Epoch 193/1000: L(Train): 0.4893549084663391; L(Test): 0.5209488868713379
Epoch 194/1000: L(Train): 0.4891664385795593; L(Test): 0.5207898020744324
Epoch 195/1000: L(Train): 0.48898234963417053; L(Test): 0.5206344723701477
Epoch 196/1000: L(Train): 0.48880207538604736; L(Test): 0.5204828977584839
Epoch 197/1000: L(Train): 0.48862677812576294; L(Test): 0.5203351378440857
Epoch 198/1000: L(Train): 0.4884549081325531; L(Test): 0.5201908349990845
Epoch 199/1000: L(Train): 0.4882870018482208; L(Test): 0.5200501680374146
Epoch 200/1000: L(Train): 0.4881230592727661; L(Test): 0.5199125409126282
Epoch 201/1000: L(Train): 0.4879627227783203; L(Test): 0.519778311252594
Epoch 202/1000: L(Train): 0.4878057539463043; L(Test): 0.5196473598480225
Epoch 203/1000: L(Train): 0.4876522719860077; L(Test): 0.5195192694664001
Epoch 204/1000: L(Train): 0.4875023663043976; L(Test): 0.5193942189216614
Epoch 205/1000: L(Train): 0.4873557388782501; L(Test): 0.5192723870277405
Epoch 206/1000: L(Train): 0.48721182346343994; L(Test): 0.5191532969474792
Epoch 207/1000: L(Train): 0.4870709478855133; L(Test): 0.5190368294715881
Epoch 208/1000: L(Train): 0.48693352937698364; L(Test): 0.5189234614372253
Epoch 209/1000: L(Train): 0.48679882287979126; L(Test): 0.5188127160072327
Epoch 210/1000: L(Train): 0.4866671562194824; L(Test): 0.5187044739723206
Epoch 211/1000: L(Train): 0.48653772473335266; L(Test): 0.518598735332489
Epoch 212/1000: L(Train): 0.486411452293396; L(Test): 0.5184957385063171
Epoch 213/1000: L(Train): 0.4862876236438751; L(Test): 0.5183951258659363
Epoch 214/1000: L(Train): 0.4861661493778229; L(Test): 0.5182966589927673
Epoch 215/1000: L(Train): 0.4860474765300751; L(Test): 0.5182004570960999
Epoch 216/1000: L(Train): 0.48593074083328247; L(Test): 0.5181064605712891
Epoch 217/1000: L(Train): 0.4858166575431824; L(Test): 0.5180146098136902
Epoch 218/1000: L(Train): 0.4857047200202942; L(Test): 0.5179245471954346
Epoch 219/1000: L(Train): 0.48559513688087463; L(Test): 0.5178365111351013
Epoch 220/1000: L(Train): 0.48548758029937744; L(Test): 0.5177505016326904
Epoch 221/1000: L(Train): 0.4853818714618683; L(Test): 0.5176662802696228
Epoch 222/1000: L(Train): 0.48527854681015015; L(Test): 0.5175839066505432
Epoch 223/1000: L(Train): 0.48517683148384094; L(Test): 0.5175034403800964
Epoch 224/1000: L(Train): 0.4850771725177765; L(Test): 0.5174245238304138
Epoch 225/1000: L(Train): 0.4849795699119568; L(Test): 0.5173476338386536
Epoch 226/1000: L(Train): 0.484883576631546; L(Test): 0.5172721147537231
Epoch 227/1000: L(Train): 0.4847894012928009; L(Test): 0.517198383808136
Epoch 228/1000: L(Train): 0.48469677567481995; L(Test): 0.5171263217926025
Epoch 229/1000: L(Train): 0.4846063554286957; L(Test): 0.517055869102478
Epoch 230/1000: L(Train): 0.4845169186592102; L(Test): 0.5169866681098938
Epoch 231/1000: L(Train): 0.4844295084476471; L(Test): 0.5169191956520081
Epoch 232/1000: L(Train): 0.48434317111968994; L(Test): 0.5168529152870178
Epoch 233/1000: L(Train): 0.48425865173339844; L(Test): 0.5167883634567261
Epoch 234/1000: L(Train): 0.4841756820678711; L(Test): 0.5167250633239746
Epoch 235/1000: L(Train): 0.48409390449523926; L(Test): 0.5166633129119873
Epoch 236/1000: L(Train): 0.4840138554573059; L(Test): 0.5166026949882507
Epoch 237/1000: L(Train): 0.48393499851226807; L(Test): 0.5165433883666992
Epoch 238/1000: L(Train): 0.48385727405548096; L(Test): 0.5164854526519775
Epoch 239/1000: L(Train): 0.48378127813339233; L(Test): 0.5164287686347961
Epoch 240/1000: L(Train): 0.48370614647865295; L(Test): 0.5163732767105103
Epoch 241/1000: L(Train): 0.48363250494003296; L(Test): 0.5163190364837646
Epoch 242/1000: L(Train): 0.48355984687805176; L(Test): 0.5162659287452698
Epoch 243/1000: L(Train): 0.4834885895252228; L(Test): 0.5162139534950256
Epoch 244/1000: L(Train): 0.48341840505599976; L(Test): 0.516163170337677
Epoch 245/1000: L(Train): 0.4833489954471588; L(Test): 0.5161134600639343
Epoch 246/1000: L(Train): 0.48328059911727905; L(Test): 0.5160645842552185
Epoch 247/1000: L(Train): 0.48321399092674255; L(Test): 0.5160166621208191
Epoch 248/1000: L(Train): 0.48314812779426575; L(Test): 0.5159696936607361
Epoch 249/1000: L(Train): 0.483083575963974; L(Test): 0.5159237384796143
Epoch 250/1000: L(Train): 0.4830198287963867; L(Test): 0.5158785581588745
Epoch 251/1000: L(Train): 0.48295706510543823; L(Test): 0.5158342719078064
Epoch 252/1000: L(Train): 0.4828953444957733; L(Test): 0.5157909393310547
Epoch 253/1000: L(Train): 0.4828346073627472; L(Test): 0.5157483816146851
Epoch 254/1000: L(Train): 0.4827745854854584; L(Test): 0.5157065391540527
Epoch 255/1000: L(Train): 0.4827154874801636; L(Test): 0.5156656503677368
Epoch 256/1000: L(Train): 0.48265743255615234; L(Test): 0.515625536441803
Epoch 257/1000: L(Train): 0.48260000348091125; L(Test): 0.5155860781669617
Epoch 258/1000: L(Train): 0.4825432598590851; L(Test): 0.5155473351478577
Epoch 259/1000: L(Train): 0.4824874699115753; L(Test): 0.5155093669891357
Epoch 260/1000: L(Train): 0.4824325144290924; L(Test): 0.5154720544815063
Epoch 261/1000: L(Train): 0.48237842321395874; L(Test): 0.5154355764389038
Epoch 262/1000: L(Train): 0.4823252856731415; L(Test): 0.5153995752334595
Epoch 263/1000: L(Train): 0.4822726249694824; L(Test): 0.5153644680976868
Epoch 264/1000: L(Train): 0.4822205901145935; L(Test): 0.515329897403717
Epoch 265/1000: L(Train): 0.4821695387363434; L(Test): 0.5152960419654846
Epoch 266/1000: L(Train): 0.4821189045906067; L(Test): 0.5152628421783447
Epoch 267/1000: L(Train): 0.48206937313079834; L(Test): 0.5152299404144287
Epoch 268/1000: L(Train): 0.48202013969421387; L(Test): 0.5151981115341187
Epoch 269/1000: L(Train): 0.4819713830947876; L(Test): 0.5151664018630981
Epoch 270/1000: L(Train): 0.48192381858825684; L(Test): 0.515135645866394
Epoch 271/1000: L(Train): 0.48187699913978577; L(Test): 0.515105128288269

In [11]:
cfs.load_state_dict(torch.load(path_cfs, map_location='cpu'))

### GRU Model

In [12]:
gru = GRUModel(
    n_actions=dataset_train.n_actions, 
    additional_inputs=2, 
    dropout=0.1,
    hidden_size=32,
    )
path_gru = path_spice.replace('spice_', 'gru_')

In [13]:
if train_gru:
    epochs = 1000
    optimizer_gru = torch.optim.Adam(gru.parameters(), lr=0.01)

    gru = training(
        model=gru,
        optimizer=optimizer_gru,
        dataset_train=dataset_train,
        dataset_test=dataset_test,
        epochs=epochs,
        loss_kwargs={'label_smoothing': 0.0},
        ).to(torch.device('cpu'))

    torch.save(gru.state_dict(), path_gru)

In [14]:
gru.load_state_dict(torch.load(path_gru, map_location='cpu'))

# ANALYSIS

In [15]:
from weinhardt2026.analysis.analysis_model_evaluation import analysis_model_evaluation
from weinhardt2026.analysis.analysis_coefficients_distributions import analysis_coefficients_distributions
from weinhardt2026.analysis.analysis_coefficients_individuals import analysis_coefficients_individuals
from analysis_generative import analysis_generative_behavior

In [16]:
estimator.eval()
cfs.eval()
gru.eval()

GRUModel(
  (participant_embedding): Embedding(1, 16)
  (experiment_embedding): Embedding(1, 16)
  (linear_in): Linear(in_features=10, out_features=32, bias=True)
  (dropout): Dropout(p=0.1, inplace=False)
  (gru): GRU(32, 32, batch_first=True)
  (linear_out): Linear(in_features=32, out_features=4, bias=True)
)

## General Analysis

In [17]:
# Dataset-specific behavioral analysis placeholder.
# Replace with Eckstein2024-specific columns if needed.

In [18]:
print("Fitted Castro2025 parameters:")
print("\nBeta_r")
print(cfs.beta_r)
print("\nLapse")
print(cfs.lapse)
print("\nPrior")
print(cfs.prior)
print("\nAlpha exploration rate")
print(cfs.alpha_exploration_rate)
print("\nDecay rate")
print(cfs.decay_rate)
print("\nGamma")
print(cfs.gamma)
print("\nTemperature")
print(cfs.temperature)

Fitted Castro2025 parameters:

Beta_r
tensor([2.6436, 2.5725, 1.6350, 2.6326, 1.4967, 2.2864, 2.0761, 2.0822, 1.3668,
        2.0461, 2.6666, 2.1200, 2.3732, 2.6012, 2.1834, 2.1364, 2.7813, 2.5134,
        2.6401, 3.0772, 2.2167, 2.3841, 1.6499, 5.0067, 1.8361, 1.8675, 1.6592,
        2.4276, 1.9511, 2.3570, 1.9517, 2.0336, 2.0844, 2.6510, 2.3429, 2.4858,
        2.2422, 2.5832, 2.2496, 1.5830, 1.9944, 1.7697, 2.4686, 1.7852, 2.4369,
        2.5515, 2.3137, 1.7513, 2.4290, 2.6330, 2.1942, 1.9395, 2.2016, 1.2631,
        1.6957, 1.7863, 1.7522, 2.4744, 2.4172, 2.4560, 1.7453, 2.0340, 2.3964,
        1.8907, 2.5230, 1.7380, 2.3518, 2.0107, 1.4852, 1.6658, 1.8698, 1.9066,
        3.0647, 2.3329, 1.6459, 2.7516, 2.0881, 1.4873, 2.4971, 3.3913, 2.8240,
        2.1707, 2.4945, 1.8685, 1.6642, 2.5955, 1.7528, 2.7511, 1.6749, 2.8953,
        1.5376, 2.2284, 2.2507, 4.8863, 1.9715, 1.0420, 2.3308, 1.7879, 2.2634,
        2.2010, 2.0965, 1.8153, 2.6210, 2.3455, 2.2507, 2.5202, 1.9719, 2.3137,
        2.4235, 2.3676, 1.7185, 2.1615, 2.1371, 2.3108, 2.2691, 2.5693, 0.8933,
        1.5420, 1.9544, 3.4638, 2.2388, 1.5766, 1.1484, 1.6823, 1.7470, 2.1684,
        1.7731, 1.5931, 2.4112, 1.7155, 2.3654, 1.8480, 2.0375, 1.3781, 2.5068,
        2.7075, 1.9068, 2.2506, 2.1752, 2.0295, 3.1832, 2.8109, 1.9645, 2.1911,
        1.6266, 2.3572, 2.2413, 1.7938, 2.5829, 2.4168, 2.1734, 2.4351, 2.3910,
        2.5642, 2.2012, 2.1717, 0.0941, 1.9410, 1.8271, 2.2230, 2.6185, 2.5641,
        2.4941, 1.9005, 2.5441, 2.4863, 2.1515, 1.7002, 1.7600, 2.3875, 2.4617,
        1.9565, 2.1433, 1.8758, 2.0162, 1.6175, 2.4427, 2.1187, 1.8895, 1.9257,
        1.6526, 1.7275, 2.1571, 3.2357, 2.2158, 2.5959, 1.9360, 2.0479, 2.2703,
        2.4609, 1.9159, 3.4055, 2.0680, 1.5002, 2.0669, 1.6979, 2.1340, 3.2729,
        1.3756, 1.4468, 1.7618, 3.5177, 1.8695, 1.8820, 2.0206, 1.4895, 2.4753,
        2.4634, 2.3435, 1.9044, 2.0820, 2.7355, 2.0876, 1.6144, 2.4201, 1.9492,
        2.1527, 1.7768, 2.5886, 2.3809, 2.3700, 2.5591, 2.2285, 1.3807, 1.6191,
        2.2764, 1.8133, 1.9211, 1.7913, 2.4818, 1.9685, 1.7122, 2.4877, 2.3146,
        1.6555, 1.9676, 2.5482, 2.5265, 2.1206, 2.0006, 2.3035, 2.5019, 1.5301,
        2.0101, 2.0901, 1.5590, 2.5859, 1.9937, 2.3067, 2.2952, 1.4937, 2.0977,
        1.9263, 2.2466, 2.3048, 1.6746, 2.4825, 2.5368, 2.2422, 2.0839, 2.1190,
        2.7466, 2.9930, 2.3582, 2.3193, 2.8504, 2.0184, 2.1374, 2.2122, 2.1236,
        2.6118, 2.0581, 1.9202, 1.8714, 2.1970, 2.3326, 2.2313, 2.0314, 1.7702,
        1.0555, 2.8052, 2.1187, 1.9432, 2.3669, 1.7493, 1.4951, 2.2701, 1.7842,
        1.8234, 2.5160, 2.3638, 1.6863, 1.8880, 1.9553, 2.2743, 2.3864, 2.2861,
        3.3066, 2.1238, 2.1193, 1.7530, 2.4071, 2.0018, 2.2662, 2.1392, 3.4292,
        2.4466, 2.3000, 1.8445, 1.7405, 1.7013, 1.5296, 1.8064, 1.7572, 1.8936,
        2.1248, 2.3659, 2.3607, 1.8287, 2.3780, 1.8556, 1.8419, 1.4722, 2.5930,
        1.5815, 2.8263, 2.4452, 1.8266, 1.7296, 1.7344, 1.4287, 1.9709, 2.9354,
        1.2300, 2.6317, 2.3342, 2.0200, 1.8294, 2.1886, 2.7140, 1.6510, 2.3724,
        2.2599, 2.7955, 2.7400, 2.2348, 2.0441, 1.9537, 2.2481, 1.8930, 1.8142,
        2.1479, 2.4464, 1.9527, 3.1237, 2.3968, 1.9900, 1.8505, 2.4247, 1.7172,
        2.6065, 2.0785, 2.5751, 1.6044, 2.0360, 2.2585, 2.3749, 2.4440, 1.5410,
        2.3639, 2.7109, 2.4498, 2.4622, 1.5243, 1.7120, 1.5512, 2.1204, 2.5844,
        2.2003, 1.1698, 1.5737, 1.6779, 2.0579, 1.2732, 1.4130, 2.2202, 1.7004,
        1.6141, 1.9466, 1.9368, 2.0972, 1.3480, 1.6840, 1.3304, 2.6824, 1.7544,
        1.7167, 2.1614, 2.5803, 1.5305, 1.9141, 2.4329, 2.6276, 2.2108, 2.6121,
        1.7563, 2.5550, 1.7532, 2.4588, 1.4292, 2.1792, 1.7195, 5.0067, 1.5919,
        2.1011, 2.2345, 1.6363, 2.2193, 2.5203, 1.6822, 2.0442, 2.1522, 1.6794,
        1.8432, 2.3728, 2.8438, 1.7981, 2.5787, 2.4301, 2.2355, 2.6979, 2.5243,
        1.8685, 2.1617, 2.0604, 1.8067, 1.9510, 2.3527, 2.0611, 1.4757, 1.7255,
        2.6502, 2.1392, 2.2672, 2.0199, 2.4251, 2.5237, 2.0419, 2.2237, 1.9929,
        2.0916, 1.3899, 1.6722, 2.0143, 1.4677, 2.5486, 1.8138, 1.8405, 1.6283,
        1.8159, 2.0398, 1.7651, 1.8270, 1.8539, 2.1850, 2.4151, 2.1697, 1.9184,
        2.4516, 2.1596, 2.3085, 1.4835, 1.4966, 0.2582, 2.0617, 2.3418, 2.6750,
        2.2969, 2.9106, 1.7400, 1.8913, 2.2047, 1.7077, 1.5498, 1.3327, 2.2673,
        2.1704, 1.9844, 1.9014, 2.2658, 1.7957, 1.9051, 1.8071, 2.0242, 2.1682,
        2.4211, 1.9102, 2.1922, 2.3488, 2.4081, 1.7458, 1.6535, 1.7173, 2.8489,
        2.1910, 2.3261, 2.2156, 2.4122, 1.1313, 2.6602, 1.9594, 1.7501, 1.8679,
        2.1534, 2.0962, 2.1084, 2.6949, 2.3335, 2.0126, 1.6908, 2.1384, 2.4248,
        1.8989, 1.5810, 1.8517, 2.1289, 2.0586, 1.9497, 2.9454, 1.9278, 2.2432,
        2.0602, 1.1854, 2.6251, 2.4093, 2.1394, 1.8447, 2.0384, 2.3386, 1.5113,
        2.4085, 1.7005, 1.9382, 2.4657, 1.7833, 2.6210, 2.0199, 1.8816, 1.4013,
        1.7860, 2.0676, 1.5757, 2.2456, 3.0623, 1.7450, 1.6183, 1.7902, 1.9346,
        2.1886, 3.3135, 2.1380, 1.9812, 1.9207, 1.8710, 1.8710, 1.4815, 1.9966,
        2.4141, 1.4171, 2.5531, 2.6627, 2.0384, 1.6808, 2.3231, 2.0467, 2.2903,
        2.4422, 1.7073, 1.7268, 2.2706, 1.6518, 1.7535, 2.1209, 2.0894, 2.2317,
        2.0596, 1.6893, 1.7963, 1.8358, 1.7087, 2.2142, 1.6337, 2.4391, 1.4340,
        2.5052, 1.8835, 2.1919, 2.2037, 2.5875, 1.6700, 2.1948, 1.7528, 2.3958,
        1.8357, 2.3964, 2.5608, 2.8748, 1.5418, 2.4455, 1.9794, 2.0235, 2.0926,
        2.0862, 2.1806, 2.0823, 2.6823, 2.8738, 1.0680, 1.9992, 2.5604, 1.8709,
        2.3168, 2.1981, 1.9984, 1.9447, 2.1749, 1.9746, 2.0324, 1.8521, 1.7204,
        2.1473, 1.8578, 2.1481, 1.8444, 1.5708, 2.3925, 2.5621, 1.4293, 2.3925,
        0.9423, 2.3518, 1.9686, 1.7665, 1.4906, 1.6596, 2.1464, 2.2139, 1.4071,
        2.0591, 2.0239, 1.6750, 1.6002, 1.8723, 2.2640, 1.9034, 2.5501, 2.3006,
        1.3520, 1.7126, 1.8059, 1.9852, 2.1693, 1.8659, 1.4792, 2.5484, 1.9107,
        2.2937, 2.0499, 2.5740, 1.9422, 5.0067, 1.9718, 2.1007, 1.5642, 2.5135,
        1.9788, 2.0152, 2.4656, 1.9536, 2.1466, 1.9345, 2.3024, 1.2903, 2.3476,
        2.4044, 1.7857, 1.9811, 2.1793, 2.4284, 2.5085, 2.2860, 2.6247, 2.4833,
        2.0557, 2.6465, 3.0086, 2.9681, 1.8525, 2.2097, 2.0713, 2.4586, 2.0063,
        1.9659, 2.3547, 2.2892, 1.2728, 2.1316, 2.4059, 1.9198, 1.2460, 3.1770,
        1.4993, 1.6892, 1.6945, 1.6073, 2.0318, 1.7978, 1.9607, 1.9373, 2.0372,
        1.8365, 2.2620, 1.8333, 2.3565, 1.9457, 2.5261, 2.7333, 1.9425, 2.8052,
        1.4043, 1.2978, 2.1542, 2.2100, 2.6297, 2.5284, 1.4135, 2.5175, 2.0958,
        2.1449, 2.4289, 1.7615, 1.8761, 1.8383, 2.6200, 1.4375, 2.7881, 1.9313,
        2.2859, 2.3966, 2.1208, 1.6995, 1.3279, 1.6255, 1.7457, 2.2951, 2.2688,
        1.5506, 2.5229, 1.9591, 2.4430, 2.1982, 1.8578, 1.8851, 1.7911, 1.3816,
        1.5734, 2.5144, 1.9141, 1.7992, 2.5191, 2.5926, 1.9006, 1.3976, 2.2527,
        1.7819, 2.0646, 2.0833, 1.7599, 2.2943, 2.1461, 1.6475, 2.6971, 1.7729,
        2.2795, 1.4493, 2.3745, 1.1450, 1.7638, 1.3699, 1.4193, 2.0597, 2.0986,
        2.3172, 1.8935, 1.6470, 1.7510, 2.3494, 2.0434, 2.6415, 2.6159, 2.3629,
        2.5436, 1.6779, 2.1183, 1.8471, 1.7560, 3.0830, 2.2492, 1.6873, 1.6322,
        2.1685, 1.8441, 1.7390, 2.8094, 2.3469, 1.7499, 1.7784, 2.8785, 1.8420,
        2.4194, 1.8983, 1.9432, 1.7467, 1.9356, 2.4051, 2.0613, 2.0650, 2.2563,
        2.0221, 2.0186, 1.9699, 2.3076, 1.8255, 2.9208, 1.4807, 3.3017, 2.1418,
        2.5577, 1.8166, 2.1887, 2.5972, 2.5108, 1.4374, 2.4260, 1.7829, 2.1093,
        2.4084, 1.7281, 2.7199, 2.3683, 2.3743, 2.6695, 1.7322, 1.9220, 2.3341,
        2.2522, 2.2887, 2.4480, 2.0423, 1.8767, 2.5858, 1.9840],
       grad_fn=<ClampBackward1>)

Lapse
tensor([0.0964, 0.0309, 0.0788, 0.2254, 0.1741, 0.1080, 0.0157, 0.1183, 0.1071,
        0.0508, 0.2254, 0.1644, 0.0975, 0.6305, 0.0219, 0.1971, 0.0315, 0.1084,
        0.0200, 0.3304, 0.0271, 0.0224, 0.1683, 0.0408, 0.0678, 0.0145, 0.0152,
        0.1853, 0.0252, 0.1698, 0.5163, 0.0626, 0.0570, 0.0231, 0.1214, 0.0635,
        0.0299, 0.0368, 0.1284, 0.0156, 0.0618, 0.0148, 0.0856, 0.0453, 0.0112,
        0.0600, 0.0596, 0.0473, 0.2482, 0.0801, 0.0122, 0.0229, 0.0524, 0.0216,
        0.0224, 0.0100, 0.0218, 0.1360, 0.0163, 0.1093, 0.0205, 0.0100, 0.0154,
        0.1058, 0.1269, 0.1027, 0.0480, 0.1551, 0.2058, 0.1911, 0.0761, 0.0312,
        0.0295, 0.3764, 0.0243, 0.1289, 0.0251, 0.0311, 0.1517, 0.3566, 0.0589,
        0.0786, 0.4197, 0.0451, 0.2036, 0.0399, 0.0667, 0.1384, 0.0167, 0.3155,
        0.0968, 0.0673, 0.1170, 0.5328, 0.0561, 0.0269, 0.2183, 0.2377, 0.0172,
        0.0139, 0.4877, 0.1638, 0.0363, 0.0214, 0.1613, 0.1545, 0.0231, 0.2004,
        0.0105, 0.0597, 0.5873, 0.0224, 0.0340, 0.0954, 0.0546, 0.2859, 0.1889,
        0.0246, 0.2157, 0.1654, 0.0304, 0.0169, 0.0303, 0.0262, 0.0151, 0.0997,
        0.0379, 0.0591, 0.1630, 0.1275, 0.1153, 0.0110, 0.0491, 0.1382, 0.0917,
        0.0933, 0.0742, 0.1075, 0.1386, 0.1146, 0.0758, 0.2323, 0.0624, 0.0520,
        0.0356, 0.1313, 0.1768, 0.0480, 0.1036, 0.0681, 0.0100, 0.1125, 0.0710,
        0.2010, 0.0160, 0.0267, 0.0449, 0.1464, 0.0274, 0.3192, 0.0425, 0.2065,
        0.3264, 0.1622, 0.2372, 0.0717, 0.0732, 0.0442, 0.1135, 0.1309, 0.1773,
        0.0490, 0.1127, 0.0276, 0.0194, 0.0100, 0.0742, 0.1013, 0.0316, 0.0170,
        0.0623, 0.0659, 0.0231, 0.4696, 0.1043, 0.1081, 0.0112, 0.0764, 0.0387,
        0.3791, 0.1222, 0.7176, 0.0489, 0.0202, 0.0110, 0.0375, 0.1170, 0.2318,
        0.1038, 0.1126, 0.0112, 0.1139, 0.1520, 0.0271, 0.0454, 0.0333, 0.0422,
        0.0402, 0.0547, 0.0602, 0.0314, 0.1984, 0.0343, 0.0442, 0.3540, 0.0168,
        0.0558, 0.0192, 0.2095, 0.1065, 0.0981, 0.0347, 0.0886, 0.1069, 0.0446,
        0.0812, 0.1859, 0.0100, 0.0763, 0.0459, 0.1144, 0.0406, 0.0202, 0.2950,
        0.0349, 0.1462, 0.0612, 0.0400, 0.0805, 0.0324, 0.1140, 0.1663, 0.0459,
        0.0234, 0.0468, 0.2802, 0.2570, 0.0170, 0.2037, 0.2707, 0.0100, 0.1687,
        0.0652, 0.0278, 0.0247, 0.0101, 0.1485, 0.1837, 0.0351, 0.1802, 0.0655,
        0.0858, 0.3072, 0.1955, 0.0870, 0.0742, 0.0306, 0.0715, 0.0177, 0.0396,
        0.1594, 0.0563, 0.0712, 0.1619, 0.0358, 0.1820, 0.0256, 0.0105, 0.0851,
        0.0187, 0.0147, 0.0100, 0.0298, 0.1580, 0.1078, 0.0881, 0.1925, 0.0100,
        0.0512, 0.1385, 0.0477, 0.1678, 0.2002, 0.0516, 0.2169, 0.1093, 0.0563,
        0.2635, 0.0286, 0.0249, 0.0357, 0.0179, 0.1262, 0.0149, 0.2744, 0.0502,
        0.0267, 0.1419, 0.0563, 0.5543, 0.0204, 0.0144, 0.1660, 0.0100, 0.3610,
        0.0537, 0.0862, 0.0394, 0.0244, 0.1096, 0.0182, 0.0523, 0.2216, 0.0443,
        0.0325, 0.1334, 0.0728, 0.0248, 0.0125, 0.0235, 0.1305, 0.5516, 0.0946,
        0.3325, 0.1017, 0.0566, 0.3131, 0.0133, 0.0148, 0.4322, 0.0379, 0.1288,
        0.0297, 0.0611, 0.0176, 0.0180, 0.1655, 0.2201, 0.2910, 0.0534, 0.0167,
        0.0320, 0.0964, 0.0172, 0.5642, 0.0709, 0.0216, 0.2627, 0.0939, 0.0591,
        0.1517, 0.0169, 0.1563, 0.2235, 0.0513, 0.0534, 0.0644, 0.0466, 0.0275,
        0.0873, 0.0800, 0.0564, 0.0610, 0.0258, 0.0914, 0.0181, 0.0131, 0.0252,
        0.0288, 0.0260, 0.0649, 0.0776, 0.0806, 0.2252, 0.0596, 0.0157, 0.0158,
        0.1280, 0.1241, 0.0585, 0.0124, 0.3462, 0.3666, 0.1159, 0.1248, 0.0723,
        0.0525, 0.2483, 0.0386, 0.0200, 0.0528, 0.0907, 0.0687, 0.1057, 0.2318,
        0.1532, 0.1197, 0.0100, 0.0617, 0.0618, 0.0271, 0.3115, 0.2764, 0.0554,
        0.1000, 0.1073, 0.0494, 0.2715, 0.1678, 0.0210, 0.0476, 0.0642, 0.0424,
        0.1336, 0.2464, 0.1009, 0.0191, 0.0563, 0.1312, 0.0214, 0.0972, 0.0371,
        0.0128, 0.1464, 0.0218, 0.1320, 0.0113, 0.0543, 0.0169, 0.0183, 0.0227,
        0.1698, 0.0179, 0.0204, 0.1182, 0.1136, 0.0442, 0.3894, 0.0982, 0.0778,
        0.1082, 0.0584, 0.0625, 0.0100, 0.0163, 0.8124, 0.0100, 0.0241, 0.0933,
        0.0273, 0.0107, 0.0259, 0.1324, 0.3900, 0.0579, 0.0256, 0.0544, 0.1233,
        0.1666, 0.0236, 0.0536, 0.0100, 0.0272, 0.9513, 0.0100, 0.1316, 0.2183,
        0.0163, 0.1446, 0.1153, 0.0983, 0.2291, 0.0236, 0.0294, 0.2240, 0.0904,
        0.0590, 0.1675, 0.0404, 0.1974, 0.0432, 0.0259, 0.0610, 0.0121, 0.0195,
        0.0405, 0.0229, 0.1172, 0.2010, 0.1174, 0.1728, 0.2238, 0.0465, 0.2925,
        0.0459, 0.2244, 0.0168, 0.0666, 0.1326, 0.2742, 0.0996, 0.0203, 0.2199,
        0.0246, 0.0163, 0.0419, 0.1214, 0.3336, 0.1032, 0.0994, 0.1303, 0.0909,
        0.0588, 0.0258, 0.0409, 0.0721, 0.0342, 0.0335, 0.2411, 0.1070, 0.0145,
        0.0959, 0.0277, 0.0925, 0.0379, 0.1747, 0.0876, 0.0398, 0.0121, 0.0555,
        0.1154, 0.0161, 0.0399, 0.0316, 0.2167, 0.0614, 0.1424, 0.2039, 0.1443,
        0.0714, 0.0575, 0.0219, 0.0242, 0.2123, 0.0416, 0.2772, 0.0919, 0.0875,
        0.0244, 0.0298, 0.2120, 0.0111, 0.0295, 0.0159, 0.0310, 0.0848, 0.0249,
        0.0559, 0.0573, 0.1020, 0.2231, 0.1227, 0.4173, 0.0346, 0.0695, 0.1476,
        0.1411, 0.0139, 0.0707, 0.0821, 0.0100, 0.0140, 0.1517, 0.0500, 0.0812,
        0.1387, 0.0100, 0.0450, 0.0569, 0.0381, 0.0497, 0.1441, 0.1304, 0.4224,
        0.0882, 0.2103, 0.0172, 0.1364, 0.1843, 0.1799, 0.0603, 0.0213, 0.0986,
        0.0443, 0.0975, 0.0179, 0.0268, 0.0158, 0.0684, 0.0229, 0.0410, 0.0939,
        0.0182, 0.3129, 0.0672, 0.4542, 0.0208, 0.0456, 0.0723, 0.0863, 0.0683,
        0.0134, 0.2122, 0.0260, 0.0165, 0.0101, 0.0874, 0.0381, 0.0397, 0.1896,
        0.2976, 0.0560, 0.0433, 0.0757, 0.0228, 0.0223, 0.2739, 0.0265, 0.1104,
        0.0274, 0.1100, 0.0366, 0.0217, 0.0154, 0.0275, 0.0152, 0.0418, 0.0178,
        0.0458, 0.0218, 0.1877, 0.0179, 0.4159, 0.0395, 0.0244, 0.1008, 0.1855,
        0.1705, 0.1041, 0.0174, 0.0186, 0.1702, 0.0199, 0.0100, 0.3940, 0.1771,
        0.0827, 0.0864, 0.0785, 0.1933, 0.4887, 0.1118, 0.1099, 0.0449, 0.1848,
        0.1113, 0.0114, 0.0354, 0.0736, 0.0419, 0.0326, 0.0389, 0.0863, 0.1133,
        0.0628, 0.0419, 0.0107, 0.0696, 0.0597, 0.0203, 0.1360, 0.1007, 0.1721,
        0.1675, 0.1321, 0.1505, 0.0544, 0.1109, 0.0351, 0.0493, 0.1423, 0.0319,
        0.1776, 0.1559, 0.0235, 0.0662, 0.3165, 0.0862, 0.1464, 0.0438, 0.1458,
        0.0771, 0.0368, 0.0372, 0.0183, 0.0175, 0.1048, 0.0381, 0.0165, 0.1453,
        0.0579, 0.1844, 0.1545, 0.1289, 0.0184, 0.2646, 0.0270, 0.0513, 0.0666,
        0.1639, 0.0324, 0.1339, 0.0933, 0.1369, 0.1415, 0.0159, 0.1611, 0.0947,
        0.1184, 0.1377, 0.0100, 0.0755, 0.0252, 0.0540, 0.0818, 0.5395, 0.0133,
        0.0960, 0.0274, 0.0471, 0.0121, 0.2359, 0.0491, 0.1209, 0.0214, 0.2100,
        0.3650, 0.1853, 0.0467, 0.3766, 0.0857, 0.0679, 0.0327, 0.0198, 0.0750,
        0.0247, 0.1003, 0.1997, 0.0301, 0.1635, 0.1433, 0.1332, 0.0422, 0.2370,
        0.0598, 0.1799, 0.1561, 0.1032, 0.4473, 0.0409, 0.0129, 0.2010, 0.0100,
        0.3808, 0.0616, 0.1457, 0.1042, 0.0100, 0.1142, 0.0343, 0.2315, 0.1366,
        0.2186, 0.0146, 0.1390, 0.0469, 0.1138, 0.1896, 0.0519, 0.0589, 0.0214,
        0.0321, 0.1462, 0.0296, 0.0514, 0.0125, 0.4599, 0.0560, 0.0389, 0.5512,
        0.0153, 0.2552, 0.0100, 0.7887, 0.0888, 0.0194, 0.2573, 0.6936, 0.1268,
        0.1177, 0.0102, 0.0873, 0.1977, 0.0402, 0.1477, 0.1429, 0.0877, 0.1087,
        0.0273, 0.2818, 0.0782, 0.0266, 0.0793, 0.5631, 0.0199, 0.5697, 0.1159,
        0.0835, 0.0702, 0.2027, 0.1330, 0.0772, 0.0223, 0.0271, 0.0720, 0.1353,
        0.0508, 0.0325, 0.0867, 0.1564, 0.1201, 0.0413, 0.3711, 0.1190, 0.0728,
        0.1931, 0.0336, 0.0245, 0.0252, 0.1068, 0.3249, 0.0345],
       grad_fn=<ClampBackward1>)

Prior
tensor([0.9900, 0.9900, 0.9900, 0.9900, 0.4431, 0.6346, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.5853, 0.9900, 0.0764, 0.1360, 0.9900, 0.9900,
        0.3435, 0.9900, 0.9900, 0.9900, 0.9900, 0.1040, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.3149, 0.9900, 0.9900, 0.1158, 0.9900,
        0.9900, 0.9900, 0.1438, 0.9900, 0.9900, 0.9900, 0.2523, 0.9900, 0.7248,
        0.9900, 0.6095, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.2221, 0.9900, 0.9900, 0.4361,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0270, 0.0202, 0.9900,
        0.7099, 0.9900, 0.9900, 0.2301, 0.3971, 0.9900, 0.4349, 0.9900, 0.9900,
        0.9900, 0.9002, 0.9900, 0.1158, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0571, 0.9900, 0.5457, 0.6935, 0.6161, 0.2975,
        0.9900, 0.9900, 0.0139, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0114,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0417, 0.9900,
        0.9900, 0.0100, 0.9900, 0.3752, 0.9900, 0.9900, 0.9900, 0.9900, 0.3085,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.1690, 0.9900, 0.9900,
        0.9900, 0.9900, 0.0483, 0.9900, 0.4277, 0.5791, 0.9900, 0.7115, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.0346, 0.1486, 0.9900, 0.0682, 0.1362,
        0.9900, 0.0574, 0.9900, 0.2468, 0.9900, 0.9900, 0.0981, 0.9900, 0.9900,
        0.0199, 0.9900, 0.9900, 0.6844, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.1338, 0.5188, 0.0619, 0.9900, 0.9900, 0.9900, 0.9900, 0.3076, 0.9900,
        0.0332, 0.5005, 0.9900, 0.2632, 0.9900, 0.9900, 0.9900, 0.0100, 0.9900,
        0.9900, 0.9900, 0.7807, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.4213,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.6441, 0.0100, 0.9900, 0.5945, 0.9900, 0.0236, 0.9900, 0.4091, 0.8917,
        0.9900, 0.9900, 0.3642, 0.9900, 0.3813, 0.5117, 0.1929, 0.7763, 0.9900,
        0.1833, 0.9900, 0.9900, 0.9900, 0.2731, 0.9900, 0.9900, 0.9900, 0.0814,
        0.9900, 0.1653, 0.9900, 0.9900, 0.9900, 0.3141, 0.2366, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.0100, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.0401, 0.9900, 0.5967, 0.9900, 0.3602, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0152, 0.9900, 0.6186, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0177, 0.1257, 0.0100, 0.9900, 0.9900, 0.9900,
        0.1834, 0.9900, 0.9900, 0.9900, 0.9900, 0.1038, 0.9900, 0.9900, 0.4715,
        0.5097, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.0245, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.5662, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.8012, 0.9900,
        0.9900, 0.4635, 0.9900, 0.4876, 0.9900, 0.9900, 0.9900, 0.0170, 0.9900,
        0.9900, 0.9900, 0.9900, 0.0128, 0.9900, 0.9900, 0.0100, 0.9900, 0.0115,
        0.9900, 0.5299, 0.7069, 0.9900, 0.9900, 0.7086, 0.9900, 0.0165, 0.4823,
        0.9900, 0.3042, 0.0164, 0.0100, 0.9900, 0.4379, 0.0117, 0.9900, 0.9900,
        0.9900, 0.9900, 0.5160, 0.9900, 0.2298, 0.9900, 0.3329, 0.9900, 0.4272,
        0.6010, 0.1472, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.4786,
        0.2698, 0.0358, 0.2375, 0.9900, 0.9900, 0.1565, 0.9900, 0.9900, 0.0421,
        0.2733, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0737,
        0.9900, 0.9900, 0.4647, 0.9900, 0.9900, 0.9900, 0.4532, 0.3468, 0.9900,
        0.9900, 0.9900, 0.9900, 0.4557, 0.9900, 0.9900, 0.9900, 0.1973, 0.9900,
        0.1843, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.3937, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.1102, 0.0100, 0.9900, 0.9900,
        0.9900, 0.5192, 0.9900, 0.9900, 0.9900, 0.2296, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.6964, 0.9900, 0.0699, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.2145, 0.5678, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.3550, 0.9900, 0.9900, 0.9900,
        0.9900, 0.4675, 0.1929, 0.4298, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.3714, 0.9900, 0.0100, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900,
        0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.9900, 0.0100, 0.9900, 0.9900,

## Analysis Model Evaluation

In [24]:
analysis_model_evaluation(
    dataset=dataset_train,
    spice_model=estimator,
    benchmark_model=cfs.to(torch.device('cpu')),
    gru_model=gru.eval().to(torch.device('cpu')),
    )

Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...
Computing choice probabilities with SPICE model...

,Trial Lik.,(std),n_parameters,(std),NLL,AIC,BIC
Benchmark,0.621020,0.159128,13.000000,0.000000,232753.859375,465533.71875,465678.0000
GRU,0.627344,0.156140,6852.000000,0.000000,227803.765625,469311.53125,545363.6250
SPICE-RNN,0.602785,0.156805,15948.000000,0.000000,247314.750000,526525.50000,703536.3750
SPICE,0.595553,0.157122,38.266823,2.774654,253211.718750,506500.40625,506927.5625

In [25]:
analysis_model_evaluation(
    dataset=dataset_test,
    spice_model=estimator,
    benchmark_model=cfs.to(torch.device('cpu')),
    gru_model=gru.eval().to(torch.device('cpu')),
    )

Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...
Computing choice probabilities with SPICE model...

,Trial Lik.,(std),n_parameters,(std),NLL,AIC,BIC
Benchmark,0.598384,0.161196,13.000000,0.000000,65651.343750,131328.687500,131455.546875
GRU,0.618730,0.157360,6852.000000,0.000000,61376.554688,136457.109375,203322.843750
SPICE-RNN,0.593454,0.156552,15948.000000,0.000000,66708.921875,165313.843750,320943.562500
SPICE,0.584291,0.156896,38.266823,3.530624,68698.375000,137473.281250,137846.718750

## Analysis generative behavior

In [ ]:
estimator.use_sindy(True)
generate_behavior(
    model=estimator,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_spice.csv'
)

estimator.use_sindy(False)
generate_behavior(
    model=estimator,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_spice_rnn.csv'
)

gru.eval()
generate_behavior(
    model=gru,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_gru.csv'
)

generate_behavior(
    model=cfs,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_cfs.csv'
)

In [ ]:
analysis_generative_behavior(
    path_data_real=path_data,
    path_data_gru='data/eckstein2024_gru.csv',
    path_data_benchmark='data/eckstein2024_cfs.csv',
    path_data_spice='data/eckstein2024_spice.csv',
    path_data_spice_rnn='data/eckstein2024_spice_rnn.csv',
    output_dir='results',
)

## Analysis coefficient distributions

In [ ]:
# analysis_coefficients_distributions(
#     spice_model=estimator,
#     output_dir='results',
# )

## Analysis Individual Differences

In [ ]:
# analysis_coefficients_individuals(
#     criterion="SomeCriterionColumnInYourDataset",
#     analysis="disc",  # also: "cont"
#     reference="ReferenceGroupFromCriterionColumn",  # only necessary if analysis="disc"
    
#     path_data=path_file,
    
#     spice_model=estimator,
    
#     dir_output='results',
# )