In [ ]:
#!git clone https://github.com/whyhardt/SPICE.git

In [ ]:
# !pip install -e SPICE

In [1]:
import sys

import torch

from spice import SpiceEstimator

sys.path.append("../../..")
from weinhardt2026.utils.benchmarking_gru import GRUModel, training
from weinhardt2026.studies.castro2025.benchmarking_castro2025 import Castro2025Model, get_dataset, generate_behavior
import spice_castro2025, spice_castro2025_2

## Load dataset

In [2]:
path_data = 'data/eckstein2024.csv'
test_sessions = (2,)  # pick sessions that exist for all participants; adjust if needed
dataset_train, dataset_test, info_dataset = get_dataset(path_data=path_data, test_sessions=test_sessions, verbose=True)

Shape of dataset: torch.Size([4158, 150, 1, 13])
Number of participants: 862
Number of actions in dataset: 4

In [ ]:
# from spice import SpiceDataset

# # keep only 100 timesteps
# dataset_train = SpiceDataset(dataset_train.xs[:, :100], dataset_train.ys[:, :100])

# # keep only 100 participants for rapid prototyping
# keep_participants = torch.arange(0, 50)

# def keep_subset(dataset, subset):
#     participant_ids = dataset.xs[:, 0, 0, -1]
#     mask = torch.isin(participant_ids, subset)
#     return SpiceDataset(dataset.xs[mask], dataset.ys[mask])

# dataset_train = keep_subset(dataset_train, keep_participants)
# dataset_test = keep_subset(dataset_test, keep_participants)

## SPICE Setup

## SPICE Training

Let's setup now the `SpiceEstimator` object and fit it to the data! 

We are going to do this in two steps:

1. Without fitting the SINDy coefficients to get the pure RNN performance given the selected architecture. 
2. With fitting SINDy coefficients to get the final performance of the interpretable model

That way we can disentangle the gap between GRU and SPICE w.r.t. architecture and SINDy library

In [ ]:
# fitting without SINDy coefficients
path_spice = 'params/spice_castro2025_2.pkl'

estimator = SpiceEstimator(
        # model paramaeters
        spice_class=spice_castro2025_2.SpiceModel,
        spice_config=spice_castro2025_2.CONFIG,
        n_actions=dataset_train.n_actions,
        n_participants=dataset_train.n_participants,
        
        epochs=1,
        
        sindy_weight=0,
        sindy_library_polynomial_degree=2,
        sindy_pruning_frequency=100,
        sindy_ensemble_pruning=0.05,
        sindy_threshold_pruning=0.01,
        sindy_alpha=0.0001,
        
        save_path_spice=path_spice,
        verbose=True,
    )
estimator.fit(dataset_train.xs, dataset_train.ys, dataset_test.xs, dataset_test.ys)

In [3]:
path_spice = 'params/spice_castro2025_2_noens_noprune.pkl'

estimator = SpiceEstimator(
        # model paramaeters
        spice_class=spice_castro2025_2.SpiceModel,
        spice_config=spice_castro2025_2.CONFIG,
        n_actions=dataset_train.n_actions,
        n_participants=dataset_train.n_participants,
        
        epochs=1000,
        warmup_steps=200,
        learning_rate=0.01,
        ensemble_size=1,
        
        sindy_weight=0.1,
        sindy_alpha=0.0001,
        sindy_pruning_frequency=100,
        sindy_threshold_pruning=0.01,
        sindy_ensemble_pruning=0.05,
        sindy_library_polynomial_degree=2,

        verbose=True,
        # device = torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
        save_path_spice=path_spice,
    )

In [ ]:
estimator.fit(dataset_train.xs, dataset_train.ys, dataset_test.xs, dataset_test.ys)

================================================================================================================================================================
 24%|████████▉                            | 243/1000 [19:54<1:02:01,  4.92s/it, L(Train)=0.4903638, L(Val,RNN)=0.5158772, L(Val,SINDy)=0.8586412, Conv=1.40e-03]
----------------------------------------------------------------------------------------------------------------------------------------------------------------
SPICE Model (Coefficients: 37):
value_reward_env[t+1]        = -0.04 1 + 0.961 value_reward_env[t] + 0.001 reward[t] + -0.005 value_reward_env^2 + -0.013 value_reward_env*reward[t] + 0.005 reward[t]^2
value_reward_chosen[t+1]     = -0.377 1 + 1.005 value_reward_chosen[t] + 0.064 reward_env + 0.223 reward[t] + -0.005 value_reward_chosen^2 + 0.02 value_reward_chosen*reward_env + -0.149 value_reward_chosen*reward[t] + -0.005 reward_env^2 + -0.122 reward_env*reward[t] + 0.453 reward[t]^2
value_reward_not_chosen[t+1] = -0.008 1 + 0.985 value_reward_not_chosen[t] + 0.014 reward_env + -0.003 value_reward_not_chosen^2 + 0.002 value_reward_not_chosen*reward_env + 0.001 reward_env^2
value_choice_chosen[t+1]     = 0.208 1 + 0.834 value_choice_chosen[t] + 0.012 value_choice_chosen^2
value_choice_not_chosen[t+1] = -0.068 1 + 0.39 value_choice_not_chosen[t] + -0.2 value_choice_not_chosen^2
volatility_chosen[t+1]       = 0.206 1 + 0.849 volatility_chosen[t] + 2.039 dvalue + -0.025 volatility_chosen^2 + 0.227 volatility_chosen*dvalue + -0.428 dvalue^2
volatility_not_chosen[t+1]   = -0.051 1 + 0.66 volatility_not_chosen[t] + -0.052 volatility_not_chosen^2
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Pruning patience:
value_reward_env:        1, 0, 1, 1, 1, 1
value_reward_chosen:     0, 1, 1, 0, 1, 1, 1, 1, 1, 0
value_reward_not_chosen: 1, 1, 1, 1, 1, 1
value_choice_chosen:     0, 0, 1
value_choice_not_chosen: 1, 0, 0
volatility_chosen:       1, 0, 0, 1, 0, 1
volatility_not_chosen:   1, 0, 1
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Term presence across SPICE models (number of models=50):
value_reward_env:        50, 50, 50, 50, 50, 50
value_reward_chosen:     50, 50, 50, 50, 50, 50, 50, 50, 50, 50
value_reward_not_chosen: 50, 50, 50, 50, 50, 50
value_choice_chosen:     50, 50, 50
value_choice_not_chosen: 50, 50, 50
volatility_chosen:       50, 50, 50, 50, 50, 50
volatility_not_chosen:   50, 50, 50
================================================================================================================================================================

Training interrupted. Continuing with further operations...

================================================================================
Stage 2: SINDy refit
================================================================================

  6%|▌         | 55/1000 [00:18<06:09,  2.56it/s, loss=0.0244261, n_params=37.00+/-0.00]

In [4]:
estimator.load_spice(path_spice)
# estimator.aggregate_coefficients()

In [5]:
# Print example SPICE model for first participant
print("\nExample SPICE model (participant 0):")
estimator.print_spice_model(participant_id=0)

Example SPICE model (participant 0):
value_reward_env[t+1]        = 0.235 1 + 0.371 value_reward_env[t] + -0.178 reward[t] + 0.03 value_reward_env^2 + -0.438 value_reward_env*reward[t] + -0.306 reward[t]^2
value_reward_chosen[t+1]     = -0.246 1 + 0.858 value_reward_chosen[t] + -0.651 reward_env + 0.618 reward[t] + 0.037 value_reward_mean + -0.024 value_reward_chosen^2 + 0.043 value_reward_chosen*reward_env + -0.077 value_reward_chosen*reward[t] + 0.05 value_reward_chosen*value_reward_mean + -0.084 reward_env^2 + -0.042 reward_env*reward[t] + -0.657 reward_env*value_reward_mean + 0.716 reward[t]^2 + -0.123 reward[t]*value_reward_mean + -0.03 value_reward_mean^2
value_reward_not_chosen[t+1] = -0.067 1 + 0.959 value_reward_not_chosen[t] + 0.068 reward_env + 0.042 value_reward_mean + -0.002 value_reward_not_chosen^2 + 0.053 value_reward_not_chosen*reward_env + 0.001 value_reward_not_chosen*value_reward_mean + 0.016 reward_env^2 + -0.003 reward_env*value_reward_mean + 0.003 value_reward_mean^2
value_choice_chosen[t+1]     = 0.581 1 + 0.808 value_choice_chosen[t] + 0.111 value_choice_mean + -0.019 value_choice_chosen^2 + 0.036 value_choice_chosen*value_choice_mean + 0.009 value_choice_mean^2
value_choice_not_chosen[t+1] = 0.028 1 + 0.192 value_choice_not_chosen[t] + 0.309 value_choice_mean + -0.07 value_choice_not_chosen^2 + -0.042 value_choice_not_chosen*value_choice_mean + 0.049 value_choice_mean^2
volatility_chosen[t+1]       = -1.629 1 + -0.151 volatility_chosen[t] + 2.573 dvalue + -0.066 volatility_chosen^2 + 0.08 volatility_chosen*dvalue + 0.27 dvalue^2
volatility_not_chosen[t+1]   = 0.154 1 + 0.953 volatility_not_chosen[t] + -0.125 dvalue + -0.015 volatility_not_chosen^2 + -0.016 volatility_not_chosen*dvalue + 0.061 dvalue^2

## Benchmarking

### Castro2025 benchmark model

In [3]:
path_spice = 'params/spice_castro2025.pkl'

# Benchmark model: Castro et al. 2025
cfs = Castro2025Model(
    n_participants=dataset_train.n_participants,
    n_actions=dataset_train.n_actions,
    batch_first=True,
    )

path_cfs = path_spice.replace('spice_', 'cfs_')

In [ ]:
optimizer_cfs = torch.optim.Adam(params=cfs.parameters(), lr=0.01)
epochs = 1000

cfs = training(
    model=cfs,
    optimizer=optimizer_cfs,
    dataset_train=dataset_train,
    dataset_test=dataset_test,
    epochs=epochs,
    loss_kwargs={'label_smoothing': 0.0},
)

torch.save(cfs.state_dict(), path_cfs)

Epoch 1/1000: L(Train): 0.6583927869796753; L(Test): 0.6491681933403015
Epoch 2/1000: L(Train): 0.6574205160140991; L(Test): 0.6484070420265198
Epoch 3/1000: L(Train): 0.6564786434173584; L(Test): 0.6476723551750183
Epoch 4/1000: L(Train): 0.6555653810501099; L(Test): 0.6469632983207703
Epoch 5/1000: L(Train): 0.6546801924705505; L(Test): 0.6462777853012085
Epoch 6/1000: L(Train): 0.6538210511207581; L(Test): 0.6456145644187927
Epoch 7/1000: L(Train): 0.6529873013496399; L(Test): 0.6449723243713379
Epoch 8/1000: L(Train): 0.6521780490875244; L(Test): 0.6443491578102112
Epoch 9/1000: L(Train): 0.6513909101486206; L(Test): 0.6437438130378723
Epoch 10/1000: L(Train): 0.650625467300415; L(Test): 0.6431549191474915
Epoch 11/1000: L(Train): 0.6498801112174988; L(Test): 0.6425809264183044
Epoch 12/1000: L(Train): 0.6491535902023315; L(Test): 0.642021656036377
Epoch 13/1000: L(Train): 0.6484441757202148; L(Test): 0.6414744853973389
Epoch 14/1000: L(Train): 0.6477522253990173; L(Test): 0.6409397125244141
Epoch 15/1000: L(Train): 0.6470742225646973; L(Test): 0.6404157280921936
Epoch 16/1000: L(Train): 0.6464107036590576; L(Test): 0.6399008631706238
Epoch 17/1000: L(Train): 0.6457608938217163; L(Test): 0.6393943428993225
Epoch 18/1000: L(Train): 0.645122766494751; L(Test): 0.6388954520225525
Epoch 19/1000: L(Train): 0.6444967985153198; L(Test): 0.6384031772613525
Epoch 20/1000: L(Train): 0.6438804864883423; L(Test): 0.6379163265228271
Epoch 21/1000: L(Train): 0.6432746052742004; L(Test): 0.637434720993042
Epoch 22/1000: L(Train): 0.6426776647567749; L(Test): 0.6369574666023254
Epoch 23/1000: L(Train): 0.6420888900756836; L(Test): 0.6364837288856506
Epoch 24/1000: L(Train): 0.6415081024169922; L(Test): 0.6360133290290833
Epoch 25/1000: L(Train): 0.64093416929245; L(Test): 0.6355454325675964
Epoch 26/1000: L(Train): 0.6403667330741882; L(Test): 0.635080099105835
Epoch 27/1000: L(Train): 0.6398046016693115; L(Test): 0.6346167325973511
Epoch 28/1000: L(Train): 0.6392484903335571; L(Test): 0.6341553926467896
Epoch 29/1000: L(Train): 0.638695240020752; L(Test): 0.6336948871612549
Epoch 30/1000: L(Train): 0.6381470561027527; L(Test): 0.6332351565361023
Epoch 31/1000: L(Train): 0.6376011371612549; L(Test): 0.6327763795852661
Epoch 32/1000: L(Train): 0.637058675289154; L(Test): 0.6323176026344299
Epoch 33/1000: L(Train): 0.6365180611610413; L(Test): 0.6318584084510803
Epoch 34/1000: L(Train): 0.635979175567627; L(Test): 0.6313974857330322
Epoch 35/1000: L(Train): 0.6354401111602783; L(Test): 0.6309354901313782
Epoch 36/1000: L(Train): 0.6349022388458252; L(Test): 0.6304711103439331
Epoch 37/1000: L(Train): 0.6343637108802795; L(Test): 0.6300044059753418
Epoch 38/1000: L(Train): 0.6338245868682861; L(Test): 0.6295339465141296
Epoch 39/1000: L(Train): 0.6332842111587524; L(Test): 0.6290599703788757
Epoch 40/1000: L(Train): 0.6327413320541382; L(Test): 0.628581702709198
Epoch 41/1000: L(Train): 0.6321964263916016; L(Test): 0.6280988454818726
Epoch 42/1000: L(Train): 0.6316483020782471; L(Test): 0.6276109218597412
Epoch 43/1000: L(Train): 0.6310964822769165; L(Test): 0.6271175742149353
Epoch 44/1000: L(Train): 0.6305406093597412; L(Test): 0.6266180872917175
Epoch 45/1000: L(Train): 0.6299799680709839; L(Test): 0.6261120438575745
Epoch 46/1000: L(Train): 0.6294142603874207; L(Test): 0.6255991458892822
Epoch 47/1000: L(Train): 0.6288425922393799; L(Test): 0.6250791549682617
Epoch 48/1000: L(Train): 0.6282644867897034; L(Test): 0.6245532035827637
Epoch 49/1000: L(Train): 0.6276830434799194; L(Test): 0.6240205764770508
Epoch 50/1000: L(Train): 0.6270955801010132; L(Test): 0.6234793663024902
Epoch 51/1000: L(Train): 0.6265014410018921; L(Test): 0.6229287385940552
Epoch 52/1000: L(Train): 0.6258988976478577; L(Test): 0.6223686337471008
Epoch 53/1000: L(Train): 0.6252873539924622; L(Test): 0.6217977404594421
Epoch 54/1000: L(Train): 0.6246668100357056; L(Test): 0.6212158203125
Epoch 55/1000: L(Train): 0.6240362524986267; L(Test): 0.6206226348876953
Epoch 56/1000: L(Train): 0.6233956217765808; L(Test): 0.6200172901153564
Epoch 57/1000: L(Train): 0.6227431893348694; L(Test): 0.6193997263908386
Epoch 58/1000: L(Train): 0.6220791935920715; L(Test): 0.6187692880630493
Epoch 59/1000: L(Train): 0.6214027404785156; L(Test): 0.6181252598762512
Epoch 60/1000: L(Train): 0.6207140684127808; L(Test): 0.6174672245979309
Epoch 61/1000: L(Train): 0.6200125217437744; L(Test): 0.6167944073677063
Epoch 62/1000: L(Train): 0.6192962527275085; L(Test): 0.6161061525344849
Epoch 63/1000: L(Train): 0.6185662746429443; L(Test): 0.6154021620750427
Epoch 64/1000: L(Train): 0.6178210973739624; L(Test): 0.6146824955940247
Epoch 65/1000: L(Train): 0.6170601844787598; L(Test): 0.6139458417892456
Epoch 66/1000: L(Train): 0.6162837743759155; L(Test): 0.6131920218467712
Epoch 67/1000: L(Train): 0.6154915690422058; L(Test): 0.6124207973480225
Epoch 68/1000: L(Train): 0.6146817207336426; L(Test): 0.6116316914558411
Epoch 69/1000: L(Train): 0.6138548851013184; L(Test): 0.6108244061470032
Epoch 70/1000: L(Train): 0.613010585308075; L(Test): 0.6099984645843506
Epoch 71/1000: L(Train): 0.6121476292610168; L(Test): 0.6091538667678833
Epoch 72/1000: L(Train): 0.6112669706344604; L(Test): 0.608290433883667
Epoch 73/1000: L(Train): 0.6103670597076416; L(Test): 0.6074076294898987
Epoch 74/1000: L(Train): 0.6094480752944946; L(Test): 0.6065050959587097
Epoch 75/1000: L(Train): 0.6085100769996643; L(Test): 0.6055830717086792
Epoch 76/1000: L(Train): 0.6075527667999268; L(Test): 0.6046414375305176
Epoch 77/1000: L(Train): 0.6065747737884521; L(Test): 0.6036797165870667
Epoch 78/1000: L(Train): 0.6055774688720703; L(Test): 0.6026980876922607
Epoch 79/1000: L(Train): 0.604560911655426; L(Test): 0.6016967296600342
Epoch 80/1000: L(Train): 0.603523850440979; L(Test): 0.6006757020950317
Epoch 81/1000: L(Train): 0.6024670004844666; L(Test): 0.5996347665786743
Epoch 82/1000: L(Train): 0.601391077041626; L(Test): 0.5985749959945679
Epoch 83/1000: L(Train): 0.6002946496009827; L(Test): 0.5974961519241333
Epoch 84/1000: L(Train): 0.5991794466972351; L(Test): 0.5963990092277527
Epoch 85/1000: L(Train): 0.5980451107025146; L(Test): 0.5952838063240051
Epoch 86/1000: L(Train): 0.5968923568725586; L(Test): 0.5941512584686279
Epoch 87/1000: L(Train): 0.5957218408584595; L(Test): 0.5930019021034241
Epoch 88/1000: L(Train): 0.5945332050323486; L(Test): 0.59183669090271
Epoch 89/1000: L(Train): 0.5933276414871216; L(Test): 0.590656042098999
Epoch 90/1000: L(Train): 0.5921064019203186; L(Test): 0.5894615054130554
Epoch 91/1000: L(Train): 0.5908694267272949; L(Test): 0.5882540345191956
Epoch 92/1000: L(Train): 0.5896179676055908; L(Test): 0.5870340466499329
Epoch 93/1000: L(Train): 0.5883527398109436; L(Test): 0.5858034491539001
Epoch 94/1000: L(Train): 0.5870750546455383; L(Test): 0.584563136100769
Epoch 95/1000: L(Train): 0.5857858657836914; L(Test): 0.5833145380020142
Epoch 96/1000: L(Train): 0.5844866037368774; L(Test): 0.5820591449737549
Epoch 97/1000: L(Train): 0.5831781625747681; L(Test): 0.5807984471321106
Epoch 98/1000: L(Train): 0.5818618535995483; L(Test): 0.579533576965332
Epoch 99/1000: L(Train): 0.5805391669273376; L(Test): 0.578266978263855
Epoch 100/1000: L(Train): 0.579211413860321; L(Test): 0.5769995450973511
Epoch 101/1000: L(Train): 0.5778800249099731; L(Test): 0.5757330656051636
Epoch 102/1000: L(Train): 0.5765467286109924; L(Test): 0.574469268321991
Epoch 103/1000: L(Train): 0.5752127766609192; L(Test): 0.5732097625732422
Epoch 104/1000: L(Train): 0.573879599571228; L(Test): 0.571956217288971
Epoch 105/1000: L(Train): 0.5725493431091309; L(Test): 0.5707105398178101
Epoch 106/1000: L(Train): 0.5712228417396545; L(Test): 0.5694743990898132
Epoch 107/1000: L(Train): 0.5699020624160767; L(Test): 0.5682491064071655
Epoch 108/1000: L(Train): 0.5685883164405823; L(Test): 0.5670360922813416
Epoch 109/1000: L(Train): 0.5672831535339355; L(Test): 0.5658372640609741
Epoch 110/1000: L(Train): 0.5659880042076111; L(Test): 0.5646532773971558
Epoch 111/1000: L(Train): 0.5647042393684387; L(Test): 0.5634863972663879
Epoch 112/1000: L(Train): 0.5634332299232483; L(Test): 0.5623371005058289
Epoch 113/1000: L(Train): 0.5621761083602905; L(Test): 0.5612064003944397
Epoch 114/1000: L(Train): 0.5609335899353027; L(Test): 0.5600955486297607
Epoch 115/1000: L(Train): 0.5597079992294312; L(Test): 0.559005618095398
Epoch 116/1000: L(Train): 0.558499276638031; L(Test): 0.5579366683959961
Epoch 117/1000: L(Train): 0.557309091091156; L(Test): 0.5568897724151611
Epoch 118/1000: L(Train): 0.5561378598213196; L(Test): 0.5558650493621826
Epoch 119/1000: L(Train): 0.554986298084259; L(Test): 0.5548633337020874
Epoch 120/1000: L(Train): 0.5538550019264221; L(Test): 0.5538845062255859
Epoch 121/1000: L(Train): 0.5527448058128357; L(Test): 0.5529285073280334
Epoch 122/1000: L(Train): 0.5516558885574341; L(Test): 0.5519958138465881
Epoch 123/1000: L(Train): 0.550588846206665; L(Test): 0.551085352897644
Epoch 124/1000: L(Train): 0.5495437979698181; L(Test): 0.550197958946228
Epoch 125/1000: L(Train): 0.5485210418701172; L(Test): 0.5493327975273132
Epoch 126/1000: L(Train): 0.547520101070404; L(Test): 0.5484892725944519
Epoch 127/1000: L(Train): 0.5465414524078369; L(Test): 0.547667384147644
Epoch 128/1000: L(Train): 0.545585036277771; L(Test): 0.5468662977218628
Epoch 129/1000: L(Train): 0.544651210308075; L(Test): 0.54608553647995
Epoch 130/1000: L(Train): 0.5437387228012085; L(Test): 0.5453246831893921
Epoch 131/1000: L(Train): 0.5428485870361328; L(Test): 0.5445829033851624
Epoch 132/1000: L(Train): 0.5419794321060181; L(Test): 0.543860137462616
Epoch 133/1000: L(Train): 0.5411314368247986; L(Test): 0.5431551337242126
Epoch 134/1000: L(Train): 0.5403047800064087; L(Test): 0.5424677729606628
Epoch 135/1000: L(Train): 0.5394983887672424; L(Test): 0.5417972803115845
Epoch 136/1000: L(Train): 0.5387117266654968; L(Test): 0.5411428809165955
Epoch 137/1000: L(Train): 0.5379450917243958; L(Test): 0.5405049920082092
Epoch 138/1000: L(Train): 0.5371981263160706; L(Test): 0.5398817658424377
Epoch 139/1000: L(Train): 0.5364698171615601; L(Test): 0.5392735004425049
Epoch 140/1000: L(Train): 0.5357598066329956; L(Test): 0.5386795401573181
Epoch 141/1000: L(Train): 0.5350679755210876; L(Test): 0.5380997657775879
Epoch 142/1000: L(Train): 0.5343939661979675; L(Test): 0.5375333428382874
Epoch 143/1000: L(Train): 0.5337371826171875; L(Test): 0.5369800329208374
Epoch 144/1000: L(Train): 0.5330970883369446; L(Test): 0.5364392995834351
Epoch 145/1000: L(Train): 0.5324732661247253; L(Test): 0.535910964012146
Epoch 146/1000: L(Train): 0.5318654179573059; L(Test): 0.5353944301605225
Epoch 147/1000: L(Train): 0.5312733054161072; L(Test): 0.5348897576332092
Epoch 148/1000: L(Train): 0.5306959748268127; L(Test): 0.5343959927558899
Epoch 149/1000: L(Train): 0.5301341414451599; L(Test): 0.5339133739471436
Epoch 150/1000: L(Train): 0.5295863151550293; L(Test): 0.5334414839744568
Epoch 151/1000: L(Train): 0.529052734375; L(Test): 0.5329803824424744
Epoch 152/1000: L(Train): 0.5285328030586243; L(Test): 0.5325292944908142
Epoch 153/1000: L(Train): 0.5280264019966125; L(Test): 0.5320882201194763
Epoch 154/1000: L(Train): 0.5275326371192932; L(Test): 0.531657338142395
Epoch 155/1000: L(Train): 0.5270518660545349; L(Test): 0.5312358140945435
Epoch 156/1000: L(Train): 0.5265834331512451; L(Test): 0.5308235287666321
Epoch 157/1000: L(Train): 0.5261269211769104; L(Test): 0.5304209589958191
Epoch 158/1000: L(Train): 0.5256823301315308; L(Test): 0.5300272107124329
Epoch 159/1000: L(Train): 0.525249183177948; L(Test): 0.5296424627304077
Epoch 160/1000: L(Train): 0.5248270630836487; L(Test): 0.5292664766311646
Epoch 161/1000: L(Train): 0.5244156122207642; L(Test): 0.528899073600769
Epoch 162/1000: L(Train): 0.5240153670310974; L(Test): 0.5285400748252869
Epoch 163/1000: L(Train): 0.5236246585845947; L(Test): 0.5281891226768494
Epoch 164/1000: L(Train): 0.5232443809509277; L(Test): 0.5278462171554565
Epoch 165/1000: L(Train): 0.52287358045578; L(Test): 0.5275110602378845
Epoch 166/1000: L(Train): 0.5225125551223755; L(Test): 0.5271835923194885
Epoch 167/1000: L(Train): 0.5221607089042664; L(Test): 0.5268636345863342
Epoch 168/1000: L(Train): 0.5218178033828735; L(Test): 0.5265506505966187
Epoch 169/1000: L(Train): 0.5214836597442627; L(Test): 0.5262448191642761
Epoch 170/1000: L(Train): 0.52115797996521; L(Test): 0.5259459018707275
Epoch 171/1000: L(Train): 0.5208402872085571; L(Test): 0.5256535410881042
Epoch 172/1000: L(Train): 0.5205309391021729; L(Test): 0.5253678560256958
Epoch 173/1000: L(Train): 0.5202288627624512; L(Test): 0.525088369846344
Epoch 174/1000: L(Train): 0.5199344754219055; L(Test): 0.5248152613639832
Epoch 175/1000: L(Train): 0.519648015499115; L(Test): 0.5245482325553894
Epoch 176/1000: L(Train): 0.5193682909011841; L(Test): 0.5242871046066284
Epoch 177/1000: L(Train): 0.5190954208374023; L(Test): 0.524031937122345
Epoch 178/1000: L(Train): 0.5188295245170593; L(Test): 0.5237822532653809
Epoch 179/1000: L(Train): 0.5185697078704834; L(Test): 0.5235382914543152
Epoch 180/1000: L(Train): 0.5183166861534119; L(Test): 0.5232995748519897
Epoch 181/1000: L(Train): 0.518069863319397; L(Test): 0.5230662822723389
Epoch 182/1000: L(Train): 0.5178288817405701; L(Test): 0.5228381156921387
Epoch 183/1000: L(Train): 0.5175939202308655; L(Test): 0.5226152539253235
Epoch 184/1000: L(Train): 0.517364501953125; L(Test): 0.522397518157959
Epoch 185/1000: L(Train): 0.517140805721283; L(Test): 0.5221845507621765
Epoch 186/1000: L(Train): 0.5169224739074707; L(Test): 0.5219767689704895
Epoch 187/1000: L(Train): 0.5167089700698853; L(Test): 0.5217737555503845
Epoch 188/1000: L(Train): 0.5165007710456848; L(Test): 0.5215752720832825
Epoch 189/1000: L(Train): 0.5162975192070007; L(Test): 0.5213814973831177
Epoch 190/1000: L(Train): 0.5160991549491882; L(Test): 0.5211923718452454
Epoch 191/1000: L(Train): 0.5159054398536682; L(Test): 0.5210076570510864
Epoch 192/1000: L(Train): 0.5157161951065063; L(Test): 0.5208269357681274
Epoch 193/1000: L(Train): 0.5155313014984131; L(Test): 0.5206509232521057
Epoch 194/1000: L(Train): 0.5153506994247437; L(Test): 0.5204789042472839
Epoch 195/1000: L(Train): 0.5151740908622742; L(Test): 0.5203109979629517
Epoch 196/1000: L(Train): 0.5150015950202942; L(Test): 0.520146906375885
Epoch 197/1000: L(Train): 0.5148325562477112; L(Test): 0.5199868083000183
Epoch 198/1000: L(Train): 0.5146676898002625; L(Test): 0.519830584526062
Epoch 199/1000: L(Train): 0.5145066380500793; L(Test): 0.5196776986122131
Epoch 200/1000: L(Train): 0.5143489837646484; L(Test): 0.5195285081863403
Epoch 201/1000: L(Train): 0.514194667339325; L(Test): 0.5193825960159302
Epoch 202/1000: L(Train): 0.5140441656112671; L(Test): 0.5192400813102722
Epoch 203/1000: L(Train): 0.5138964653015137; L(Test): 0.5191007852554321
Epoch 204/1000: L(Train): 0.5137521028518677; L(Test): 0.5189647078514099
Epoch 205/1000: L(Train): 0.5136107802391052; L(Test): 0.518831729888916
Epoch 206/1000: L(Train): 0.5134724378585815; L(Test): 0.5187016129493713
Epoch 207/1000: L(Train): 0.5133371353149414; L(Test): 0.5185742378234863
Epoch 208/1000: L(Train): 0.5132043361663818; L(Test): 0.5184497237205505
Epoch 209/1000: L(Train): 0.5130748152732849; L(Test): 0.518328070640564
Epoch 210/1000: L(Train): 0.5129474997520447; L(Test): 0.5182087421417236
Epoch 211/1000: L(Train): 0.5128228068351746; L(Test): 0.5180924534797668
Epoch 212/1000: L(Train): 0.5127012133598328; L(Test): 0.5179786682128906
Epoch 213/1000: L(Train): 0.5125816464424133; L(Test): 0.5178673267364502
Epoch 214/1000: L(Train): 0.5124645233154297; L(Test): 0.517758309841156
Epoch 215/1000: L(Train): 0.5123500227928162; L(Test): 0.5176518559455872
Epoch 216/1000: L(Train): 0.5122371315956116; L(Test): 0.517547607421875
Epoch 217/1000: L(Train): 0.5121273398399353; L(Test): 0.5174456834793091
Epoch 218/1000: L(Train): 0.5120189189910889; L(Test): 0.5173459053039551
Epoch 219/1000: L(Train): 0.5119127631187439; L(Test): 0.5172483325004578
Epoch 220/1000: L(Train): 0.5118086934089661; L(Test): 0.5171527862548828
Epoch 221/1000: L(Train): 0.5117064118385315; L(Test): 0.5170592069625854
Epoch 222/1000: L(Train): 0.5116063952445984; L(Test): 0.5169675946235657
Epoch 223/1000: L(Train): 0.5115081071853638; L(Test): 0.5168781876564026
Epoch 224/1000: L(Train): 0.5114118456840515; L(Test): 0.5167901515960693
Epoch 225/1000: L(Train): 0.5113173723220825; L(Test): 0.5167044997215271
Epoch 226/1000: L(Train): 0.5112243294715881; L(Test): 0.5166203379631042
Epoch 227/1000: L(Train): 0.511133074760437; L(Test): 0.5165379643440247
Epoch 228/1000: L(Train): 0.5110436081886292; L(Test): 0.516457200050354
Epoch 229/1000: L(Train): 0.5109556913375854; L(Test): 0.5163779854774475
Epoch 230/1000: L(Train): 0.5108695030212402; L(Test): 0.5163004398345947
Epoch 231/1000: L(Train): 0.5107848048210144; L(Test): 0.5162246227264404
Epoch 232/1000: L(Train): 0.5107016563415527; L(Test): 0.5161500573158264
Epoch 233/1000: L(Train): 0.5106199979782104; L(Test): 0.5160771608352661
Epoch 234/1000: L(Train): 0.5105395317077637; L(Test): 0.5160055160522461
Epoch 235/1000: L(Train): 0.5104606747627258; L(Test): 0.5159353613853455
Epoch 236/1000: L(Train): 0.5103833079338074; L(Test): 0.5158664584159851
Epoch 237/1000: L(Train): 0.5103070139884949; L(Test): 0.5157988667488098
Epoch 238/1000: L(Train): 0.5102320909500122; L(Test): 0.5157328844070435
Epoch 239/1000: L(Train): 0.5101586580276489; L(Test): 0.5156677961349487
Epoch 240/1000: L(Train): 0.510086178779602; L(Test): 0.5156040787696838
Epoch 241/1000: L(Train): 0.5100151896476746; L(Test): 0.5155417919158936
Epoch 242/1000: L(Train): 0.5099450945854187; L(Test): 0.5154805183410645
Epoch 243/1000: L(Train): 0.5098760724067688; L(Test): 0.5154206156730652
Epoch 244/1000: L(Train): 0.509808361530304; L(Test): 0.5153619647026062
Epoch 245/1000: L(Train): 0.5097422003746033; L(Test): 0.5153043270111084
Epoch 246/1000: L(Train): 0.5096766948699951; L(Test): 0.5152480602264404
Epoch 247/1000: L(Train): 0.5096124410629272; L(Test): 0.5151926279067993
Epoch 248/1000: L(Train): 0.5095492601394653; L(Test): 0.5151385068893433
Epoch 249/1000: L(Train): 0.509486973285675; L(Test): 0.5150853991508484
Epoch 250/1000: L(Train): 0.5094255208969116; L(Test): 0.5150332450866699
Epoch 251/1000: L(Train): 0.5093650221824646; L(Test): 0.5149820446968079
Epoch 252/1000: L(Train): 0.509306013584137; L(Test): 0.514931857585907
Epoch 253/1000: L(Train): 0.5092471241950989; L(Test): 0.5148827433586121
Epoch 254/1000: L(Train): 0.5091894865036011; L(Test): 0.5148343443870544
Epoch 255/1000: L(Train): 0.5091328620910645; L(Test): 0.5147870779037476
Epoch 256/1000: L(Train): 0.5090767741203308; L(Test): 0.514740526676178
Epoch 257/1000: L(Train): 0.5090218186378479; L(Test): 0.5146949887275696
Epoch 258/1000: L(Train): 0.508967399597168; L(Test): 0.5146501064300537
Epoch 259/1000: L(Train): 0.5089139342308044; L(Test): 0.5146061778068542
Epoch 260/1000: L(Train): 0.5088615417480469; L(Test): 0.5145631432533264
Epoch 261/1000: L(Train): 0.5088093280792236; L(Test): 0.5145207643508911
Epoch 262/1000: L(Train): 0.5087580680847168; L(Test): 0.5144792199134827
Epoch 263/1000: L(Train): 0.5087077617645264; L(Test): 0.5144383907318115
Epoch 264/1000: L(Train): 0.5086578726768494; L(Test): 0.5143982768058777
Epoch 265/1000: L(Train): 0.5086089968681335; L(Test): 0.5143589973449707
Epoch 266/1000: L(Train): 0.5085607767105103; L(Test): 0.5143203139305115
Epoch 267/1000: L(Train): 0.5085127949714661; L(Test): 0.5142822861671448
Epoch 268/1000: L(Train): 0.5084660053253174; L(Test): 0.5142450332641602
Epoch 269/1000: L(Train): 0.5084195733070374; L(Test): 0.5142083764076233
Epoch 270/1000: L(Train): 0.5083736777305603; L(Test): 0.5141719579696655
Epoch 271/1000: L(Train): 0.5083284378051758; L(Test): 0.5141369104385376
Epoch 272/1000: L(Train): 0.508284330368042; L(Test): 0.5141022205352783

In [7]:
cfs.load_state_dict(torch.load(path_cfs, map_location='cpu'))

### GRU Model

In [6]:
gru = GRUModel(
    n_actions=dataset_train.n_actions, 
    additional_inputs=2, 
    dropout=0.1,
    hidden_size=32,
    )
path_gru = path_spice.replace('spice_', 'gru_')

In [12]:
epochs = 1000
optimizer_gru = torch.optim.Adam(gru.parameters(), lr=0.01)

gru = training(
    model=gru,
    optimizer=optimizer_gru,
    dataset_train=dataset_train,
    dataset_test=dataset_test,
    epochs=epochs,
    loss_kwargs={'label_smoothing': 0.0},
    ).to(torch.device('cpu'))

torch.save(gru.state_dict(), path_gru)

Epoch 1/1000: L(Train): 0.4995410144329071; L(Test): 1.8238345384597778
Epoch 2/1000: L(Train): 1.8106528520584106; L(Test): 0.7546141743659973
Epoch 3/1000: L(Train): 0.7678055763244629; L(Test): 0.7457813620567322
Epoch 4/1000: L(Train): 0.7755215167999268; L(Test): 0.8805248141288757
Epoch 5/1000: L(Train): 0.9214949011802673; L(Test): 0.8561751842498779
Epoch 6/1000: L(Train): 0.8995146751403809; L(Test): 0.7348523736000061
Epoch 7/1000: L(Train): 0.7798618674278259; L(Test): 0.6502336263656616
Epoch 8/1000: L(Train): 0.6937047243118286; L(Test): 0.6488674283027649
Epoch 9/1000: L(Train): 0.6794036030769348; L(Test): 0.65349942445755
Epoch 10/1000: L(Train): 0.6788702011108398; L(Test): 0.6388862133026123
Epoch 11/1000: L(Train): 0.6636232733726501; L(Test): 0.6207823157310486
Epoch 12/1000: L(Train): 0.6460587978363037; L(Test): 0.6204745769500732
Epoch 13/1000: L(Train): 0.6426492929458618; L(Test): 0.6185701489448547
Epoch 14/1000: L(Train): 0.6363800168037415; L(Test): 0.6134316921234131
Epoch 15/1000: L(Train): 0.6279114484786987; L(Test): 0.6073234677314758
Epoch 16/1000: L(Train): 0.6202839612960815; L(Test): 0.5990476012229919
Epoch 17/1000: L(Train): 0.6101351380348206; L(Test): 0.5895335674285889
Epoch 18/1000: L(Train): 0.6002594232559204; L(Test): 0.5819871425628662
Epoch 19/1000: L(Train): 0.5950303673744202; L(Test): 0.5783432722091675
Epoch 20/1000: L(Train): 0.5930148363113403; L(Test): 0.5699575543403625
Epoch 21/1000: L(Train): 0.5853284597396851; L(Test): 0.5586262941360474
Epoch 22/1000: L(Train): 0.5737521052360535; L(Test): 0.5554624795913696
Epoch 23/1000: L(Train): 0.570600688457489; L(Test): 0.5539000034332275
Epoch 24/1000: L(Train): 0.5695188641548157; L(Test): 0.5486059784889221
Epoch 25/1000: L(Train): 0.5657169222831726; L(Test): 0.5448604226112366
Epoch 26/1000: L(Train): 0.5613351464271545; L(Test): 0.5440642237663269
Epoch 27/1000: L(Train): 0.5594026446342468; L(Test): 0.541330873966217
Epoch 28/1000: L(Train): 0.5535516142845154; L(Test): 0.5410082936286926
Epoch 29/1000: L(Train): 0.5522810816764832; L(Test): 0.5397841930389404
Epoch 30/1000: L(Train): 0.5498321652412415; L(Test): 0.5336980819702148
Epoch 31/1000: L(Train): 0.5445278286933899; L(Test): 0.5285427570343018
Epoch 32/1000: L(Train): 0.5393847227096558; L(Test): 0.5271177291870117
Epoch 33/1000: L(Train): 0.53810715675354; L(Test): 0.5248198509216309
Epoch 34/1000: L(Train): 0.5356113910675049; L(Test): 0.5230047106742859
Epoch 35/1000: L(Train): 0.5331356525421143; L(Test): 0.5226507186889648
Epoch 36/1000: L(Train): 0.53151935338974; L(Test): 0.5218399167060852
Epoch 37/1000: L(Train): 0.5298777222633362; L(Test): 0.5209029316902161
Epoch 38/1000: L(Train): 0.529030442237854; L(Test): 0.5190098285675049
Epoch 39/1000: L(Train): 0.5273913145065308; L(Test): 0.5165876746177673
Epoch 40/1000: L(Train): 0.5255119800567627; L(Test): 0.5156858563423157
Epoch 41/1000: L(Train): 0.5237908363342285; L(Test): 0.5144856572151184
Epoch 42/1000: L(Train): 0.523066520690918; L(Test): 0.5128413438796997
Epoch 43/1000: L(Train): 0.5205079317092896; L(Test): 0.5125826001167297
Epoch 44/1000: L(Train): 0.5201839804649353; L(Test): 0.5118346214294434
Epoch 45/1000: L(Train): 0.5186830163002014; L(Test): 0.5102120041847229
Epoch 46/1000: L(Train): 0.5177059769630432; L(Test): 0.5090914964675903
Epoch 47/1000: L(Train): 0.5172653794288635; L(Test): 0.5081415772438049
Epoch 48/1000: L(Train): 0.5159358978271484; L(Test): 0.5074449777603149
Epoch 49/1000: L(Train): 0.5149377584457397; L(Test): 0.5072422623634338
Epoch 50/1000: L(Train): 0.5144491195678711; L(Test): 0.5069249272346497
Epoch 51/1000: L(Train): 0.5133114457130432; L(Test): 0.5059661865234375
Epoch 52/1000: L(Train): 0.5126919150352478; L(Test): 0.5048537850379944
Epoch 53/1000: L(Train): 0.51189786195755; L(Test): 0.5041372179985046
Epoch 54/1000: L(Train): 0.5112506747245789; L(Test): 0.5034705996513367
Epoch 55/1000: L(Train): 0.5104444622993469; L(Test): 0.5031274557113647
Epoch 56/1000: L(Train): 0.5099136829376221; L(Test): 0.5026456117630005
Epoch 57/1000: L(Train): 0.5089485049247742; L(Test): 0.5017029643058777
Epoch 58/1000: L(Train): 0.5081051588058472; L(Test): 0.5011359453201294
Epoch 59/1000: L(Train): 0.5081058144569397; L(Test): 0.5005871057510376
Epoch 60/1000: L(Train): 0.5071848630905151; L(Test): 0.5003182888031006
Epoch 61/1000: L(Train): 0.5067740082740784; L(Test): 0.5000138282775879
Epoch 62/1000: L(Train): 0.5063371658325195; L(Test): 0.4993298053741455
Epoch 63/1000: L(Train): 0.5055635571479797; L(Test): 0.49894067645072937
Epoch 64/1000: L(Train): 0.504758358001709; L(Test): 0.49857088923454285
Epoch 65/1000: L(Train): 0.5043904781341553; L(Test): 0.4983971118927002
Epoch 66/1000: L(Train): 0.5041164755821228; L(Test): 0.4981197714805603
Epoch 67/1000: L(Train): 0.50397127866745; L(Test): 0.4975277781486511
Epoch 68/1000: L(Train): 0.5039178729057312; L(Test): 0.4971006512641907
Epoch 69/1000: L(Train): 0.5028769373893738; L(Test): 0.4968040883541107
Epoch 70/1000: L(Train): 0.5026764273643494; L(Test): 0.4966500699520111
Epoch 71/1000: L(Train): 0.5021292567253113; L(Test): 0.4962822496891022
Epoch 72/1000: L(Train): 0.5019388794898987; L(Test): 0.49584752321243286
Epoch 73/1000: L(Train): 0.5012790560722351; L(Test): 0.49555039405822754
Epoch 74/1000: L(Train): 0.5010619759559631; L(Test): 0.49537354707717896
Epoch 75/1000: L(Train): 0.5014857053756714; L(Test): 0.49519455432891846
Epoch 76/1000: L(Train): 0.5011674165725708; L(Test): 0.49484047293663025
Epoch 77/1000: L(Train): 0.500598669052124; L(Test): 0.49450671672821045
Epoch 78/1000: L(Train): 0.5002478361129761; L(Test): 0.4943036735057831
Epoch 79/1000: L(Train): 0.500618040561676; L(Test): 0.49419745802879333
Epoch 80/1000: L(Train): 0.500255286693573; L(Test): 0.4939478933811188
Epoch 81/1000: L(Train): 0.5003800392150879; L(Test): 0.4936814606189728
Epoch 82/1000: L(Train): 0.4997212886810303; L(Test): 0.49355626106262207
Epoch 83/1000: L(Train): 0.4993956387042999; L(Test): 0.49346035718917847
Epoch 84/1000: L(Train): 0.49915561079978943; L(Test): 0.4933585822582245
Epoch 85/1000: L(Train): 0.4991498291492462; L(Test): 0.4931308329105377
Epoch 86/1000: L(Train): 0.499040812253952; L(Test): 0.492889404296875
Epoch 87/1000: L(Train): 0.4991723597049713; L(Test): 0.49275410175323486
Epoch 88/1000: L(Train): 0.49828749895095825; L(Test): 0.4926474690437317
Epoch 89/1000: L(Train): 0.4982736110687256; L(Test): 0.4925127327442169
Epoch 90/1000: L(Train): 0.49843376874923706; L(Test): 0.4922388792037964
Epoch 91/1000: L(Train): 0.4983125329017639; L(Test): 0.4920174777507782
Epoch 92/1000: L(Train): 0.49825960397720337; L(Test): 0.4918821454048157
Epoch 93/1000: L(Train): 0.4978495240211487; L(Test): 0.49174797534942627
Epoch 94/1000: L(Train): 0.4977990388870239; L(Test): 0.4916347861289978
Epoch 95/1000: L(Train): 0.497640997171402; L(Test): 0.4915570616722107
Epoch 96/1000: L(Train): 0.4973445236682892; L(Test): 0.49145567417144775
Epoch 97/1000: L(Train): 0.4968722462654114; L(Test): 0.4913605749607086
Epoch 98/1000: L(Train): 0.4975091814994812; L(Test): 0.4911476671695709
Epoch 99/1000: L(Train): 0.49694424867630005; L(Test): 0.49099722504615784
Epoch 100/1000: L(Train): 0.49676966667175293; L(Test): 0.4909874498844147
Epoch 101/1000: L(Train): 0.4970523416996002; L(Test): 0.4908999800682068
Epoch 102/1000: L(Train): 0.49685725569725037; L(Test): 0.4907945692539215
Epoch 103/1000: L(Train): 0.4964873790740967; L(Test): 0.4907120168209076
Epoch 104/1000: L(Train): 0.4966029226779938; L(Test): 0.4906007647514343
Epoch 105/1000: L(Train): 0.49650049209594727; L(Test): 0.4904206097126007
Epoch 106/1000: L(Train): 0.49617472290992737; L(Test): 0.49038389325141907
Epoch 107/1000: L(Train): 0.4963184595108032; L(Test): 0.4903066158294678
Epoch 108/1000: L(Train): 0.49605581164360046; L(Test): 0.49022525548934937
Epoch 109/1000: L(Train): 0.4961380362510681; L(Test): 0.4901653528213501
Epoch 110/1000: L(Train): 0.49581024050712585; L(Test): 0.4900784194469452
Epoch 111/1000: L(Train): 0.49612537026405334; L(Test): 0.48998817801475525
Epoch 112/1000: L(Train): 0.4959658980369568; L(Test): 0.4899975061416626
Epoch 113/1000: L(Train): 0.4957660734653473; L(Test): 0.48991307616233826
Epoch 114/1000: L(Train): 0.49570485949516296; L(Test): 0.4897625148296356
Epoch 115/1000: L(Train): 0.495536744594574; L(Test): 0.4896957576274872
Epoch 116/1000: L(Train): 0.4955262839794159; L(Test): 0.4897220730781555
Epoch 117/1000: L(Train): 0.4955160915851593; L(Test): 0.4895005524158478
Epoch 118/1000: L(Train): 0.49541670083999634; L(Test): 0.48951128125190735
Epoch 119/1000: L(Train): 0.4958375096321106; L(Test): 0.48953133821487427
Epoch 120/1000: L(Train): 0.495353639125824; L(Test): 0.48940572142601013
Epoch 121/1000: L(Train): 0.4948965013027191; L(Test): 0.48934295773506165
Epoch 122/1000: L(Train): 0.4951785206794739; L(Test): 0.4893042743206024
Epoch 123/1000: L(Train): 0.4946991503238678; L(Test): 0.4891831874847412
Epoch 124/1000: L(Train): 0.4948170483112335; L(Test): 0.48913753032684326
Epoch 125/1000: L(Train): 0.49428755044937134; L(Test): 0.48913484811782837
Epoch 126/1000: L(Train): 0.49479955434799194; L(Test): 0.4890611469745636
Epoch 127/1000: L(Train): 0.4946863055229187; L(Test): 0.48896917700767517
Epoch 128/1000: L(Train): 0.4944438636302948; L(Test): 0.48893290758132935
Epoch 129/1000: L(Train): 0.49471449851989746; L(Test): 0.4889647364616394
Epoch 130/1000: L(Train): 0.4945165514945984; L(Test): 0.4889649450778961
Epoch 131/1000: L(Train): 0.4944285452365875; L(Test): 0.4888697564601898
Epoch 132/1000: L(Train): 0.4943424165248871; L(Test): 0.48874229192733765
Epoch 133/1000: L(Train): 0.4947083592414856; L(Test): 0.4886426329612732
Epoch 134/1000: L(Train): 0.4944392144680023; L(Test): 0.48862653970718384
Epoch 135/1000: L(Train): 0.4942379593849182; L(Test): 0.4885922372341156
Epoch 136/1000: L(Train): 0.49425625801086426; L(Test): 0.48851704597473145
Epoch 137/1000: L(Train): 0.49432501196861267; L(Test): 0.4884454905986786
Epoch 138/1000: L(Train): 0.4940129220485687; L(Test): 0.4884297847747803
Epoch 139/1000: L(Train): 0.49402186274528503; L(Test): 0.4884748160839081
Epoch 140/1000: L(Train): 0.4945198893547058; L(Test): 0.48839396238327026
Epoch 141/1000: L(Train): 0.49360334873199463; L(Test): 0.4883610010147095
Epoch 142/1000: L(Train): 0.4939757287502289; L(Test): 0.4882902503013611
Epoch 143/1000: L(Train): 0.493765264749527; L(Test): 0.4883132576942444
Epoch 144/1000: L(Train): 0.4939967691898346; L(Test): 0.4881751537322998
Epoch 145/1000: L(Train): 0.49378636479377747; L(Test): 0.48822417855262756
Epoch 146/1000: L(Train): 0.49379003047943115; L(Test): 0.4882160723209381
Epoch 147/1000: L(Train): 0.49375295639038086; L(Test): 0.48801931738853455
Epoch 148/1000: L(Train): 0.493958443403244; L(Test): 0.48815616965293884
Epoch 149/1000: L(Train): 0.4934254288673401; L(Test): 0.487946480512619
Epoch 150/1000: L(Train): 0.4932801127433777; L(Test): 0.4879566729068756
Epoch 151/1000: L(Train): 0.4939177632331848; L(Test): 0.48812243342399597
Epoch 152/1000: L(Train): 0.4934768080711365; L(Test): 0.4879411458969116
Epoch 153/1000: L(Train): 0.4937427341938019; L(Test): 0.487896203994751
Epoch 154/1000: L(Train): 0.4935024380683899; L(Test): 0.4879477918148041
Epoch 155/1000: L(Train): 0.4933643937110901; L(Test): 0.48775890469551086
Epoch 156/1000: L(Train): 0.4935513436794281; L(Test): 0.487884521484375
Epoch 157/1000: L(Train): 0.493064284324646; L(Test): 0.48783233761787415
Epoch 158/1000: L(Train): 0.49292609095573425; L(Test): 0.4877409338951111
Epoch 159/1000: L(Train): 0.493411123752594; L(Test): 0.4876668155193329
Epoch 160/1000: L(Train): 0.49354714155197144; L(Test): 0.4877195954322815
Epoch 161/1000: L(Train): 0.4928593933582306; L(Test): 0.4877369999885559
Epoch 162/1000: L(Train): 0.4930715560913086; L(Test): 0.4877222180366516
Epoch 163/1000: L(Train): 0.4927002787590027; L(Test): 0.4875777065753937
Epoch 164/1000: L(Train): 0.49261024594306946; L(Test): 0.48749154806137085
Epoch 165/1000: L(Train): 0.49309444427490234; L(Test): 0.4875181317329407
Epoch 166/1000: L(Train): 0.4924110770225525; L(Test): 0.4874747097492218
Epoch 167/1000: L(Train): 0.49265798926353455; L(Test): 0.4875028729438782
Epoch 168/1000: L(Train): 0.4926784932613373; L(Test): 0.48742082715034485
Epoch 169/1000: L(Train): 0.4930095076560974; L(Test): 0.48721620440483093
Epoch 170/1000: L(Train): 0.49288150668144226; L(Test): 0.487362265586853
Epoch 171/1000: L(Train): 0.49284106492996216; L(Test): 0.48744305968284607
Epoch 172/1000: L(Train): 0.4927559196949005; L(Test): 0.4873524308204651
Epoch 173/1000: L(Train): 0.49281829595565796; L(Test): 0.48734965920448303
Epoch 174/1000: L(Train): 0.49292513728141785; L(Test): 0.4871945381164551
Epoch 175/1000: L(Train): 0.49263304471969604; L(Test): 0.48772209882736206
Epoch 176/1000: L(Train): 0.4924625754356384; L(Test): 0.48734673857688904
Epoch 177/1000: L(Train): 0.4927283525466919; L(Test): 0.48738399147987366
Epoch 178/1000: L(Train): 0.49256378412246704; L(Test): 0.4870530068874359
Epoch 179/1000: L(Train): 0.492342472076416; L(Test): 0.4870142340660095
Epoch 180/1000: L(Train): 0.4922739863395691; L(Test): 0.4874955415725708
Epoch 181/1000: L(Train): 0.49276411533355713; L(Test): 0.48707231879234314
Epoch 182/1000: L(Train): 0.4927353262901306; L(Test): 0.4876316785812378
Epoch 183/1000: L(Train): 0.4922109842300415; L(Test): 0.48704928159713745
Epoch 184/1000: L(Train): 0.4920114278793335; L(Test): 0.4872901737689972
Epoch 185/1000: L(Train): 0.4923226535320282; L(Test): 0.4869987964630127
Epoch 186/1000: L(Train): 0.49194806814193726; L(Test): 0.48691579699516296
Epoch 187/1000: L(Train): 0.4921375513076782; L(Test): 0.4872809052467346
Epoch 188/1000: L(Train): 0.49224168062210083; L(Test): 0.48691490292549133
Epoch 189/1000: L(Train): 0.49218618869781494; L(Test): 0.48731398582458496
Epoch 190/1000: L(Train): 0.4919990301132202; L(Test): 0.4866846203804016
Epoch 191/1000: L(Train): 0.4921267628669739; L(Test): 0.48700207471847534
Epoch 192/1000: L(Train): 0.4920598566532135; L(Test): 0.48672109842300415
Epoch 193/1000: L(Train): 0.49151578545570374; L(Test): 0.4867769479751587
Epoch 194/1000: L(Train): 0.4919836223125458; L(Test): 0.4868386685848236
Epoch 195/1000: L(Train): 0.49213048815727234; L(Test): 0.4865874648094177
Epoch 196/1000: L(Train): 0.4920462369918823; L(Test): 0.48735296726226807
Epoch 197/1000: L(Train): 0.4922301173210144; L(Test): 0.4868588149547577
Epoch 198/1000: L(Train): 0.4926648437976837; L(Test): 0.48791420459747314
Epoch 199/1000: L(Train): 0.4925116300582886; L(Test): 0.48710912466049194
Epoch 200/1000: L(Train): 0.4925970435142517; L(Test): 0.48747381567955017
Epoch 201/1000: L(Train): 0.4918515682220459; L(Test): 0.4865339398384094
Epoch 202/1000: L(Train): 0.4915784001350403; L(Test): 0.4868079721927643
Epoch 203/1000: L(Train): 0.49198466539382935; L(Test): 0.4868832528591156
Epoch 204/1000: L(Train): 0.49173352122306824; L(Test): 0.4865235686302185
Epoch 205/1000: L(Train): 0.4919210374355316; L(Test): 0.48698243498802185
Epoch 206/1000: L(Train): 0.49211594462394714; L(Test): 0.48655277490615845
Epoch 207/1000: L(Train): 0.49187397956848145; L(Test): 0.48709025979042053
Epoch 208/1000: L(Train): 0.4920177161693573; L(Test): 0.48640409111976624
Epoch 209/1000: L(Train): 0.4918142855167389; L(Test): 0.4867149889469147
Epoch 210/1000: L(Train): 0.4917619526386261; L(Test): 0.48645251989364624
Epoch 211/1000: L(Train): 0.49182507395744324; L(Test): 0.48680946230888367
Epoch 212/1000: L(Train): 0.4911978840827942; L(Test): 0.48644962906837463
Epoch 213/1000: L(Train): 0.4915032386779785; L(Test): 0.4869701564311981
Epoch 214/1000: L(Train): 0.49215787649154663; L(Test): 0.486285537481308
Epoch 215/1000: L(Train): 0.4918612241744995; L(Test): 0.4868459105491638
Epoch 216/1000: L(Train): 0.4914589524269104; L(Test): 0.48637983202934265
Epoch 217/1000: L(Train): 0.4914376139640808; L(Test): 0.486634761095047
Epoch 218/1000: L(Train): 0.49160486459732056; L(Test): 0.48621904850006104
Epoch 219/1000: L(Train): 0.49173426628112793; L(Test): 0.4862791895866394
Epoch 220/1000: L(Train): 0.4912658631801605; L(Test): 0.4867702126502991
Epoch 221/1000: L(Train): 0.49134311079978943; L(Test): 0.48628613352775574
Epoch 222/1000: L(Train): 0.4918796122074127; L(Test): 0.4867956042289734
Epoch 223/1000: L(Train): 0.49166756868362427; L(Test): 0.48636531829833984
Epoch 224/1000: L(Train): 0.4915658235549927; L(Test): 0.4869909882545471
Epoch 225/1000: L(Train): 0.49161583185195923; L(Test): 0.48636871576309204
Epoch 226/1000: L(Train): 0.4913671016693115; L(Test): 0.48644909262657166
Epoch 227/1000: L(Train): 0.4913150668144226; L(Test): 0.48610854148864746
Epoch 228/1000: L(Train): 0.49176329374313354; L(Test): 0.48623284697532654
Epoch 229/1000: L(Train): 0.49184155464172363; L(Test): 0.48610371351242065
Epoch 230/1000: L(Train): 0.49129465222358704; L(Test): 0.4860437512397766
Epoch 231/1000: L(Train): 0.4913286864757538; L(Test): 0.48621222376823425
Epoch 232/1000: L(Train): 0.4909480810165405; L(Test): 0.48618295788764954
Epoch 233/1000: L(Train): 0.49109071493148804; L(Test): 0.4862493872642517
Epoch 234/1000: L(Train): 0.4911414384841919; L(Test): 0.4863293170928955
Epoch 235/1000: L(Train): 0.4911242127418518; L(Test): 0.4862077832221985
Epoch 236/1000: L(Train): 0.4914858937263489; L(Test): 0.48644986748695374
Epoch 237/1000: L(Train): 0.4915756583213806; L(Test): 0.4865463376045227
Epoch 238/1000: L(Train): 0.4918716549873352; L(Test): 0.4875243604183197
Epoch 239/1000: L(Train): 0.49143800139427185; L(Test): 0.48732155561447144
Epoch 240/1000: L(Train): 0.49288007616996765; L(Test): 0.48921138048171997
Epoch 241/1000: L(Train): 0.49425172805786133; L(Test): 0.48807293176651
Epoch 242/1000: L(Train): 0.49366384744644165; L(Test): 0.4880581498146057
Epoch 243/1000: L(Train): 0.49254903197288513; L(Test): 0.4859474301338196
Epoch 244/1000: L(Train): 0.4912666976451874; L(Test): 0.4861859977245331
Epoch 245/1000: L(Train): 0.4909510612487793; L(Test): 0.48710542917251587
Epoch 246/1000: L(Train): 0.4920825660228729; L(Test): 0.48743942379951477
Epoch 247/1000: L(Train): 0.492423415184021; L(Test): 0.48756372928619385
Epoch 248/1000: L(Train): 0.4926239848136902; L(Test): 0.48729661107063293
Epoch 249/1000: L(Train): 0.4920119047164917; L(Test): 0.4867075979709625
Epoch 250/1000: L(Train): 0.4922035336494446; L(Test): 0.48891231417655945
Epoch 251/1000: L(Train): 0.4935261607170105; L(Test): 0.48748278617858887
Epoch 252/1000: L(Train): 0.4931948482990265; L(Test): 0.4882194995880127
Epoch 253/1000: L(Train): 0.49264922738075256; L(Test): 0.48586058616638184
Epoch 254/1000: L(Train): 0.4913766384124756; L(Test): 0.48588037490844727
Epoch 255/1000: L(Train): 0.4905265271663666; L(Test): 0.4868355691432953
Epoch 256/1000: L(Train): 0.49144604802131653; L(Test): 0.4861307740211487
Epoch 257/1000: L(Train): 0.4919290244579315; L(Test): 0.4869113564491272
Epoch 258/1000: L(Train): 0.4917675852775574; L(Test): 0.4864440858364105
Epoch 259/1000: L(Train): 0.49144095182418823; L(Test): 0.48697349429130554
Epoch 260/1000: L(Train): 0.4916781187057495; L(Test): 0.48725494742393494
Epoch 261/1000: L(Train): 0.49124717712402344; L(Test): 0.4861578047275543
Epoch 262/1000: L(Train): 0.4913575351238251; L(Test): 0.4856785535812378
Epoch 263/1000: L(Train): 0.4903125464916229; L(Test): 0.4860532581806183
Epoch 264/1000: L(Train): 0.4905683398246765; L(Test): 0.48632335662841797
Epoch 265/1000: L(Train): 0.49161478877067566; L(Test): 0.4865543842315674
Epoch 266/1000: L(Train): 0.4908997118473053; L(Test): 0.485882967710495
Epoch 267/1000: L(Train): 0.49078723788261414; L(Test): 0.4855339527130127
Epoch 268/1000: L(Train): 0.49015775322914124; L(Test): 0.4862324595451355
Epoch 269/1000: L(Train): 0.4906977713108063; L(Test): 0.48574477434158325
Epoch 270/1000: L(Train): 0.4902513921260834; L(Test): 0.48607146739959717

In [9]:
gru.load_state_dict(torch.load(path_gru, map_location='cpu'))

# ANALYSIS

In [8]:
from weinhardt2026.analysis.analysis_model_evaluation import analysis_model_evaluation
from weinhardt2026.analysis.analysis_coefficients_distributions import analysis_coefficients_distributions
from weinhardt2026.analysis.analysis_coefficients_individuals import analysis_coefficients_individuals
from analysis_generative import analysis_generative_behavior

## General Analysis

In [15]:
# Dataset-specific behavioral analysis placeholder.
# Replace with Eckstein2024-specific columns if needed.

In [ ]:
print("Fitted Castro2025 parameters:")
print("\nBeta_r")
print(cfs.beta_r)
print("\nLapse")
print(cfs.lapse)
print("\nPrior")
print(cfs.prior)
print("\nAlpha exploration rate")
print(cfs.alpha_exploration_rate)
print("\nDecay rate")
print(cfs.decay_rate)
print("\nGamma")
print(cfs.gamma)
print("\nTemperature")
print(cfs.temperature)

## Analysis Model Evaluation

In [14]:
analysis_model_evaluation(
    dataset=dataset_train,
    # spice_model=estimator,
    benchmark_model=cfs.to(torch.device('cpu')),
    gru_model=gru.eval().to(torch.device('cpu')),
    )

Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...

,Trial Lik.,(std),n_parameters,(std),NLL,AIC,BIC
Benchmark,0.620472,0.158088,13.0,0.0,233184.984375,466395.96875,466540.250
GRU,0.627344,0.156140,6852.0,0.0,227803.765625,469311.53125,545363.625
SPICE-RNN,1.000000,0.000000,NaN,0.0,0.000000,0.00000,0.000
SPICE,1.000000,0.000000,NaN,0.0,0.000000,0.00000,0.000

In [13]:
analysis_model_evaluation(
    dataset=dataset_test,
    # spice_model=estimator,
    benchmark_model=cfs.to(torch.device('cpu')),
    gru_model=gru.eval().to(torch.device('cpu')),
    )

Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...

,Trial Lik.,(std),n_parameters,(std),NLL,AIC,BIC
Benchmark,0.599315,0.160264,13.0,0.0,65452.593750,130931.187500,131058.046875
GRU,0.618730,0.157360,6852.0,0.0,61376.554688,136457.109375,203322.843750
SPICE-RNN,1.000000,0.000000,NaN,0.0,0.000000,0.000000,0.000000
SPICE,1.000000,0.000000,NaN,0.0,0.000000,0.000000,0.000000

## Analysis coefficient distributions

In [ ]:
analysis_coefficients_distributions(
    spice_model=estimator,
    output_dir='results',
)

## Analysis Individual Differences

In [ ]:
# analysis_coefficients_individuals(
#     criterion="SomeCriterionColumnInYourDataset",
#     analysis="disc",  # also: "cont"
#     reference="ReferenceGroupFromCriterionColumn",  # only necessary if analysis="disc"
    
#     path_data=path_file,
    
#     spice_model=estimator,
    
#     dir_output='results',
# )

## Generative Behavior Analysis

In [ ]:
estimator.eval()
generate_behavior(
    model=estimator,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_spice.csv'
)

estimator.use_sindy(False)
generate_behavior(
    model=estimator,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_spice_rnn.csv'
)

gru.eval()
generate_behavior(
    model=gru,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_gru.csv'
)

generate_behavior(
    model=cfs,
    dataset=dataset_train,
    save_dataset='data/eckstein2024_cfs.csv'
)

In [ ]:
analysis_generative_behavior(
    path_data_real=path_data,
    path_data_gru='data/eckstein2024_gru.csv',
    path_data_benchmark='data/eckstein2024_cfs.csv',
    path_data_spice='data/eckstein2024_spice.csv',
    path_data_spice_rnn='data/eckstein2024_spice_rnn.csv',
    output_dir='results',
)