In [ ]:
#!git clone https://github.com/whyhardt/SPICE.git

In [ ]:
# !pip install -e SPICE

In [5]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from spice import SpiceEstimator, SpiceConfig, csv_to_dataset, BaseModel, plot_session, split_data_along_sessiondim

sys.path.append('../../..')
from weinhardt2026.utils.benchmarking_gru import Model as GRU, training
from weinhardt2026.studies.braun2018.benchmarking_braun2018 import ExpectedValueControl

# For custom RNN
import torch
import torch.nn as nn

# NOTEBOOK CONFIG

In [48]:
train_spice = False
train_evc = False
train_gru = True

# DATASET

## Load dataset

Let's load the data first with the `convert_dataset` method. This method returns a `SpiceDataset` object which we can use right away

In [51]:
# Load your data
path_file = '../data/braun2018/braun2018_2.csv'

# dataset description from github: 
# subject -- subject ID 
# rsi -- response-stimulus interval, how long points were visible before stimulus onset
# block -- position in the experiment (out of 12)
# block_c -- same as above except the distribution is centered at block 6 (total number of blocks = 12)
# blocktime -- amount of time it took to complete a given block
# trial -- each row represents one trial
# current -- factor var representing whether the value of the task performed on previous trial changed (1 = decrease by a point, 0 = remained constant)
# other -- same as ^ except represents value changes for task not performed on previous trial and (1 = increase by a point, 0 = remain constant)
# difference -- difference between values on present trial (other - current; pos values indicate difference in favor of other task)
# stim.rep -- did the stimulus repeat from the previous trial
# pvsum -- sum of points
# rt -- amount of time between stimulus onset and response on present trial
# transcode -- task selection at trial N relative to selection at trial N-1 (1 = switched to the opposite task, 0 = repeated same task)

dataset = csv_to_dataset(
    file = path_file,
    df_participant_id='subject',
    df_choice='transcode',
    df_feedback=None,
    df_block='block',
    additional_inputs=('difference', 'current', 'other'),
    timeshift_additional_inputs=(-1, -1, -1),
    )

n_participants = len(dataset.xs[..., -1].unique())
n_actions = dataset.ys.shape[-1]

print(f"Shape of dataset: {dataset.xs.shape}")
print(f"Number of participants: {n_participants}")
print(f"Number of actions in dataset: {n_actions}")
print(f"Number of additional inputs: {dataset.xs.shape[-1]-2*n_actions-5}")

Shape of dataset: torch.Size([756, 274, 1, 10])
Number of participants: 63
Number of actions in dataset: 2
Number of additional inputs: 1

## Dataset processing

In [52]:
# seems like there are a few blocks that are way longer than the average block
# maybe limiting the block length to a given size would help
n_trials_per_block = np.zeros(dataset.xs.shape[0])
for index, block in enumerate(dataset.xs[:, :, 0, 0]):
    n_trials_per_block[index] = block.shape[0]-block.isnan().sum()

mean, std = n_trials_per_block.mean(), n_trials_per_block.std()

print(f"Average sequence length: {int(mean)}+-{int(std)}")
print(f"Old max sequence length is {dataset.xs.shape[1]}")

# it would be okay to limit until ca mean+2*std trials per  (~200 trials)
dataset.xs = dataset.xs[:, :int(mean+2*std)]
dataset.ys = dataset.ys[:, :int(mean+2*std)]

print(f"New max sequence length is {dataset.xs.shape[1]}")

Average sequence length: 66+-38
Old max sequence length is 274
New max sequence length is 143

In [53]:
dataset_train, dataset_test = split_data_along_sessiondim(dataset, list_test_sessions=[3, 6, 9])

print(f"Number of training sessions: {dataset_train.xs.shape[0]}")
print(f"Number of test sessions: {dataset_test.xs.shape[0]}")

Number of training sessions: 567
Number of test sessions: 189

# SPICE

## SPICE Setup

Thoughts on SPICE architecture:

1. Reward and Effort sensitivity -> Separate values for reward and effort
2. Include effort levels for both tasks
3. Item-Space -> Task-Space -> Enables tracking task-individual values (e.g. some people might find easier to say color and others prefer form) 
4. Action-Space -> Repeat/Switch or specific Task-Selection?
5. Include separate module for repeat/switch bias -> May be unncessary because could be encoded already in effort modules
6. Include previous response time as input to repeat/switch bias
7. Account for length of experiment as cognitive control becomes more costly over time i.e. blocks ("We predict that the indifference point will increase as the experiment progresses")
8. Check whether state-less implementation makes sense -> Everything is given in cues (rewards for each task; effort levels could be directly predicted using last n actions) vs state-based dynamical model (evolution of effort/reward values over trials)

On repeat/switch bias:

"control becomes increasingly costly as it is exerted for a longer period of time" - Braun (2018)
-> Switching to keep optimal reward strength cannot be done over an extended period
-> Repeat/Switch ratio is probabily very unbalanced while Task-Ratio should be more or less counterbalanced -> **Benefit of acting on Task-Space instead of Repeat/Switch-Space**

Now we are going to define the configuration for SPICE with a `SpiceConfig` object.

The `SpiceConfig` takes as arguments 
1. `library_setup (dict)`: Defining the variable names of each module.
2. `memory_state (dict)`: Defining the memory state variables and their initial values.
3. `states_in_logit (list)`: Defining which of the memory state variables are used later for the logit computation. This is necessary for some background processes.

In [9]:
spice_config = SpiceConfig(
    library_setup={
        'reward_repeat': (
            'dreward_tasks', 
            # 'dreward_trials_repeat',
            # 'dreward_trials_switch',
            ),
        'reward_switch': (
            'dreward_tasks',
            # 'dreward_trials_repeat',
            # 'dreward_trials_switch', 
            ),
        'task_repeat': (
            'repeat',
            ),
        'task_switch': (
            'repeat',
            ),
        'fatigue_repeat': (
            'block',
            ),
        'fatigue_switch': (
            'block',
            ),
    },
    memory_state={
        'value_reward': 0,
        'value_control': 0,
        'value_fatigue': 0,
    },
)

And now we are going to define the SPICE model which is a child of the `BaseModel` and `torch.nn.Module` class and takes as required arguments:
1. `spice_config (SpiceConfig)`: previously defined SpiceConfig object
2. `n_actions (int)`: number of possible actions in your dataset (including non-displayed ones if applicable).
3. `n_participants (int)`: number of participants in your dataset.

As usual for a `torch.nn.Module` we have to define at least the `__init__` method and the `forward` method.
The `forward` method gets called when computing a forward pass through the model and takes as inputs `(inputs (SpiceDataset.xs), prev_state (dict, default: None), batch_first (bool, default: False))` and returns `(logits (torch.Tensor, shape: (n_participants*n_blocks*n_experiments, timesteps, n_actions)), updated_state (dict))`. Two necessary method calls inside the forward pass are:
1. `self.init_forward_pass(inputs, prev_state, batch_first) -> SpiceSignals`: returns a `SpiceSignals` object which carries all relevant information already processed.
2. `self.post_forward_pass(SpiceSignals, batch_first) -> SpiceSignals`: does some re-arranging of the logits to adhere to `batch_first`.

In [54]:
class SpiceModel(BaseModel):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
        dropout = 0.1
        self.n_blocks = 12
        
        self.participant_embedding = self.setup_embedding(num_embeddings=self.n_participants, embedding_size=self.embedding_size, dropout=dropout)
        
        self.setup_module(key_module='reward_repeat', input_size=1 + self.embedding_size, dropout=dropout, include_state=False)
        self.setup_module(key_module='reward_switch', input_size=1 + self.embedding_size, dropout=dropout, include_state=False)
        self.setup_module(key_module='task_repeat', input_size=1 + self.embedding_size, dropout=dropout)
        self.setup_module(key_module='task_switch', input_size=1 + self.embedding_size, dropout=dropout)
        self.setup_module(key_module='fatigue_repeat', input_size=1 + self.embedding_size, dropout=dropout, include_state=False)        
        self.setup_module(key_module='fatigue_switch', input_size=1 + self.embedding_size, dropout=dropout, include_state=False)        
        
    def forward(self, inputs, prev_state=None, batch_first=True):
        
        spice_signals = self.init_forward_pass(inputs, prev_state, batch_first)
        
        dreward_tasks_current = -spice_signals.additional_inputs[..., 0].unsqueeze(-1).expand_as(spice_signals.actions)
        dreward_tasks_other = spice_signals.additional_inputs[..., 0].unsqueeze(-1).expand_as(spice_signals.actions)
        dreward_trials_current = spice_signals.additional_inputs[..., 1].unsqueeze(-1).expand_as(spice_signals.actions)
        dreward_trials_other = spice_signals.additional_inputs[..., 2].unsqueeze(-1).expand_as(spice_signals.actions)
        # rt = spice_signals.additional_inputs[..., 3].unsqueeze(-1).expand_as(spice_signals.actions)
        blocks = spice_signals.blocks.unsqueeze(0).unsqueeze(-1).expand_as(spice_signals.actions[0]) / self.n_blocks
        
        repeat = torch.zeros_like(spice_signals.actions)
        repeat += spice_signals.actions[..., :1]
        switch = torch.zeros_like(spice_signals.actions)
        switch += spice_signals.actions[..., 1:2]
        
        repeat_mask = torch.zeros_like(spice_signals.actions[0])
        repeat_mask[..., 0] = 1
        switch_mask = torch.zeros_like(spice_signals.actions[0])
        switch_mask[..., 1] = 1
        
        participant_embedding = self.participant_embedding(spice_signals.participant_ids)
        
        for trial in spice_signals.trials:
            
            # modules for reward perception
            value_reward_repeat = self.call_module(
                key_module='reward_repeat',
                # key_state='value_reward',
                action_mask=repeat_mask,
                inputs=dreward_tasks_current[trial],
                participant_index=spice_signals.participant_ids,
                participant_embedding=participant_embedding,
            )
            value_reward_switch = self.call_module(
                key_module='reward_switch',
                # key_state='value_reward',
                action_mask=switch_mask,
                inputs=dreward_tasks_other[trial],
                participant_index=spice_signals.participant_ids,
                participant_embedding=participant_embedding,
            )
            
            # modules to update switching costs
            self.call_module(
                key_module='task_repeat',
                key_state='value_control',
                action_mask=repeat_mask,
                inputs=repeat[trial],
                participant_index=spice_signals.participant_ids,
                participant_embedding=participant_embedding,
            )
            self.call_module(
                key_module='task_switch',
                key_state='value_control',
                action_mask=switch_mask,
                inputs=repeat[trial],
                participant_index=spice_signals.participant_ids,
                participant_embedding=participant_embedding,
            )
            
            # module to update fatigue value based on current block number
            value_fatigue_repeat = self.call_module(
                key_module='fatigue_repeat',
                # key_state='value_fatigue',
                action_mask=repeat_mask,
                inputs=blocks,
                participant_index=spice_signals.participant_ids,
                participant_embedding=participant_embedding,
            )
            value_fatigue_switch = self.call_module(
                key_module='fatigue_switch',
                # key_state='value_fatigue',
                action_mask=switch_mask,
                inputs=blocks,
                participant_index=spice_signals.participant_ids,
                participant_embedding=participant_embedding,
            )
            
            # compute logits
            spice_signals.logits[trial] = (
                value_reward_repeat+value_reward_switch
                + self.state['value_control'] 
                + value_fatigue_repeat+value_fatigue_switch
                )
        
        spice_signals = self.post_forward_pass(spice_signals, batch_first)
        return spice_signals.logits, self.state

Let's setup now the `SpiceEstimator` object and fit it to the data!

In [55]:
path_spice = '../params/braun2018/spice_braun2018.pkl'

estimator = SpiceEstimator(
        # model paramaeters
        spice_class=SpiceModel,
        spice_config=spice_config,
        n_actions=2,
        n_participants=n_participants,
        n_experiments=1,
        n_reward_features=0,
        
        epochs=1000,
        warmup_steps=200,
        ensemble_size=10,
        
        sindy_weight=0.1,
        sindy_alpha=0.0001,
        sindy_pruning_frequency=100,
        sindy_threshold_pruning=0.01,
        sindy_ensemble_pruning=0.05,
        sindy_library_polynomial_degree=2,
        
        sindy_refit=False,
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu'),
        verbose=True,
        save_path_spice=path_spice,
    )

In [56]:
if train_spice:
    estimator.fit(dataset_train.xs, dataset_train.ys, dataset_test.xs, dataset_test.ys)

In [57]:
estimator.load_spice(path_spice)

# BENCHMARKING

### Expected Value of Control Model (Shenhav et al., 2013)

In [59]:
evc = ExpectedValueControl(n_participants=n_participants)
path_evc = path_spice.replace('spice_', 'evc_')

In [60]:
if train_evc:
    optimizer_evc = torch.optim.Adam(evc.parameters(), lr=0.01)
    epochs = 1000

    evc = training(
        model=evc,
        optimizer=optimizer_evc,
        dataset_train=dataset_train,
        dataset_test=dataset_test,
        epochs=epochs,
        device=torch.device('cpu'),
    )

    torch.save(evc.state_dict(), path_evc)

In [61]:
evc.load_state_dict(torch.load(path_evc, map_location='cpu'))

### GRU Model

In [62]:
gru = GRU(n_actions, additional_inputs=4, n_reward_features=0)
path_gru = path_spice.replace('spice_', 'gru_')

In [63]:
if train_gru:
    epochs = 1000
    optimizer_gru = torch.optim.Adam(gru.parameters(), lr=0.01)

    gru = training(
        model=gru.to(torch.device('cuda' if torch.cuda.is_available() else 'cpu')),
        optimizer=optimizer_gru,
        dataset_train=dataset_train,
        dataset_test=dataset_test,
        epochs=epochs,
        ).to(torch.device('cpu'))

    torch.save(gru.state_dict(), path_gru)

Epoch 1/1000: L(Train): 0.7022228240966797; L(Test): 0.6754243969917297
Epoch 2/1000: L(Train): 0.6724429726600647; L(Test): 0.6668117046356201
Epoch 3/1000: L(Train): 0.659993052482605; L(Test): 0.6607396602630615
Epoch 4/1000: L(Train): 0.6520838737487793; L(Test): 0.6507664918899536
Epoch 5/1000: L(Train): 0.6422415375709534; L(Test): 0.6377213597297668
Epoch 6/1000: L(Train): 0.6302168369293213; L(Test): 0.624111533164978
Epoch 7/1000: L(Train): 0.6184144616127014; L(Test): 0.6117025017738342
Epoch 8/1000: L(Train): 0.6076127886772156; L(Test): 0.6004595160484314
Epoch 9/1000: L(Train): 0.5979776978492737; L(Test): 0.5886890292167664
Epoch 10/1000: L(Train): 0.5867869257926941; L(Test): 0.5754860639572144
Epoch 11/1000: L(Train): 0.5726652145385742; L(Test): 0.5621552467346191
Epoch 12/1000: L(Train): 0.5577712059020996; L(Test): 0.5503264665603638
Epoch 13/1000: L(Train): 0.5460419654846191; L(Test): 0.5382659435272217
Epoch 14/1000: L(Train): 0.5335555076599121; L(Test): 0.5240161418914795
Epoch 15/1000: L(Train): 0.5200096964836121; L(Test): 0.5120667815208435
Epoch 16/1000: L(Train): 0.5093467831611633; L(Test): 0.5063241720199585
Epoch 17/1000: L(Train): 0.5038663744926453; L(Test): 0.5009855628013611
Epoch 18/1000: L(Train): 0.49680590629577637; L(Test): 0.4969628155231476
Epoch 19/1000: L(Train): 0.49349871277809143; L(Test): 0.49347352981567383
Epoch 20/1000: L(Train): 0.49051031470298767; L(Test): 0.4877222776412964
Epoch 21/1000: L(Train): 0.48503750562667847; L(Test): 0.48459455370903015
Epoch 22/1000: L(Train): 0.48240819573402405; L(Test): 0.48382580280303955
Epoch 23/1000: L(Train): 0.48211735486984253; L(Test): 0.48378047347068787
Epoch 24/1000: L(Train): 0.48217499256134033; L(Test): 0.4848567843437195
Epoch 25/1000: L(Train): 0.4833751916885376; L(Test): 0.4841863811016083
Epoch 26/1000: L(Train): 0.4814339876174927; L(Test): 0.48092129826545715
Epoch 27/1000: L(Train): 0.4795386791229248; L(Test): 0.47723135352134705
Epoch 28/1000: L(Train): 0.47626033425331116; L(Test): 0.47392556071281433
Epoch 29/1000: L(Train): 0.4719274938106537; L(Test): 0.47099819779396057
Epoch 30/1000: L(Train): 0.46932002902030945; L(Test): 0.46930602192878723
Epoch 31/1000: L(Train): 0.46801021695137024; L(Test): 0.4682892858982086
Epoch 32/1000: L(Train): 0.46725302934646606; L(Test): 0.46691441535949707
Epoch 33/1000: L(Train): 0.4652532935142517; L(Test): 0.4652705788612366
Epoch 34/1000: L(Train): 0.4643108546733856; L(Test): 0.46356457471847534
Epoch 35/1000: L(Train): 0.46218374371528625; L(Test): 0.4618498682975769
Epoch 36/1000: L(Train): 0.4607465863227844; L(Test): 0.46048757433891296
Epoch 37/1000: L(Train): 0.4596553444862366; L(Test): 0.45963671803474426
Epoch 38/1000: L(Train): 0.4585556089878082; L(Test): 0.45903530716896057
Epoch 39/1000: L(Train): 0.45748215913772583; L(Test): 0.4583612084388733
Epoch 40/1000: L(Train): 0.45701277256011963; L(Test): 0.4574832022190094
Epoch 41/1000: L(Train): 0.45531532168388367; L(Test): 0.4564172029495239
Epoch 42/1000: L(Train): 0.4544927477836609; L(Test): 0.45521053671836853
Epoch 43/1000: L(Train): 0.4538067877292633; L(Test): 0.45392805337905884
Epoch 44/1000: L(Train): 0.45260870456695557; L(Test): 0.452810674905777
Epoch 45/1000: L(Train): 0.45103561878204346; L(Test): 0.45189639925956726
Epoch 46/1000: L(Train): 0.4491961896419525; L(Test): 0.45104333758354187
Epoch 47/1000: L(Train): 0.44972771406173706; L(Test): 0.4501436650753021
Epoch 48/1000: L(Train): 0.44773679971694946; L(Test): 0.4492584764957428
Epoch 49/1000: L(Train): 0.44791218638420105; L(Test): 0.4483847916126251
Epoch 50/1000: L(Train): 0.4458170235157013; L(Test): 0.44746094942092896
Epoch 51/1000: L(Train): 0.44535014033317566; L(Test): 0.4465913772583008
Epoch 52/1000: L(Train): 0.44538450241088867; L(Test): 0.4458201825618744
Epoch 53/1000: L(Train): 0.4428001344203949; L(Test): 0.4450489282608032
Epoch 54/1000: L(Train): 0.44288623332977295; L(Test): 0.4442591965198517
Epoch 55/1000: L(Train): 0.4416264593601227; L(Test): 0.4434959590435028
Epoch 56/1000: L(Train): 0.4403335750102997; L(Test): 0.44271719455718994
Epoch 57/1000: L(Train): 0.4412449598312378; L(Test): 0.44193893671035767
Epoch 58/1000: L(Train): 0.4376630485057831; L(Test): 0.4411984980106354
Epoch 59/1000: L(Train): 0.43779170513153076; L(Test): 0.44051533937454224
Epoch 60/1000: L(Train): 0.4369855523109436; L(Test): 0.4398566484451294
Epoch 61/1000: L(Train): 0.4368664622306824; L(Test): 0.43920037150382996
Epoch 62/1000: L(Train): 0.43543383479118347; L(Test): 0.4385547637939453
Epoch 63/1000: L(Train): 0.43515443801879883; L(Test): 0.437908411026001
Epoch 64/1000: L(Train): 0.43410003185272217; L(Test): 0.4372977316379547
Epoch 65/1000: L(Train): 0.43446627259254456; L(Test): 0.4367676079273224
Epoch 66/1000: L(Train): 0.432241290807724; L(Test): 0.43623241782188416
Epoch 67/1000: L(Train): 0.43174076080322266; L(Test): 0.43559902906417847
Epoch 68/1000: L(Train): 0.43183156847953796; L(Test): 0.4349338114261627
Epoch 69/1000: L(Train): 0.43068966269493103; L(Test): 0.434256911277771
Epoch 70/1000: L(Train): 0.4303630292415619; L(Test): 0.4336068034172058
Epoch 71/1000: L(Train): 0.43061673641204834; L(Test): 0.4330061972141266
Epoch 72/1000: L(Train): 0.42920660972595215; L(Test): 0.4324006736278534
Epoch 73/1000: L(Train): 0.42919549345970154; L(Test): 0.43178942799568176
Epoch 74/1000: L(Train): 0.42717158794403076; L(Test): 0.4311721622943878
Epoch 75/1000: L(Train): 0.42719289660453796; L(Test): 0.4305960536003113
Epoch 76/1000: L(Train): 0.42683228850364685; L(Test): 0.43003085255622864
Epoch 77/1000: L(Train): 0.4277783930301666; L(Test): 0.4294518828392029
Epoch 78/1000: L(Train): 0.4263276755809784; L(Test): 0.42885085940361023
Epoch 79/1000: L(Train): 0.42537811398506165; L(Test): 0.4282161295413971
Epoch 80/1000: L(Train): 0.42543476819992065; L(Test): 0.4275849163532257
Epoch 81/1000: L(Train): 0.4243084490299225; L(Test): 0.4269648492336273
Epoch 82/1000: L(Train): 0.4245903789997101; L(Test): 0.4264073073863983
Epoch 83/1000: L(Train): 0.42332667112350464; L(Test): 0.4258774220943451
Epoch 84/1000: L(Train): 0.4221171438694; L(Test): 0.425344854593277
Epoch 85/1000: L(Train): 0.42296749353408813; L(Test): 0.42483076453208923
Epoch 86/1000: L(Train): 0.4221969544887543; L(Test): 0.42431890964508057
Epoch 87/1000: L(Train): 0.42040225863456726; L(Test): 0.42379236221313477
Epoch 88/1000: L(Train): 0.4205343425273895; L(Test): 0.4232867658138275
Epoch 89/1000: L(Train): 0.41899892687797546; L(Test): 0.4227520227432251
Epoch 90/1000: L(Train): 0.4202115535736084; L(Test): 0.42220816016197205
Epoch 91/1000: L(Train): 0.4185218811035156; L(Test): 0.42167842388153076
Epoch 92/1000: L(Train): 0.4174858629703522; L(Test): 0.42118334770202637
Epoch 93/1000: L(Train): 0.41777995228767395; L(Test): 0.42069822549819946
Epoch 94/1000: L(Train): 0.417469322681427; L(Test): 0.42021945118904114
Epoch 95/1000: L(Train): 0.41688477993011475; L(Test): 0.41973090171813965
Epoch 96/1000: L(Train): 0.4166257679462433; L(Test): 0.4191855192184448
Epoch 97/1000: L(Train): 0.4163219630718231; L(Test): 0.4186193346977234
Epoch 98/1000: L(Train): 0.4156458079814911; L(Test): 0.41804689168930054
Epoch 99/1000: L(Train): 0.41399332880973816; L(Test): 0.4175579845905304
Epoch 100/1000: L(Train): 0.4157530665397644; L(Test): 0.41716450452804565
Epoch 101/1000: L(Train): 0.41228142380714417; L(Test): 0.41681763529777527
Epoch 102/1000: L(Train): 0.41204142570495605; L(Test): 0.416312038898468
Epoch 103/1000: L(Train): 0.4134015440940857; L(Test): 0.4158467650413513
Epoch 104/1000: L(Train): 0.413033664226532; L(Test): 0.4154609739780426
Epoch 105/1000: L(Train): 0.41201600432395935; L(Test): 0.41518422961235046
Epoch 106/1000: L(Train): 0.41204673051834106; L(Test): 0.41491416096687317
Epoch 107/1000: L(Train): 0.41171473264694214; L(Test): 0.4145652949810028
Epoch 108/1000: L(Train): 0.4117625653743744; L(Test): 0.41422781348228455
Epoch 109/1000: L(Train): 0.4107396900653839; L(Test): 0.41393187642097473
Epoch 110/1000: L(Train): 0.41167891025543213; L(Test): 0.4136887192726135
Epoch 111/1000: L(Train): 0.4089062511920929; L(Test): 0.41338998079299927
Epoch 112/1000: L(Train): 0.41132596135139465; L(Test): 0.4130961000919342
Epoch 113/1000: L(Train): 0.4099373519420624; L(Test): 0.4128701090812683
Epoch 114/1000: L(Train): 0.40933579206466675; L(Test): 0.4126374125480652
Epoch 115/1000: L(Train): 0.4094116985797882; L(Test): 0.41240471601486206
Epoch 116/1000: L(Train): 0.4097832143306732; L(Test): 0.4122273325920105
Epoch 117/1000: L(Train): 0.4090586304664612; L(Test): 0.41208428144454956
Epoch 118/1000: L(Train): 0.40745750069618225; L(Test): 0.411896288394928
Epoch 119/1000: L(Train): 0.4082615375518799; L(Test): 0.4116417467594147
Epoch 120/1000: L(Train): 0.4075612723827362; L(Test): 0.4113914966583252
Epoch 121/1000: L(Train): 0.40762361884117126; L(Test): 0.4111960232257843
Epoch 122/1000: L(Train): 0.40798208117485046; L(Test): 0.4111166000366211
Epoch 123/1000: L(Train): 0.4069451093673706; L(Test): 0.41103723645210266
Epoch 124/1000: L(Train): 0.40684813261032104; L(Test): 0.41071537137031555
Epoch 125/1000: L(Train): 0.40816980600357056; L(Test): 0.41049128770828247
Epoch 126/1000: L(Train): 0.4071959853172302; L(Test): 0.4103689193725586
Epoch 127/1000: L(Train): 0.4059047996997833; L(Test): 0.4103953540325165
Epoch 128/1000: L(Train): 0.40572789311408997; L(Test): 0.4102822542190552
Epoch 129/1000: L(Train): 0.4061456322669983; L(Test): 0.41003087162971497
Epoch 130/1000: L(Train): 0.4051218032836914; L(Test): 0.40979400277137756
Epoch 131/1000: L(Train): 0.40413898229599; L(Test): 0.4096945524215698
Epoch 132/1000: L(Train): 0.40464967489242554; L(Test): 0.40968039631843567
Epoch 133/1000: L(Train): 0.40463945269584656; L(Test): 0.40971463918685913
Epoch 134/1000: L(Train): 0.40452343225479126; L(Test): 0.40939900279045105
Epoch 135/1000: L(Train): 0.40529781579971313; L(Test): 0.4091946482658386
Epoch 136/1000: L(Train): 0.40540337562561035; L(Test): 0.40918534994125366
Epoch 137/1000: L(Train): 0.404796302318573; L(Test): 0.4093097448348999
Epoch 138/1000: L(Train): 0.40505287051200867; L(Test): 0.4091614782810211
Epoch 139/1000: L(Train): 0.40237000584602356; L(Test): 0.4088689684867859
Epoch 140/1000: L(Train): 0.40437719225883484; L(Test): 0.40876784920692444
Epoch 141/1000: L(Train): 0.4036840498447418; L(Test): 0.4087759554386139
Epoch 142/1000: L(Train): 0.4033176600933075; L(Test): 0.40881994366645813
Epoch 143/1000: L(Train): 0.4026821255683899; L(Test): 0.40869125723838806
Epoch 144/1000: L(Train): 0.40432384610176086; L(Test): 0.4085220992565155
Epoch 145/1000: L(Train): 0.402101069688797; L(Test): 0.40836647152900696
Epoch 146/1000: L(Train): 0.40310075879096985; L(Test): 0.4082746207714081
Epoch 147/1000: L(Train): 0.40266352891921997; L(Test): 0.40824803709983826
Epoch 148/1000: L(Train): 0.4015120565891266; L(Test): 0.40810495615005493
Epoch 149/1000: L(Train): 0.4029194712638855; L(Test): 0.4079391360282898
Epoch 150/1000: L(Train): 0.401215523481369; L(Test): 0.40778040885925293
Epoch 151/1000: L(Train): 0.4025183916091919; L(Test): 0.40770936012268066
Epoch 152/1000: L(Train): 0.4013749957084656; L(Test): 0.40769055485725403
Epoch 153/1000: L(Train): 0.40125468373298645; L(Test): 0.40752333402633667
Epoch 154/1000: L(Train): 0.4027305841445923; L(Test): 0.40735024213790894
Epoch 155/1000: L(Train): 0.4019824266433716; L(Test): 0.40734294056892395
Epoch 156/1000: L(Train): 0.4007458984851837; L(Test): 0.4072299599647522
Epoch 157/1000: L(Train): 0.40100619196891785; L(Test): 0.4072052538394928
Epoch 158/1000: L(Train): 0.40021833777427673; L(Test): 0.4071114659309387
Epoch 159/1000: L(Train): 0.4003526270389557; L(Test): 0.4069331884384155
Epoch 160/1000: L(Train): 0.4001697897911072; L(Test): 0.4068627655506134
Epoch 161/1000: L(Train): 0.40236982703208923; L(Test): 0.4068664312362671
Epoch 162/1000: L(Train): 0.40118759870529175; L(Test): 0.4068406820297241
Epoch 163/1000: L(Train): 0.3995674252510071; L(Test): 0.40678998827934265
Epoch 164/1000: L(Train): 0.40041613578796387; L(Test): 0.40658119320869446
Epoch 165/1000: L(Train): 0.4007788300514221; L(Test): 0.4064449071884155
Epoch 166/1000: L(Train): 0.40042799711227417; L(Test): 0.4064267575740814
Epoch 167/1000: L(Train): 0.40033644437789917; L(Test): 0.406454861164093
Epoch 168/1000: L(Train): 0.3997645676136017; L(Test): 0.40638089179992676
Epoch 169/1000: L(Train): 0.39953485131263733; L(Test): 0.406236857175827
Epoch 170/1000: L(Train): 0.3998112082481384; L(Test): 0.40612101554870605
Epoch 171/1000: L(Train): 0.39890408515930176; L(Test): 0.4061179459095001
Epoch 172/1000: L(Train): 0.3982912302017212; L(Test): 0.4061746299266815
Epoch 173/1000: L(Train): 0.3992269039154053; L(Test): 0.40605488419532776
Epoch 174/1000: L(Train): 0.399804025888443; L(Test): 0.4059363901615143
Epoch 175/1000: L(Train): 0.3996768295764923; L(Test): 0.40596306324005127
Epoch 176/1000: L(Train): 0.39945414662361145; L(Test): 0.4060399532318115
Epoch 177/1000: L(Train): 0.39905479550361633; L(Test): 0.40593063831329346
Epoch 178/1000: L(Train): 0.39941418170928955; L(Test): 0.40586626529693604
Epoch 179/1000: L(Train): 0.39863404631614685; L(Test): 0.4058006703853607
Epoch 180/1000: L(Train): 0.39679768681526184; L(Test): 0.4058040976524353
Epoch 181/1000: L(Train): 0.398101806640625; L(Test): 0.40576550364494324
Epoch 182/1000: L(Train): 0.39858946204185486; L(Test): 0.4056248962879181
Epoch 183/1000: L(Train): 0.3980390131473541; L(Test): 0.40558239817619324
Epoch 184/1000: L(Train): 0.3985520303249359; L(Test): 0.4055670201778412
Epoch 185/1000: L(Train): 0.39847493171691895; L(Test): 0.4055628180503845
Epoch 186/1000: L(Train): 0.3973246216773987; L(Test): 0.40546268224716187
Epoch 187/1000: L(Train): 0.39680418372154236; L(Test): 0.40529584884643555
Epoch 188/1000: L(Train): 0.39756062626838684; L(Test): 0.40527620911598206
Epoch 189/1000: L(Train): 0.39685115218162537; L(Test): 0.40541160106658936
Epoch 190/1000: L(Train): 0.39793750643730164; L(Test): 0.4053105115890503
Epoch 191/1000: L(Train): 0.3967348039150238; L(Test): 0.4050867557525635
Epoch 192/1000: L(Train): 0.39724159240722656; L(Test): 0.405061274766922
Epoch 193/1000: L(Train): 0.3976196050643921; L(Test): 0.4051653742790222
Epoch 194/1000: L(Train): 0.3962949216365814; L(Test): 0.40512463450431824
Epoch 195/1000: L(Train): 0.39582428336143494; L(Test): 0.4049355387687683
Epoch 196/1000: L(Train): 0.3974151909351349; L(Test): 0.40491732954978943
Epoch 197/1000: L(Train): 0.39579251408576965; L(Test): 0.4048806130886078
Epoch 198/1000: L(Train): 0.3955804407596588; L(Test): 0.40484437346458435
Epoch 199/1000: L(Train): 0.3956167995929718; L(Test): 0.4048633575439453
Epoch 200/1000: L(Train): 0.395295649766922; L(Test): 0.40471741557121277
Epoch 201/1000: L(Train): 0.3950164318084717; L(Test): 0.40460094809532166
Epoch 202/1000: L(Train): 0.39528053998947144; L(Test): 0.40468475222587585
Epoch 203/1000: L(Train): 0.39685317873954773; L(Test): 0.4046933650970459
Epoch 204/1000: L(Train): 0.3963593542575836; L(Test): 0.4047068655490875
Epoch 205/1000: L(Train): 0.3962472379207611; L(Test): 0.4046279489994049
Epoch 206/1000: L(Train): 0.395773321390152; L(Test): 0.40469273924827576
Epoch 207/1000: L(Train): 0.3968598544597626; L(Test): 0.40459293127059937
Epoch 208/1000: L(Train): 0.396355003118515; L(Test): 0.4045638144016266
Epoch 209/1000: L(Train): 0.3953145146369934; L(Test): 0.40465059876441956
Epoch 210/1000: L(Train): 0.3945760726928711; L(Test): 0.404728502035141
Epoch 211/1000: L(Train): 0.3955153226852417; L(Test): 0.40482431650161743
Epoch 212/1000: L(Train): 0.39526036381721497; L(Test): 0.4047991931438446
Epoch 213/1000: L(Train): 0.39437299966812134; L(Test): 0.40461692214012146
Epoch 214/1000: L(Train): 0.3954298496246338; L(Test): 0.4045655131340027
Epoch 215/1000: L(Train): 0.3954062759876251; L(Test): 0.40462788939476013
Epoch 216/1000: L(Train): 0.39409616589546204; L(Test): 0.4044206142425537
Epoch 217/1000: L(Train): 0.3946089744567871; L(Test): 0.4042344093322754
Epoch 218/1000: L(Train): 0.3936929404735565; L(Test): 0.4041384160518646
Epoch 219/1000: L(Train): 0.39308279752731323; L(Test): 0.40425947308540344
Epoch 220/1000: L(Train): 0.39463701844215393; L(Test): 0.40437576174736023
Epoch 221/1000: L(Train): 0.39388757944107056; L(Test): 0.4041837453842163
Epoch 222/1000: L(Train): 0.3949244022369385; L(Test): 0.40415045619010925
Epoch 223/1000: L(Train): 0.39426180720329285; L(Test): 0.4041999876499176
Epoch 224/1000: L(Train): 0.3953302502632141; L(Test): 0.4042409360408783
Epoch 225/1000: L(Train): 0.3946804106235504; L(Test): 0.4042520821094513
Epoch 226/1000: L(Train): 0.3950914740562439; L(Test): 0.40424078702926636
Epoch 227/1000: L(Train): 0.3940249979496002; L(Test): 0.40419918298721313
Epoch 228/1000: L(Train): 0.3942972719669342; L(Test): 0.40416982769966125
Epoch 229/1000: L(Train): 0.39540624618530273; L(Test): 0.4042365550994873
Epoch 230/1000: L(Train): 0.39484474062919617; L(Test): 0.4043402671813965
Epoch 231/1000: L(Train): 0.3930189311504364; L(Test): 0.40428972244262695
Epoch 232/1000: L(Train): 0.39414405822753906; L(Test): 0.40426912903785706
Epoch 233/1000: L(Train): 0.39297550916671753; L(Test): 0.40429776906967163
Epoch 234/1000: L(Train): 0.3928077518939972; L(Test): 0.4045020639896393
Epoch 235/1000: L(Train): 0.3928722143173218; L(Test): 0.4043639898300171
Epoch 236/1000: L(Train): 0.3927564024925232; L(Test): 0.40414121747016907
Epoch 237/1000: L(Train): 0.39370599389076233; L(Test): 0.40403395891189575
Epoch 238/1000: L(Train): 0.39371156692504883; L(Test): 0.40398064255714417
Epoch 239/1000: L(Train): 0.3944476544857025; L(Test): 0.404109925031662
Epoch 240/1000: L(Train): 0.39335715770721436; L(Test): 0.4038488566875458
Epoch 241/1000: L(Train): 0.394390732049942; L(Test): 0.40365421772003174
Epoch 242/1000: L(Train): 0.3932141661643982; L(Test): 0.4035731852054596
Epoch 243/1000: L(Train): 0.3940460681915283; L(Test): 0.403728723526001
Epoch 244/1000: L(Train): 0.3914600908756256; L(Test): 0.40353450179100037
Epoch 245/1000: L(Train): 0.39218994975090027; L(Test): 0.4034923315048218
Epoch 246/1000: L(Train): 0.39205682277679443; L(Test): 0.40355342626571655
Epoch 247/1000: L(Train): 0.39386314153671265; L(Test): 0.4036363363265991
Epoch 248/1000: L(Train): 0.39318254590034485; L(Test): 0.4034479260444641
Epoch 249/1000: L(Train): 0.3919728100299835; L(Test): 0.4035181999206543
Epoch 250/1000: L(Train): 0.39246803522109985; L(Test): 0.40366610884666443
Epoch 251/1000: L(Train): 0.39335542917251587; L(Test): 0.4036720097064972
Epoch 252/1000: L(Train): 0.3922945261001587; L(Test): 0.40369197726249695
Epoch 253/1000: L(Train): 0.39302167296409607; L(Test): 0.4036955237388611
Epoch 254/1000: L(Train): 0.39210548996925354; L(Test): 0.4037933051586151
Epoch 255/1000: L(Train): 0.39231693744659424; L(Test): 0.4036240577697754
Epoch 256/1000: L(Train): 0.39335593581199646; L(Test): 0.4035857915878296
Epoch 257/1000: L(Train): 0.39208221435546875; L(Test): 0.4036429524421692
Epoch 258/1000: L(Train): 0.3935162425041199; L(Test): 0.4037149250507355
Epoch 259/1000: L(Train): 0.3924044072628021; L(Test): 0.40363383293151855
Epoch 260/1000: L(Train): 0.39250439405441284; L(Test): 0.40359747409820557
Epoch 261/1000: L(Train): 0.39217641949653625; L(Test): 0.4035688638687134
Epoch 262/1000: L(Train): 0.3917790651321411; L(Test): 0.40362343192100525
Epoch 263/1000: L(Train): 0.3921881318092346; L(Test): 0.4036813974380493
Epoch 264/1000: L(Train): 0.3916260004043579; L(Test): 0.4036523103713989
Epoch 265/1000: L(Train): 0.3925085663795471; L(Test): 0.4036610424518585
Epoch 266/1000: L(Train): 0.3917716443538666; L(Test): 0.40361812710762024
Epoch 267/1000: L(Train): 0.3913898766040802; L(Test): 0.40367212891578674
Epoch 268/1000: L(Train): 0.3915291726589203; L(Test): 0.4037353992462158

In [64]:
gru.load_state_dict(torch.load(path_gru, map_location='cpu'))
# gru.to(torch.device('cpu')).eval()

# ANALYSIS

In [65]:
from weinhardt2026.analysis.analysis_model_evaluation import analysis_model_evaluation

In [66]:
print("Model evaluation on training data (for AIC and BIC): ")
analysis_model_evaluation(
    dataset=dataset_train,
    spice_model=estimator,
    benchmark_model=evc,
    gru_model=gru,
)

Model evaluation on training data (for AIC and BIC):
Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...
Computing choice probabilities with SPICE model...

,Trial Lik.,(std),n_parameters,(std),NLL,(std),AIC,BIC
Benchmark,0.570510,0.155808,5.000000,0.000000,0.561225,0.235656,1.276921,1.434114
GRU,0.688373,0.152831,1778.000000,0.000000,0.373424,0.220744,55.676590,111.574440
SPICE-RNN,0.662736,0.148140,88652.000000,0.000000,0.411378,0.213409,2739.649170,5526.744141
SPICE,0.651254,0.148986,13.968255,2.451447,0.428856,0.223454,1.289249,1.729760

In [67]:
print("Model evaluation on held-out data (for average trial likelihood and NLL): ")
analysis_model_evaluation(
    dataset=dataset_test,
    spice_model=estimator,
    benchmark_model=evc,
    gru_model=gru,
)

Model evaluation on held-out data (for average trial likelihood and NLL):
Computing choice probabilities with benchmark model...
Computing choice probabilities with GRU model...
Computing choice probabilities with SPICE model...

,Trial Lik.,(std),n_parameters,(std),NLL,(std),AIC,BIC
Benchmark,0.546267,0.159641,5.000000,0.000000,0.604647,0.263329,1.360615,1.516752
GRU,0.652959,0.152215,1778.000000,0.000000,0.426242,0.225513,54.662266,110.184250
SPICE-RNN,0.646598,0.147069,88652.000000,0.000000,0.436030,0.216039,2683.855469,5452.210938
SPICE,0.634173,0.151276,13.968255,2.455789,0.455433,0.236168,1.333604,1.771229